openthread/ot-br-posix

.travis.yml, .travis/before_install.sh, .travis/script.sh
This PR enables travis cache to avoid compile dependencies again and again.
=> travis cache

.travis/before_install.sh, .uncrustify.cfg, src/agent/border_agent.cpp, src/agent/main.cpp, src/agent/ncp_wpantund.cpp, src/common/code_utils.hpp, src/common/tlv.hpp, src/web/main.cpp, src/web/mdns-publisher/mdns_publisher.cpp, src/web/pskc-generator/pskc.hpp, src/web/utils/encoding.hpp, src/web/web-service/web_service.cpp, src/web/wpan-controller/dbus_base.cpp, src/web/wpan-controller/dbus_get.cpp, src/web/wpan-controller/dbus_scan.cpp, src/web/wpan-controller/wpan_controller.hpp, tests/meshcop/commissioner.cpp
This PR upgrade uncrustify to 0.65 and updated configuration to force braces and space between operands.
=> Upgrade uncrustify to 0.65

.travis.yml, .travis/before_install.sh, .travis/script.sh, script/bootstrap
This PR simulates the raspbian environment with qemu to test building on raspberry pi. Functional test are not included for now because it cannot finish building all dependencies in time.(i.e. 50 minutes, which is the maximum running time allowed for OpenSource project on Travis CI).
=> enable raspbian check

script/bootstrap
=> Fix bug in installing cmake.

script/_initrc, script/_ipforward, script/_nat64, script/_otbr, script/_wpantund, script/bootstrap, script/cibuild, script/server
This PR adds error info when something goes wrong in `./script/`.
=> Add error information in scripts

src/agent/dtls_mbedtls.cpp, src/agent/dtls_mbedtls.hpp
This PR removes boost dependency from otbr-agent.
=> Remove boost dependency from otbr-agent.

src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/coap.hpp, src/agent/coap_libcoap.cpp, src/agent/coap_libcoap.hpp, src/agent/dtls_mbedtls.cpp, src/agent/ncp_wpantund.cpp, tests/meshcop/commissioner.cpp, tests/unit/Makefile.am, tests/unit/test_coap.cpp, tests/unit/test_logging.cpp
This PR refined the CoAP interface to allow different request and response handler having different contexts. This PR is preparing for support more services besides border agent.
This PR also adds unit test for CoAP.
=> Allow request and response handlers having different contexts.

script/_otbr, src/agent/Makefile.am, src/agent/agent_instance.cpp, src/agent/agent_instance.hpp, src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/coap.hpp, src/agent/coap_libcoap.hpp, src/agent/dtls.hpp, src/agent/dtls_mbedtls.cpp, src/agent/dtls_mbedtls.hpp, src/agent/main.cpp, src/agent/ncp.hpp, src/common/event_emitter.hpp, tests/meshcop/commissioner.cpp
This PR pulls NCP controller and TMF agent out from border agent so that they can be shared with other features.
=> Add agent instance for sharing services.

src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/coap.hpp, src/agent/uris.hpp, tests/meshcop/commissioner.cpp
This PR updates prefix of the URI definitions, also fixed several documentation warnings.
=> Update URI prefix and fix documentation warnings.

src/agent/Makefile.am, src/agent/agent_instance.cpp, src/agent/agent_instance.hpp, src/agent/border_agent.cpp, src/agent/dtls_mbedtls.cpp, src/agent/dtls_mbedtls.hpp, src/agent/main.cpp, src/agent/mdns_avahi.cpp, src/agent/ncp.hpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp
This PR simply removes exceptions from *otbr-agent*, as suggested in [Google C++ style guide](https://google.github.io/styleguide/cppguide.html#Exceptions).
=> [agent] disable exceptions.

script/bootstrap
This PR adds rpm support in bootstrap. This fixes #83
=> [script] support fedora.

src/common/logging.cpp
This PR fixes conversion warnings in logging module. This PR also reuses the existing GetNow() API.
```
otbr-0.1.0-r1: logging.cpp:124:12: error: implicit conversion changes signedness: '__time_t' (aka 'long') to 'uint64_t' (aka 'unsigned long long') [-Werror,-Wsign-conversion]
otbr-0.1.0-r1:     v = tv.tv_sec;
otbr-0.1.0-r1:       ~ ~~~^~~~~~
otbr-0.1.0-r1: logging.cpp:126:25: error: implicit conversion changes signedness: 'long' to 'unsigned long long' [-Werror,-Wsign-conversion]
otbr-0.1.0-r1:     v = v + (tv.tv_usec / 1000);
otbr-0.1.0-r1:           ~  ~~~~~~~~~~~^~~~~~
otbr-0.1.0-r1: logging.cpp:133:12: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
otbr-0.1.0-r1:     return v;
otbr-0.1.0-r1: …
```
=> [logging] fix conversion warnings.

src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/uris.hpp, src/common/logging.cpp
This PR adds more resources for commissioner.
This PR also allows null pointer passed to `otbrDump()`. This still needs to be improved, but I don't have enough time to clean up this part right now.
=> [agent] add dataset uris.

script/_dns64, script/_nat64, script/bootstrap, script/setup
This pull request adds support for DNS64. I've checked and it works on ubuntu and raspbian (I've enabled also NAT64 support on raspbian platform).
=> [dns64] add support for DNS64

README.md
Mirrored what we did for the openthread repo.
=> [docs] Updating README now that openthread.io has launched

script/_dns64, script/_nat64, script/update
This pull request fixes problem with adding localhost nameserver under ubuntu platform.
=> Improve DNS64 script.

script/_dhcpv6_pd, script/_network_manager
This pull request improve DHCPv6-PD which sometimes doesn't work. There were bug that don't restart dhcpcd on interface on which dhcpcd is not active.
=> Improve DHCPv6 PD.

src/web/web-service/frontend/join.dialog.html, src/web/web-service/wpan_service.cpp
There are both frontend and backend problems to use otbr web gui to join a thread network.
- fix frontend bug that join button doesn't even post to server
- update deprecated property to set network key
=> Fix join thread network from web gui

src/web/web-service/wpan_service.cpp
Fix overflow of pskcStr since it is manipulated by strlen() in dbus_set.cpp
=> [wpan-service] fix pskc buffer overflow

src/agent/border_agent.cpp, src/agent/border_agent.hpp, tests/meshcop/Makefile.am, tests/meshcop/commissioner.cpp, tests/meshcop/commissioner_argcargv.hpp, tests/meshcop/meshcop, tests/meshcop/meshcop_ftd, tests/meshcop/meshcop_mtd
* randomized *xpanid*, *panid* and *masterkey*.
* added mtd joiner test.
* aligned `tests/meshcop/meshcop` to google shell style.
=> Enhance MeshCoP test

.travis.yml, .travis/before_install.sh, .travis/script.sh, configure.ac, src/agent/Makefile.am, src/agent/border_agent.cpp, src/agent/main.cpp, src/agent/mdns.hpp, src/agent/mdns_avahi.hpp, src/agent/mdns_mdnssd.cpp, src/agent/mdns_mdnssd.hpp, tests/Makefile.am, tests/mdns/Makefile.am, tests/mdns/test-multiple, tests/mdns/test-single, tests/mdns/test-stop, tests/mdns/test-update, tests/mdns/test_init
* added mdnsresponder adapter for otbr-agent
* added a new check for the new mdns publisher
=> [agent] add mDNSResponder adapter

tests/meshcop/meshcop
This accelerates quick test locally.
=> [test] use installed wpantund and openthread

Android.mk, third_party/wpantund/Makefile.am, third_party/wpantund/README.md, third_party/wpantund/repo/src/ipc-dbus/wpan-dbus-v1.h, third_party/wpantund/repo/src/util/string-utils.c, third_party/wpantund/repo/src/wpanctl/wpanctl-utils.c, third_party/wpantund/repo/src/wpanctl/wpanctl-utils.h, third_party/wpantund/repo/src/wpantund/wpan-properties.h, third_party/wpantund/repo/third_party/openthread/src/ncp/spinel.h
Sync with wpantund to fix failing to find the right d-bus on desktop environment issue caused by `DBUS_BUS_STARTER`.
=> [agent] fix failing to find d-bus connection

.codecov.yml, src/agent/dtls_mbedtls.cpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, tests/meshcop/commissioner.cpp, tests/meshcop/meshcop
* set mbedtls logging level according to otbr log level
* remove duplicated code
* add additional calls to improve code coverage
=> [code] clean up code

.travis/before_install.sh, .travis/script.sh, script/_nat64
tayga inner ipv6 address should be specified for default ipv6 translation prefix
=> [nat64] fix tayga start

.travis.yml, .travis/before_install.sh, .travis/check-android-build, .travis/script.sh
same as openthread/openthread#3090
=> [travis] fix android check

.codecov.yml, src/agent/dtls_mbedtls.cpp
This PR fixes infinite loop when for some reason there is no data ready.
=> [dtls] fix infinite loop

script/bootstrap
These packages may not be installed on raspbian.
=> [bootstrap] install automake and autoconf

src/commissioner/commissioner_argcargv.cpp
* fixed missing help option
* corrected typo in help
=> [commissioner] fix missing help

src/agent/border_agent.cpp, src/agent/ncp.hpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, src/agent/otbr-agent.init.in, tests/meshcop/meshcop
Quick fix for failure caused by the name change. I will submit another PR after wpantund updated the name.
=> [agent] rename UDP proxy to UDP forward

script/bootstrap
This may solve issue https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openthread-users/ORCa8Yg1n9w/tXii2w_mDAAJ
=> [dns64] install resolvconf

script/server
Add mdns support for commissioner app to work.
@Vyrastas The docker prebuilt image needs to be updated after this PR and https://github.com/openthread/borderrouter/pull/232 is merged.
=> [script] add avahi to server script

.gitmodules, .travis/before_install.sh, .travis/script.sh, Android.mk, configure.ac, script/test, src/agent/Makefile.am, src/agent/agent_instance.cpp, src/agent/agent_instance.hpp, src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/main.cpp, src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, src/web/Makefile.am, src/web/web-service/ot_client.cpp, src/web/web-service/ot_client.hpp, src/web/web-service/wpan_service.cpp, src/web/web-service/wpan_service.hpp, tests/scripts/meshcop, third_party/openthread/Makefile.am, third_party/openthread/mbedtls-config.h, third_party/openthread/mbedtls.mk, third_party/openthread/openthread.mk
* add a new implementation of `Ncp::Controller` based on OpenThread daemon mode
* add support in web GUI
* add CI tests for this new mode
=> [agent] use OpenThread daemon

.travis.yml, .travis/check-android-build, Android.mk, configure.ac, src/agent/border_agent.cpp
=> [agent] allow no mDNS

.travis.yml, .travis/check-scripts, configure.ac, src/agent/agent_instance.cpp, src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/main.cpp, src/agent/mdns_avahi.cpp, src/agent/mdns_mdnssd.cpp, src/agent/mdns_mdnssd.hpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, src/commissioner/addr_utils.cpp, src/commissioner/commissioner.cpp, src/commissioner/commissioner.hpp, src/commissioner/commissioner_argcargv.cpp, src/commissioner/commissioner_utils.hpp, src/commissioner/joiner_session.cpp, src/commissioner/main.cpp, src/common/dtls_mbedtls.hpp, src/common/logging.cpp, src/common/logging.hpp, src/utils/pskc.cpp, src/utils/steering_data.cpp, tests/scripts/meshcop, tests/unit/test_coap.cpp, third_party/libcoap/repo/include/coap/prng.h, tools/steering_data.cpp
This PR mainly allows starting otbr-agent before wpantund is started.
* updated to latest OpenThread
* fixed many conversion warnings
* updated check script to verify otbr-agent is ready
* added clang build and clang code coverage support.
=> [border-agent] auto start/stop border agent

configure.ac, src/agent/otbr-agent.conf.in
Same as wpantund, allowing own the service with another user.
=> [agent] configure service user

script/_dhcpv6_pd, script/_disable_services, script/_initrc, script/_wpantund, script/standalone_ipv6
This PR fixes the `with()` function so that it will do respect environment configurations over default configurations.
This PR also fixes many style issues.
=> [script] fix with() and style

.travis/check-docker, etc/docker/Dockerfile, etc/docker/docker_entrypoint.sh, script/bootstrap
It seems docker hub builder does not recognize `[`.
=> [script] fix script for docker

etc/docker/Dockerfile, script/bootstrap
git should be installed before running `script/*`.
=> [docker] install git in Dockerfile

STYLE_GUIDE.md, configure.ac, src/web/Makefile.am
This PR switches compiler to C++11.
=> [build] switch to c++11

configure.ac, src/Makefile.am, src/common/Makefile.am, third_party/Makefile.am, third_party/openthread/Makefile.am
Disable commissioner also disables all its dependencies.
=> [build] add option to disable commissioner

Android.mk, src/agent/border_agent.cpp, src/agent/mdns_avahi.cpp, src/agent/mdns_mdnssd.cpp, src/agent/ncp_wpantund.cpp, src/commissioner/addr_utils.cpp, src/commissioner/commissioner.cpp, src/utils/Makefile.am, src/utils/strcpy_utils.cpp, src/utils/strcpy_utils.hpp, src/web/web-service/ot_client.cpp, src/web/wpan-controller/dbus_base.cpp, src/web/wpan-controller/dbus_ifname.cpp, src/web/wpan-controller/wpan_controller.cpp
Fixes https://github.com/openthread/ot-br-posix/issues/243
=> [misc] use safe wrapped version of strcpy instead

.travis.yml, .travis/check-android-build, Android.mk, etc/libchrome_stub/Android.mk, etc/libchrome_stub/third_party/chromecast/mojom/mdns.mojom.h, src/agent/mdns_mojo.hpp
Add test stubs for Android.mk build test.
Set mojo as default mDNS implementation in Android.mk.
=> [mdns] mojo test stubs for Android.mk

tests/scripts/meshcop, third_party/openthread/Makefile.am, third_party/openthread/openthread.mk
This commit updates OpenThread, also fixes build failures.
=> [build] update OpenThread to latest version

configure.ac, src/agent/Makefile.am, third_party/wpantund/Makefile.am
This commit fix the case when it won't use dbus.
=> [build] fix build without dbus

src/web/web-service/frontend/res/js/app.js
Fixes https://github.com/openthread/ot-br-posix/issues/321
=> [web] fix frontend compatibility issue for commission

etc/libchrome_stub/third_party/chromecast/mojom/mdns.mojom.h, src/agent/border_agent.cpp, src/agent/mdns_mojo.cpp, src/agent/mdns_mojo.hpp, tests/mdns/mdns_mojo_test/client.cpp
Add retry timeout for connecting to mojo broker
Fix initialization issue when wpantund is not launched
=> [border-agent] fix mDNS with mojo initialization issue (#328)

src/agent/agent_instance.hpp, src/agent/main.cpp, src/agent/ncp.hpp, src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, src/web/web-service/ot_client.cpp
This commit update OpenThread code to the latest version.
=> [openthread] update to commit 5121754

configure.ac, src/agent/Makefile.am, src/agent/main.cpp, src/agent/ncp_wpantund.cpp, src/agent/ncp_wpantund.hpp, src/agent/otubus.cpp, src/agent/otubus.hpp, src/openwrt/controller/thread.lua, src/openwrt/handle_error.js, src/openwrt/otbr, src/openwrt/view/admin_thread/thread_add.htm, src/openwrt/view/admin_thread/thread_join.htm, src/openwrt/view/admin_thread/thread_overview.htm, src/openwrt/view/admin_thread/thread_scan.htm, src/openwrt/view/admin_thread/thread_setting.htm, src/openwrt/view/admin_thread/thread_view.htm, third_party/openthread/openthread.mk
This commit submits the initial implementation of ot-br-posix on OpenWRT.
Implemented functions are as follows:
* overview page
* setting page
* scan page
* view page
* add joiner page
* attach page
=> [openwrt] initial implementation

src/agent/mdns_mojo.cpp, tests/mdns/mdns_mojo_test/stub_mojo_service.cpp
Migrate base::MessageLoops to base::SingleThreadTaskExecutor
=> [mojo] fix test stub build break

.travis.yml, .travis/before_install.sh, .travis/check-raspbian, configure.ac, script/_otbr, script/_wpantund, script/bootstrap, tests/scripts/meshcop, tests/unit/test_event_emitter.cpp, tests/unit/test_logging.cpp
This upgrade travis tests to run on Ubuntu 18.04.
=> [travis] use bionic

.travis.yml, .travis/check-posix, tests/mdns/test-mojo
Add httplib2 dependency for mojo test and move it to allow_failures
due to instability of chromium code base.
Install cpputest for the unit tests.
=> [travis] fix build errors

.gitignore, configure.ac, src/dbus/Makefile.am, src/dbus/dbus_message_helper.cpp, src/dbus/dbus_message_helper.hpp, src/dbus/dbus_object.cpp, src/dbus/dbus_object.hpp, src/dbus/dbus_request.hpp, src/dbus/dbus_resources.hpp, src/dbus/dbus_server_test.cpp, tests/unit/Makefile.am, tests/unit/test_dbus_message.cpp
This change provides a dbus server base class and a dbus message parser
and encoder based on the tuple type.
=> [dbus] DBus server library

src/dbus/instropect.xml
This change contains a preview of Thread network management d-bus api.
=> [dbus] introspect xml

.travis.yml, .travis/before_install.sh, .travis/script.sh, CONTRIBUTING.md, Makefile.am, STYLE_GUIDE.md, configure.ac, script/clang-format, script/clang-format-check, script/make-pretty, src/Makefile.am, tests/mdns/mdns_mojo_test/client.cpp
=> [script] sync make-pretty scripts from openthread

.github/workflows/build.yml, .travis.yml, tests/scripts/bootstrap.sh
Github actions provide more coherent machines and will boost the CI check.
=> [github-actions] add pretty check

.travis.yml, configure.ac, etc/openwrt/openthread-br/Makefile, etc/openwrt/openthread-br/README.md, script/test, src/Makefile.am, src/agent/Makefile.am, src/agent/main.cpp, src/agent/otubus.cpp, src/agent/otubus.hpp, src/openwrt/otbr-agent, src/web/web-service/wpan_service.hpp, src/web/wpan-controller/dbus_get.cpp, tests/Makefile.am, tests/dbus/Makefile.am, tests/scripts/meshcop, tests/scripts/openwrt, tests/unit/Makefile.am, third_party/openthread/Makefile.am, third_party/openthread/mbedtls-config.h
* Use **openthread-br** as the package name instead of openthread.
* Added a OpenWRT Makefile and README at `etc/openwrt` to guide
development for OpenWRT.
* Updated OpenThread to support detect big endian automatically.
* Added openwrt-check in travis-ci.
* Fixed crash on start
=> [openwrt] fix building on OpenWRT

.github/workflows/raspbian.yml, etc/docker/docker_entrypoint.sh, etc/openwrt/openthread-br/README.md, script/console, src/agent/main.cpp, src/agent/ncp.hpp, src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, src/openwrt/otbr-agent.init.in, tests/dbus/test-client, tests/scripts/check-scripts, tests/scripts/meshcop
* split out the unstable raspbian check
=> [agent] transition to radio url

.gitmodules
This commit changes the submodule to track a branch instead of a commit.
=> [openthread] track a branch instead of commit

src/agent/border_agent.cpp, src/mdns/mdns_avahi.cpp, src/mdns/mdns_mdnssd.cpp, tests/mdns/main.cpp, tests/mdns/test-multiple, tests/mdns/test-single, tests/mdns/test-stop, tests/mdns/test-update
Fixes https://github.com/openthread/ot-br-posix/issues/419
=> [mdns] publish binary xpanid in mdns text

src/web/web-service/web_server.cpp
This commit outputs more exception information when the path is invalid.
=> [web] verbose invalid path exception

Android.mk, src/agent/CMakeLists.txt, src/agent/otbr-agent.conf.in
This allows users other than root to use otbr-agent service.
=> [dbus] add group for client

script/bootstrap
=> [bootstrap] install dnsmasq with network-manager

script/_otbr
This reverts commit bd8b7fc176bf1acea0bd1283fd0aa325bf595460.
=> Revert "[scripts] fix ninja build log permissions (#489)"

src/agent/main.cpp, src/agent/ncp_openthread.cpp
Fixes https://github.com/openthread/openthread/issues/5177
=> [log] fix openthread logging not availbe upon init

script/test, tests/dbus/CMakeLists.txt, tests/dbus/test-client, tests/dbus/test_dbus_client.cpp
This helps to test the logic of scan, neighbor table and child table.
=> [test] add other nodes in the dbus test

src/agent/thread_helper.cpp, tests/dbus/test-client, tests/scripts/bootstrap.sh
* Should not close interface upon join failure
* Fix wrong API call to start Thread
* Add tests for joining
=> [joiner] fix joining behavior

.github/workflows/docker.yml
This PR enhance the docker build test to use more options. 
**This PR also builds and pushes openthread/otbr:reference-device** for certification purpose.
=> [github-actions] build docker image for reference device

src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, tests/dbus/test-client
This allows users to get/set the region code over OpenThread cli.
=> [cli] add cli support for region code

.github/workflows/macOS.yml, .travis.yml, .travis/script.sh
=> [test] fix build check on macOS

src/openwrt/ubus/otubus.cpp
fixes rloc mismatch issue reported in #610.
=> [openwrt] fix rloc16 in little endian system

script/_network_manager, tests/scripts/check-scripts
=> [script] fix starting network manager

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/macOS.yml, .github/workflows/raspbian.yml, tests/scripts/bootstrap.sh
to eliminate **Annotations**
- `package` is still using `ubuntu-18.04` because it installs `cmake==3.10.3`, which will fail on ubuntu 20.04.
=> [github-actions] switch to ubuntu 20.04

CMakeLists.txt, src/agent/instance_params.hpp, src/agent/main.cpp, src/backbone_router/backbone_agent.hpp
Depends on: https://github.com/openthread/openthread/pull/5955
=> [backbone-router] add build options for backbone router features

src/agent/main.cpp, src/agent/ncp.hpp, src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, src/dbus/server/dbus_thread_object.cpp, tests/dbus/test-client
This allows the powermap to be dynamically reloaded when user sets the
region. Also fixes the reset behavior of the region code.
=> [radio] pass full power map in command line args

src/agent/main.cpp, src/dbus/client/thread_api_dbus.cpp, src/dbus/client/thread_api_dbus.hpp, src/dbus/server/dbus_thread_object.cpp, src/mdns/mdns_mdnssd.cpp, src/rest/resource.cpp, src/web/web-service/web_server.cpp, tests/unit/test_event_emitter.cpp
address the comment https://github.com/openthread/ot-br-posix/pull/666#discussion_r570683060.
=> [style] replace (void) with OTBR_UNUSED_VARIABLE

src/agent/advertising_proxy.cpp
----
Related to https://github.com/openthread/openthread/pull/6157
Depends-On: https://github.com/openthread/openthread/pull/6157
=> [dns-sd] use new DNS TXT entry iterator

src/agent/border_agent.cpp, src/agent/border_agent.hpp, src/agent/ncp.hpp, src/agent/ncp_openthread.cpp, src/common/types.hpp, src/mdns/mdns_avahi.cpp, tests/mdns/main.cpp, tests/mdns/test-multiple, tests/mdns/test-single, tests/mdns/test-stop, tests/mdns/test-update
addresses https://github.com/openthread/ot-br-posix/issues/520.
=> [mdns] advertise extended address as discriminator

src/agent/ncp_openthread.cpp, src/agent/ncp_openthread.hpp, src/agent/thread_helper.cpp, src/agent/thread_helper.hpp, src/common/task_runner.cpp, src/common/task_runner.hpp, src/common/time.hpp, src/mdns/mdns_avahi.cpp, src/mdns/mdns_avahi.hpp, tests/unit/test_task_runner.cpp
This commit adds the new `Post` API to the `TaskRunner` to execute a task in future.
We also replace the handy `Timers` in openthread controller with the `TaskRunner` API.
=> [utils] post delayed tasks with TaskRunner

.github/dependabot.yml, .github/workflows/backbone_router.yml, .github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/documentation.yml, .github/workflows/meshcop.yml, .github/workflows/openwrt.yml, .github/workflows/raspbian.yml
To enable automatic daily updates of openthread submodule.
=> [dependabot] add config file

src/agent/thread_helper.cpp, src/agent/thread_helper.hpp, src/dbus/common/constants.hpp, src/dbus/server/dbus_thread_object.cpp, src/dbus/server/dbus_thread_object.hpp, src/dbus/server/introspect.xml, tests/dbus/test-client
Fixes <https://github.com/openthread/ot-br-posix/issues/755>.
=> [dbus] add "Detach" API

src/agent/advertising_proxy.cpp, src/agent/advertising_proxy.hpp
dependent changes for https://github.com/openthread/openthread/pull/6407.
- The OTBR CI here expected to fail.
- We need to pull in https://github.com/openthread/openthread/pull/6407 before merging this PR.
=> [advertising-proxy] replace SRP Host pointer with service update ID

src/web/web-service/wpan_service.cpp
fixed parsing of ipv6 addresses + removed duplicate state and add txpower
=> [web-service] fix parsing of ipv6 addresses for status page

src/web/web-service/frontend/index.html, src/web/web-service/ot_client.cpp, src/web/web-service/wpan_service.cpp
- [ot-client] fix bug in stripping `Done\r\n`
- [web-service] fix commissioner 
- [frontend] remove `Network Passphrase` from `Commission`
Fixes #780
=> [web-service] fix commission page

src/web/web-service/web_server.cpp
help figuring out what is going wrong in issue https://github.com/openthread/ot-br-posix/issues/786.
=> [web-service] catch exceptions in web server

.github/workflows/border_router.yml
This commit adds Border Router tests (BORDER_ROUTING=1) in Github Actions.
=> [github-actions] add border router tests

src/rest/connection.cpp, src/rest/connection.hpp, src/rest/rest_web_server.cpp, src/rest/rest_web_server.hpp, tests/scripts/meshcop
=> [rest] release sockets in destructors

src/web/web-service/wpan_service.cpp, src/web/web-service/wpan_service.hpp
- fix join operation to use Active Timestamp = 0
- include PSKc as part of dataset (not separate cmd)
=> [web-service] fix form/join operations

tests/dbus/test_dbus_client.cpp
Depends on <https://github.com/openthread/openthread/pull/6817>.
=> [tests] add test for `FactoryReset` DBus API

src/openwrt/ubus/otubus.cpp
This fixes the build error caused by API changes in <https://github.com/openthread/openthread/pull/6887>.
=> [openwrt] add callbacks to MGMT API call

tests/scripts/check-raspbian
See https://github.com/openthread/ot-br-posix/runs/3397128069?check_suite_focus=true for the failure.
=> [github-actions] fix raspbian-check failure when `apt-get update`

src/agent/advertising_proxy.cpp
This commit fixes a bug that Advertising Proxy failed to handle duplicate hosts and services in multiple outstanding SRP updates. 
Bug revealed by https://github.com/openthread/openthread/pull/6991
=> [advertising-proxy] handle duplicate hosts/services in SRP updates

src/agent/advertising_proxy.cpp
Revert "[advertising-proxy] handle duplicate hosts/services in SRP updates (#1008)"
This reverts commit 685a1e0f483febc26127c8c2f2bd8f922b682a06.
Fixes #1011
=> Revert #1008

etc/yocto/otbr_git.bb
Provides a sample Yocto recipe to build otbr-agent and set specific build flags.
=> [build] provide a sample Yocto recipe

src/dbus/client/thread_api_dbus.cpp, src/dbus/client/thread_api_dbus.hpp, src/dbus/common/constants.hpp, src/dbus/common/dbus_message_helper.hpp, src/dbus/common/dbus_message_helper_openthread.cpp, src/dbus/common/types.hpp, src/dbus/server/dbus_thread_object.cpp, src/dbus/server/dbus_thread_object.hpp, src/dbus/server/introspect.xml, src/utils/thread_helper.cpp, src/utils/thread_helper.hpp, tests/dbus/test_dbus_client.cpp
This PR adds the 'energy scan' dbus API. This API is for the application level to choose a better channel.
=> [dbus] add energy scan dbus api

src/mdns/mdns_avahi.cpp, src/mdns/mdns_mdnssd.cpp, src/mdns/mdns_mdnssd.hpp
Please only review the last commit @superwhd @jwhui 
Based on #1133  and #1131
=> [mdns-mdnssd] fix potential invalid memory access

src/mdns/mdns.cpp, src/mdns/mdns_mdnssd.cpp, src/mdns/mdns_mdnssd.hpp, src/sdp_proxy/discovery_proxy.cpp, src/sdp_proxy/discovery_proxy.hpp, src/utils/dns_utils.cpp, src/utils/dns_utils.hpp
=> [mdns-mdnssd] support mDNS service removing

src/mdns/mdns.cpp, src/mdns/mdns.hpp, src/mdns/mdns_avahi.cpp, src/mdns/mdns_mdnssd.cpp
=> [mdns] notify service resolved with interface index

examples/platforms/beagleboneblack/default, script/_disable_services, script/bootstrap
=> [platforms] update BeagleBone Black default configuration

Android.mk, src/agent/CMakeLists.txt, src/agent/application.cpp, src/agent/application.hpp, src/agent/main.cpp, src/border_agent/border_agent.cpp, src/ncp/ncp_openthread.cpp, src/utils/thread_helper.cpp
This commit adds the `Application` class for better managing different program components.
=> [main] add `Application` class

src/agent/application.hpp, src/agent/instance_params.hpp, src/backbone_router/backbone_agent.hpp, src/backbone_router/dua_routing_manager.hpp, src/backbone_router/nd_proxy.hpp, src/border_agent/border_agent.hpp, src/common/code_utils.hpp, src/common/mainloop_manager.hpp, src/common/task_runner.hpp, src/dbus/server/dbus_agent.hpp, src/dbus/server/dbus_object.hpp, src/mdns/mdns.hpp, src/mdns/mdns_avahi.hpp, src/mdns/mdns_mdnssd.hpp, src/sdp_proxy/advertising_proxy.hpp, src/sdp_proxy/discovery_proxy.hpp
This commit uses `NonCopyable` to make sure certain objects are never copied.
Should choose the preferred one of https://github.com/openthread/ot-br-posix/pull/1161 and this PR.
=> [utils] add `NonCopyable`

src/dbus/server/dbus_agent.cpp, src/dbus/server/dbus_agent.hpp
Found that `dbus_bus_request_name` may fail on Raspberry Pi. 
This commit fixes the issue by re-connecting DBus in such case.
=> [dbus] fix dbus reconnection

src/mdns/mdns_mdnssd.cpp
Required for debugging https://github.com/openthread/openthread/issues/6654
=> [mdns] add debug logging for the mDNSResponder publisher

src/trel_dnssd/trel_dnssd.cpp
Depends-On: openthread/openthread#7401
=> [trel-dnssd] parse `xa` TXT value as binary

etc/docker/Dockerfile, script/bootstrap
Minor improvements in script/bootstrap and realign etc/docker/Dockerfile with what is being done in script/bootstrap.
=> [docker] cleanup script/bootstrap and etc/docker/Dockerfile

src/web/web-service/frontend/res/js/app.js
This allows to add prefixes to the path part of the URL e.g. when using a reverse proxy.
=> [web] use relative paths in xhr requests

src/trel_dnssd/trel_dnssd.cpp
Fixes https://github.com/openthread/ot-br-posix/issues/1236
=> [trel-dnssd] fix format string

src/mdns/mdns.cpp, src/mdns/mdns_avahi.cpp, src/mdns/mdns_mdnssd.cpp
- Revisit log levels
- Use more proper ways to print integers/enums
- Raise log levels when an error shows up
- Capitalize first letter of every log message
=> [logging] refine mDNS logs

src/dbus/common/dbus_message_helper_openthread.cpp, src/dbus/common/types.hpp, src/dbus/server/dbus_thread_object.cpp, src/dbus/server/introspect.xml, src/openwrt/ubus/otubus.cpp, src/openwrt/view/admin_thread/thread_scan.htm, src/web/web-service/ot_client.cpp, src/web/web-service/wpan_service.cpp, tests/dbus/test_dbus_client.cpp, tests/unit/test_dbus_message.cpp
Thread Specification v1.2.1 removes support for Thread Beacons payload.
=> [mac] remove beacons payload

src/common/logging.cpp, src/common/logging.hpp, src/ncp/ncp_openthread.cpp, src/ncp/ncp_openthread.hpp
Updates OTBR log level when OT log level changes (e.g. by `log level` command).
=> [logging] set OTBR log level when OT log level changes

src/dbus/client/thread_api_dbus.cpp, src/dbus/client/thread_api_dbus.hpp
Implement detach d-bus client API
Return appropriate value from ThreadApiDBus::DBusMessageFilter()
=> [dbus] Implement detach client API

.github/workflows/build.yml, script/test, src/agent/application.cpp, src/agent/application.hpp, src/agent/main.cpp, src/ncp/ncp_openthread.cpp, src/ncp/ncp_openthread.hpp, tests/scripts/auto-attach, tests/scripts/auto-start
This commit adds a command line argument to specify if OTBR automatically attempts to attach after starting.
=> [agent] add command-line arg to disable auto attach

src/dbus/common/constants.hpp, src/dbus/common/dbus_message_helper.hpp, src/dbus/server/dbus_object.cpp, src/dbus/server/dbus_object.hpp, src/dbus/server/dbus_thread_object.cpp, tests/dbus/test-client
This commit makes OTBR emit a DBus signal after initialization.
=> [dbus] add signal for initialization

src/dbus/server/introspect.xml
Fixes these errors: https://github.com/openthread/ot-br-posix/runs/7441973304?check_suite_focus=true
=> [dbus] fix "parser error : StartTag: invalid element name"

.github/workflows/macOS.yml
=> [github-actions] update to macos-12

.github/workflows/border_router.yml
This commit updates settings for the border router nat64 CI tests to reflect the change in [openthread PR #7619](https://github.com/openthread/openthread/pull/7619).
=> [github-actions] update settings for the border router nat64 CI tests

.github/workflows/build.yml
=> [github-actions] migrate to ubuntu 20.04 from 18.04

src/dbus/server/introspect.xml
Fixes: https://github.com/openthread/ot-br-posix/actions/runs/3472887773/jobs/5805605096
=> [dbus] fix doxygen build

Android.mk
Added trel_dnssd.cpp in Android.mk
=> [android] add `trel_dnssd.cpp` to Android.mk

src/rest/rest_web_server.cpp, src/rest/rest_web_server.hpp, src/web/main.cpp
Make the Web and REST API listen on IPv4 and IPv6 by default.
=> [web/rest] listen on IPv6 addresses as well

etc/openwrt/openthread-br/Makefile, etc/openwrt/openthread-br/README.md, src/openwrt/CMakeLists.txt, src/openwrt/otbr-agent.init.in, src/openwrt/otbr-agent.uci-config.in, src/openwrt/otbr-firewall.init.in, src/openwrt/ubus/otubus.cpp, src/openwrt/ubus/otubus.hpp, src/openwrt/view/admin_thread/thread_overview.htm, tests/scripts/openwrt
Some modifications to make ot-br-posix working with OpenWRT.
Compatible with Matter (tested on TE9 and SDK 1.0.0)
This pull request is related to:
- This issue: https://github.com/openthread/ot-br-posix/issues/1250 
- This pull-request: https://github.com/openthread/ot-br-posix/pull/1410
I re-created the pull request to make it clearer.
=> [openwrt] update the Makefile and init scripts

src/common/types.cpp, src/rest/resource.cpp, src/utils/hex.cpp, src/web/web-service/wpan_service.cpp, tests/unit/test_logging.cpp
To resolve this: https://github.com/openthread/ot-br-posix/actions/runs/3969577382/jobs/6805243782
=> [sprintf] replace sprintf with snprintf

tests/scripts/auto-attach
To resolve: https://github.com/openthread/ot-br-posix/actions/runs/4112181186/jobs/7106327761
=> [tests] update router reset wait time

.github/workflows/border_router.yml, src/ncp/ncp_openthread.cpp, src/trel_dnssd/trel_dnssd.cpp
This PR sets trel to disabled if feature flag is used.
Added a test in border_router.yml with both trel and feature flag compiled.
Updated border_router.yml tests to use the OTBR_TREL flag.
=> [trel] disable trel if feature flag is used

.github/workflows/documentation.yml
Fixes https://github.com/openthread/ot-br-posix/actions/runs/5225693754/jobs/9438081812
=> [github-actions] run `tests/scripts/bootstrap.sh` for doc gen

.github/workflows/documentation.yml
Fixes: https://github.com/openthread/ot-br-posix/actions/runs/5250631167/jobs/9484766909
=> [github-actions] specify `BUILD_TARGET` in doc workflow

src/utils/thread_helper.cpp, tests/dbus/test-client, tests/rest/test-rest-server
Resolves GitHub Actions failures: https://github.com/openthread/ot-br-posix/pull/1934
=> [dataset] properly configure operational dataset

src/mdns/mdns_avahi.cpp
This commit updates `TxtDataToAvahiStringList()` to directly use the encoded TXT data entries.
=> [mdns-avahi] simplify TXT data conversion to `AvahiStringList`

src/agent/main.cpp
Existing implementation will re-exec the ot-daemon process itself by leveraging the execvp() system call. This specifically doesn't work on Android for reasons:
1. ot-daemon on Android is managed / controlled by the system_server service which creates TUN FD and manages the enabled states that are essential for the ot-daemon to run. So ot-daemon can't re-start on on its own.
2. execvp() will result in lost of runtime callbacks registered from system_server and put the system into an inconsistent state.
It simplifies the system if the lifecycle of ot-daemon is execlusively managed by the system_server. This also allows us to do optimizations such as tearing down the ot-daemon server to save memory and power when Thread is stopped or disabled.
This commit fixes the the sepolicy denied …
=> [android] exit ot-daemon when factoryreset

.github/workflows/macOS.yml
Fixes: https://github.com/openthread/ot-br-posix/actions/runs/8077912982/job/22069147310?pr=2202
=> [github-actions] add `brew upgrade node`

.github/workflows/macOS.yml
Fixes https://github.com/openthread/ot-br-posix/actions/runs/8230530893/job/22531745159?pr=2217
=> [github-actions] fix macOS CI

script/_initrc, script/server
This PR refactors the `script/server` to reduce duplicate code.
=> [script] refactor `script/server`

.github/workflows/macOS.yml
The cmake option is `OTBR_SRP_ADVERTISING_PROXY`.
=> [github-actions] fix ADVERTISING_PROXY option

src/dbus/common/constants.hpp, src/dbus/server/dbus_thread_object_ncp.cpp, src/dbus/server/dbus_thread_object_ncp.hpp, src/ncp/CMakeLists.txt, src/ncp/async_task.cpp, src/ncp/async_task.hpp, src/ncp/ncp_host.cpp, src/ncp/ncp_host.hpp, src/ncp/ncp_spinel.cpp, src/ncp/ncp_spinel.hpp, src/ncp/rcp_host.cpp, src/ncp/rcp_host.hpp, src/ncp/thread_host.hpp, tests/gtest/CMakeLists.txt, tests/gtest/test_async_task.cpp, tests/scripts/expect/ncp_join_leave.exp, tests/scripts/ncp_mode
This PR adds 'Join' and 'Leave' APIs to `ThreadHost` and implements them under NCP mode.
The PR also adds an expect test to test the two APIs under NCP mode.
=> [controller] add join and leave api

src/dbus/server/dbus_thread_object_rcp.cpp
add dbus limitation when ePSKc feature not enabled
=> [border-agent] add error reply for DeactivateEphemeralKeyMode dbus API

.github/workflows/border_router.yml
With openthread/openthread#10794 and this PR, we should be able to resolve the CI failure in a clean way.
https://github.com/openthread/ot-br-posix/pull/2525 is the PoC for this PR.
=> [tests] update tests according to openthread/openthread#10794

.github/workflows/ncp_mode.yml, script/test, tests/scripts/ncp_mode
This PR enhances the ncp_mode github workflow in CI.
A few enhancement is done:
1. Build docker image in the workflow for testing the border routing functionality.
2. Change the usage of `ncp_mode` script. Use the same parameter style as `script/test`.
3. Accelerate the workflow by avoiding building unnecessary dependencies: openthread library (in bootstrap), unit test, OTBR web
=> [github-action] enhance ncp mode workflow

etc/docker/README.md
This PR adds a README doc for OTBR docker for common issues.
=> [doc] add a README doc for otbr docker for common issues

src/backbone_router/dua_routing_manager.hpp, src/backbone_router/nd_proxy.hpp
Make the ifdef header guard consistent.
=> [backbone-router] make header guard style consistent

src/web/web-service/wpan_service.cpp
Fixes https://github.com/openthread/ot-br-posix/issues/2731.
=> [web] fix the build error caused by deprecated readers and writers

etc/docker/border-router/Dockerfile
=> [docker] remove separate `COPY` command

README.md
Add a badge to repo's README file to enable weekly auto refresh in https://deepwiki.com/openthread/ot-br-posix
=> [docs] add DeepWiki badge link

src/agent/main.cpp, src/common/mainloop_manager.hpp, src/host/posix/cli_daemon.cpp, src/host/posix/infra_if.cpp, src/host/posix/netif_linux.cpp, src/host/posix/udp_proxy.cpp
- Add missing includes of `errno.h`.
- Remove unnecessary include statements.
=> [build] minor improves in include statements

.github/workflows/border_router.yml
Configs are already enabled by default.
=> [github-action] remove redundant OT configs

src/rest/network_diag_handler.cpp, src/rest/openapi.yaml, src/rest/rest_web_server.cpp, src/web/web-service/frontend/index.html, src/web/web-service/frontend/res/js/app.js, tests/restjsonapi/devices/Options.bru
- fix missing cors headers after introducing cpp-httplib
- fix interface to REST API and building the topology view
=> [rest] fix web topology view
