- .travis.yml
- .travis/before_install.sh
- bootstrap
- configure.ac
- src/agent/Makefile.am
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/coap.hpp
- src/agent/coap_libcoap.cpp
- src/agent/coap_libcoap.hpp
- src/agent/dtls.hpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/agent/main.cpp
- src/common/tlv.hpp
- tests/Makefile.am
- tests/meshcop/Makefile.am
- tests/meshcop/commissioner.cpp
- tests/meshcop/meshcop
- third_party/libcoap/Makefile.am
- third_party/libcoap/patch/0001-remove-generated-files-and-fix-separate-response.patch
This PR,
* Adds functional test for meshcop(involves OpenThread, wpantund)
* Formalize the state machine of DTLS session.
* Fix timeout of DTLS.
* Support piggy-back response of CoAP API.
This test is based on the POSIX simulation of OpenThread and wpantund. The scenario is simple. Firstly, create an one node Thread network, thus the only node acts as Thread leader as well as Thread border router. Secondly, authenticate an external commissioner. At last, authenticate the joiner.
Implements a simple commissioner app with fixed PSKd `123456`, steering data(for joiner whose EUI64 is 18b4300000000002) and commissioner id `OpenThread`. It connects to local border agent and petition to be the commissioner. Once success, it will authenticate the joiner.
Latest OpenThread is built to provide …
> Add functional test for meshcop

- README.md
- script/_initrc
- script/_ipforward
- script/_otbr
- script/_wpantund
- script/bootstrap
- script/cibuild
- script/console
- script/server
- script/setup
- script/test
- script/update
This PR adds several scripts according to [Scripts to rule them all](https://github.com/github/scripts-to-rule-them-all)
- *bootstrap* install dependencies.
- *setup* build and install border router, wpantund.
- *update* rebuild border router and update wpantund.
- *server* start wpantund and border router.
- *console* start border router and wpantund.
- *cibuild* used only on travis.
- *test* run test locally.
> Scripts to rule them all

- configure.ac
This PR checks if Exuberant Ctags is available in configure and fails if not. This solves #8
> Check ctags when configure

- examples/platforms/raspbian/after_bootstrap
- script/_initrc
- script/bootstrap
- script/cibuild
- script/console
- script/server
- script/setup
- script/test
- script/update
This PR involves an mechanism to allow adding hooks on certain platform before or after certain script runs its tasks.
Platform is identified based on output of `lsb_release -i`. On raspberry PI 3B, it gives `raspbian`. On ubuntu, it gives `ubuntu`.
To add a hook, create a script file in `examples/platforms/XXX` where XXX is the platform name describe above, and name the script as `before_XXX` or `after_XXX`, XXX is the script filename in `script`, an example hook is provided under `examples/platforms/raspbian/after_bootstrap` to remove *avahi-daemon* which is currently conflict with border router service.
> Task hooks

- script/_nat64
- script/bootstrap
- script/server
- script/setup
- script/update
This PR enables NAT64 service.
> Support nat64

- src/agent/Makefile.am
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/coap.hpp
- src/agent/coap_libcoap.cpp
- src/agent/coap_libcoap.hpp
- src/agent/dtls.hpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_wpantund.cpp
- src/agent/ncp_wpantund.hpp
- tests/meshcop/Makefile.am
- tests/meshcop/commissioner.cpp
- tests/meshcop/meshcop
This PR changes the top level namespace of *otbr-agent* side from `ot::BorderAgent` to `ot::BorderRouter`.
> Update otbr-agent top level namespace to ot::BorderRouter

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
- bootstrap
- configure.ac
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/coap_libcoap.cpp
- src/agent/dtls_mbedtls.cpp
- src/agent/ncp_wpantund.cpp
- src/web/Makefile.am
- src/web/web-service/web_service.cpp
- src/web/wpan-controller/dbus_get.cpp
- src/web/wpan-controller/dbus_scan.cpp
- tests/meshcop/commissioner.cpp
- third_party/libcoap/Makefile.am
- third_party/libcoap/patch/0001-remove-generated-files-and-fix-separate-response.patch
- third_party/libcoap/patch/0002-fix-warnings.patch
- third_party/mbedtls/Makefile.am
- third_party/wpantund/Makefile.am
This PR,
1. adds `scan-build` check
2. adds `-Werror` to `CFLAGS`
3. fixes a mistake in libcoap patch
3. fixes some warnings in libcoap
> Make checks more strict

- src/agent/otbr-agent.service.in
- src/web/otbr-web.service.in
- third_party/wpantund/wpantund.service.in
Currently, OTBR mainly runs three services provided by OpenThread(wpantund, otbr-web, otbr-agent). Although they are already managed by systemd, but the configuration files are not properly set to make sure these services be restarted if some unexpected error happened. Especially for the case that NCP is unplugged, wpantund dies and will not recover.
This PR utilizes systemd's restart on-failure feature to make sure these services be restarted once exited unexpectedly. With this PR,  when unplugging NCP, systemd will try starting wpantund every 5s. Thus when the device is plugged, wpantund and otbr-agent can recover.
More information
* [1] https://www.freedesktop.org/software/systemd/man/systemd.service.html
* [2] https://www.freedesktop.org/software/systemd/man/systemd.unit.html
> Make OTBR services robust

- src/agent/border_agent.cpp
- src/agent/dtls.hpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
This PR fixes the issue that mbedDTLS is not proper seeded. This is caused by configuring CTR_DRBG before initializing seed.
> Fix seed mbedDTLS

- src/agent/Makefile.am
- src/agent/otbr-agent.default
- src/agent/otbr-agent.service.in
This PR adds the default configuration file for otbr-agent.
For the sake of user friendly, the configuration file will not be overwritten by`make install`.
> Add otbr-agent configuration file

- .travis.yml
- .travis/before_install.sh
- .travis/script.sh
- bootstrap
- script/console
- script/server
This PR adds a new Travis target `script-check` to check `script/*` functionality.
To keep the default NCP device path as `/dev/ttyUSB0` for wpantund, this PR simulates the NCP device with *socat* and *OpenThread NCP POSIX simulation*.
This target is not fully finished yet, because currently we only provide systemd service files, however Travis build system is based on Ubuntu trusty, which uses upstart as the init system. This target should be improved when this compatible issue was resolved.
Currently this target checks,
* `script/bootstrap`
* `script/setup`
* `script/console`
> Add script-check Travis target

- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/common/types.hpp
This PR fixes the issue that when there are multiple address on border router. The DTLS session may not be stable and causes the DTLS session cannot be established or hang.
This is caused by mbedTLS ignores the original destination address of packets when binding the socket session. This PR retrieves the original destination, then bind and connect the socket for mbedTLS.
With this PR, border router can both support IPv4 and IPv6 on external link.
> Support listening on multiple addresses.

- src/agent/border_agent.cpp
- src/agent/dtls_mbedtls.cpp
- src/common/logging.cpp
- src/common/logging.hpp
This PR adds otbrDump to dump memory as hex string for debugging.
> Add otbrDump() in the logging library.

- src/agent/Makefile.am
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/ncp.hpp
- src/agent/ncp_wpantund.cpp
- src/agent/ncp_wpantund.hpp
- src/agent/otbr-agent.conf
- src/common/Makefile.am
- src/common/event_emitter.cpp
- src/common/event_emitter.hpp
- tests/unit/Makefile.am
- tests/unit/test_event_emitter.cpp
This PR implements an event emitter and refines the NCP controller with it.
Spinel defined many properties for OpenThread. The formats of those properties vary a lot. As more and more properties are to watched for changes, defining handlers for every property bloats the source code. A generic mechanism is needed.
This PR implements a simple `EventEmitter` based on `stdarg`, which supports,
* Multiple handlers for single event,
* Dynamically add and remove event handler,
* Each handler can have different context.
> Add event emitter and refine NCP controller

- .travis/before_install.sh
- tests/unit/Makefile.am
- tests/unit/test_logging.cpp
This PR fixes a mistake in `otbrDump()` about the size of memory. Also this PR adds a unit test for logging functionality.
> Fix otbrDump mistake and add logging unit test.

- src/agent/border_agent.cpp
- src/agent/dtls.hpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_wpantund.cpp
- src/agent/ncp_wpantund.hpp
- src/common/types.hpp
This PR improves the error code handling in otbr-agent. Since otbr-agent utilizes several third-party libraries, instead of defining a set of error codes, this PR defines category of error code, and tries to map errors to appropriate errno defined by POSIX and c99 if possible.
> Improve error handling in otbr-agent.

- doc/Doxyfile.in
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/coap.hpp
- src/agent/coap_libcoap.cpp
- src/agent/coap_libcoap.hpp
- src/agent/dtls.hpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/agent/libcoap.h
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_wpantund.cpp
- src/agent/ncp_wpantund.hpp
- src/agent/uris.hpp
- src/common/event_emitter.hpp
- src/common/types.hpp
- tests/meshcop/commissioner.cpp
This PR improves the comments and logging messages. Also adjusted some variable names.
> Improve documentation and logging messages.

- bootstrap
- configure.ac
- third_party/libcoap/Makefile.am
- third_party/libcoap/patch/0003-disable-documentation.patch
This PR disables building libcoap documentation and skip installing this library.
> Disable libcoap documentation and installation.

- src/web/web-service/wpan_service.cpp
It is not necessary to add `leave` before `scan` available networks, which may impact on the existing wpan status if the OTRB has formed or joined a Thread network.
> Remove 'leave' operation to avoid change existing WPAN status

- .travis/before_install.sh
- configure.ac
- src/agent/Makefile.am
- src/agent/border_agent.hpp
- src/agent/mdns.hpp
- src/agent/mdns_avahi.cpp
- src/agent/mdns_avahi.hpp
- src/common/code_utils.hpp
- src/common/time.hpp
- src/common/types.hpp
- tests/mdns/Makefile.am
- tests/mdns/main.cpp
- tests/mdns/test-multiple
- tests/mdns/test-single
- tests/mdns/test-stop
- tests/mdns/test-update
This PR implemented a `AvahiPoll` to integrate avahi client into `select()` based mainloop.
This is the first step to moving MDNS service from *otbr-web* into *otbr-agent*.
Functional tests are also added to make sure this service can support publishing multiple services, stop publishing as well as updating existing services.
Functional test of meshcop should be improved to use MDNS published service after it's fully moved into *otbr-agent*.
> Integrate MDNS service into mainloop.

- src/agent/dtls_mbedtls.cpp
- src/common/logging.cpp
- src/common/logging.hpp
This PR mainly tries to recover DTLS from server socket failure.
I encounter this issue once. This issue results in a lot of logs in syslog.
Other changes,
* Added a function to convert error into string.
> Fix issue that server socket fails.

- examples/platforms/fedora/default
- examples/platforms/ubuntu/default
- script/_initrc
- script/_nat64
- script/_otbr
- script/bootstrap
- script/console
This PR solves #79 by adding a flag mechanism to tune the behavior of scripts.
Every platform can provide default flag settings in `examples/platforms/$PLATFORM/default`. Flag settings can be override by environment variables. `PLATFORM` is by default detected based on output of `lsb_release`, but it can also be set by environment variable.
Currently supported flags
```
NAT64
RELEASE
```
> [script] add flags support.

- src/agent/agent_instance.cpp
- src/agent/coap_libcoap.cpp
- src/agent/dtls_mbedtls.cpp
- src/agent/dtls_mbedtls.hpp
- src/agent/mdns.hpp
- src/agent/mdns_avahi.cpp
- src/agent/mdns_avahi.hpp
- src/agent/ncp_wpantund.cpp
- src/common/code_utils.hpp
- src/common/time.hpp
- src/common/tlv.hpp
- src/common/types.hpp
- tests/mdns/main.cpp
- third_party/mbedtls/Makefile.am
This PR fixes,
* signed conversion warnings when enabled `-Wsign-conversion`, which is forced under some environment.
* `va_start` warning for now starting from promoted type argument.
* changed return type of `GetNow()` to `unsigned long`.
> [code] fix warnings.

- src/agent/border_agent.cpp
- src/agent/dtls_mbedtls.cpp
- src/common/logging.cpp
- src/common/logging.hpp
- src/utils/Makefile.am
- src/utils/crc16.cpp
- src/utils/crc16.hpp
- src/utils/steeringdata.cpp
- src/utils/steeringdata.hpp
- tests/meshcop/Makefile.am
- tests/meshcop/commissioner.cpp
- tests/meshcop/commissioner.hpp
- tests/meshcop/commissioner_argcargv.cpp
- tests/meshcop/commissioner_argcargv.hpp
- tests/meshcop/commissioner_compute.cpp
- tests/meshcop/commissioner_selftest.cpp
- tests/meshcop/commissioner_utils.cpp
- tests/meshcop/meshcop
- tests/unit/test_logging.cpp
Current test app: ${borderrouter}/tests/meshcop/commissioner.cpp - and the associated test script meshcop are very hard coded for a very specific test scenario.
This pull request:
* Removes hard coding of the test app
* Adds features to the test app to calculate for example the PSKc
* And can be used with any target device by adjusting various command line parameters.
General intent is that the commissioner test app can be used from a script to commission *actual* physical hardware via a script in a test farm scenario.
NOTE: A number of bugs/issues where found with the test scripts during this process, they are noted here: https://github.com/openthread/borderrouter/issues/94
> [tests] remove hardcoding for commissioner test app

- src/agent/ncp_wpantund.cpp
Compile OTBR with latest Raspbian Stretch Lite OS image, had one compile error as below:
Add a space between string literal and macro to fix this error.
> [agent] add a space between string literal and macro to meet c++11 standard.

- src/agent/border_agent.cpp
- src/agent/ncp.hpp
- src/agent/ncp_wpantund.cpp
- src/agent/ncp_wpantund.hpp
Not changed property values will not be sent if requested asynchronously. This PR changes NCP to request events synchronously so that we don't requiring wpantund start first for certain situations.
> [agent] request event synchronously.

- tests/meshcop/README.md
- tools/README.md
Adding READMEs to call out useful tools and redirect the user to openthread.io.
Wait until the Tools & Scripts page is live on openthread.io before merging.
> [docs] READMEs for tools

- script/_initrc
This pull request fixes problem with not working scripts on platforms different than BeagleBone Black. The root cause of problem was line: 98 in file `script/_initrc`, which check if there is a string "BeagleBone Black" in the path: `/sys/firmware/devicetree/base/model`. If there was this file present and doesn't contain string "BeagleBone Black" code ended because there was called command `set -e` (few lines above). Command `set -e` causes that script simply ends when gets return code different than 0. So for raspberry pi return code was always equal 1.
> Fix problem with not working scripts after merge Beagle Bone Black platform

- script/_dhcpv6_pd
- script/_network_manager
- script/setup
This pull request adds "ncp_state_notifier" to be able to react on NCP state changes. After add this change it possible to e.g. reload dhcpcd when NCP change it state to associated.
> Introduce ncp_state_notifier to improve Border Router extensibility.

- configure.ac
Checking if building computer has `pkg-config` before getting `libdbus` data leads to setting some environment variables to _build version_ of `pkg-config` instead of _target host version_ of `pkg-config`. It prevents `configure` from finding `libdbus`
> Modify configure.ac to allow cross-compilation

- src/agent/border_agent.cpp
This PR simply publish border agent service with service name the same as network name.
> Publish network name as service name

- script/_nat64
With old tayga config, the border router itself cannot ping nat64 ip
> [nat64] fix border router itself cannot use nat64

- .codecov.yml
- .travis.yml
- .travis/script.sh
- README.md
- configure.ac
- src/agent/main.cpp
- tests/mdns/main.cpp
- tests/meshcop/Makefile.am
* added SIGTERM handler to allow binaries exit elegantly so that `.gcda` files will be generated.
* enhanced the existing distcheck so that no specific check is needed to generate coverage data.
> [codecov] enable code coverage

- src/agent/border_agent.cpp
- src/agent/mdns_avahi.cpp
- src/agent/mdns_avahi.hpp
- src/agent/mdns_mdnssd.cpp
- src/agent/mdns_mdnssd.hpp
- tests/mdns/main.cpp
- tests/unit/Makefile.am
- tests/unit/test_mdns_mdnssd.cpp
From the codecov report, some methods supposed to be called were not called at all. This PR
* fixed this issue by adding service once the register call is successfully returned.
* added a `.` at the end of mdns service type, which will be added by mDNSResponder.
> [mdns] fix processing mdnssd

- third_party/wpantund/repo/src/util/string-utils.h
- third_party/wpantund/repo/src/wpantund/wpan-error.h
- third_party/wpantund/repo/third_party/openthread/src/ncp/spinel.h
The `sys/cdefs.h` is an internal header of `glibc` and is not meant to
be used by user code.  The macros needed from it can be trivially
implemented where required, relying on this header being present
excludes the OpenThread Border Router from being used on systems where
`glibc` is not the used C library (e.g. OpenWRT, where `uclibc` or
`musl` is standard).
https://wiki.musl-libc.org/faq.html#Q:-When-compiling-something-against-musl,-I-get-error-messages-about-%3Ccode%3Esys/cdefs.h%3C/code%3E
> [libc] do not use glibc-internal header sys/cdefs.h

- script/bootstrap
*ping6* from `iputils-ping` supports `-I` argument.
> [bootstrap] use iputils-ping instead of inetutils-ping

- configure.ac
- src/agent/Makefile.am
- src/web/Makefile.am
- third_party/wpantund/Makefile.am
fixes #207 . Unit files of systemd should be install in `/lib/systemd/system`, which could be get from `pkg-config`
> [systemd] fix unit file installation path

- src/agent/ncp_wpantund.cpp
Compiling under alpine:3.9 produces this error:
ncp_wpantund.cpp: In constructor 'ot::BorderRouter::Ncp::ControllerWpantund::ControllerWpantund(const char*)':
ncp_wpantund.cpp:219:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 16 equals destination size [-Werror=stringop-truncation]
strncpy(mInterfaceName, aInterfaceName, sizeof(mInterfaceName));
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:719: libotbr_agent_la-ncp_wpantund.lo] Error 1
make[2]: *** [Makefile:448: all-recursive] Error 1
make[1]: *** [Makefile:571: all-recursive] Error 1
make: *** [Makefile:497: all] Error 2
IFNAMSIZ is the size required including the NULL byte, so I think the
strncpy needs to be size-1. …
> [border-agent] ncp_wpatund.cpp: Fix off-by-one strncpy

- src/commissioner/main.cpp
A quick fix to #254 when user use Ctrl^C to quit the first commissioner. For longer term, I think it makes sense to add an option that the commissioner quit on joiner session ends.
> [commissioner] ensure close notify on close

- src/agent/border_agent.cpp
- src/agent/main.cpp
- src/agent/mdns_avahi.cpp
- src/agent/mdns_mdnssd.cpp
- src/agent/ncp_wpantund.cpp
- src/commissioner/main.cpp
- src/common/logging.cpp
- src/common/logging.hpp
- src/web/main.cpp
- tests/mdns/main.cpp
- tests/scripts/meshcop
- tests/unit/test_logging.cpp
This PR changes the default logging behavior to not logging to console
without `-v`.
> [logging] do not log to stderr by default

- configure.ac
This PR removes checking boost, so that if web is disabled, no need to have boost at all.
> [build] allow no boost

- .travis/check-android-build
- Android.mk
This PR fixes build otbr-agent.conf on Android system, also added this
into travis tests.
> [agent] fix build on Android

- src/web/otbr-web.init.in
- src/web/otbr-web.service.in
This PR unifies the environment name in `/etc/default/otbr-web` to be `OTBR_WEB_OPTS`.
> [web] unify start environment name

- script/bootstrap
Docker Hub clones repositories with `--recursive`, and since it is using
a old version of git. The git file is pointing to absolute path. After
copying into docker, the path is incorrect.
This PR allows git submodule failure in `script/bootstrap`.
> [docker] do not fail on submodule update failure

- .travis.yml
- Android.mk
- public/chromecast/mojom/mdns.mojom
- src/agent/border_agent.cpp
- src/agent/mdns_mojo.cpp
- src/agent/mdns_mojo.hpp
- tests/mdns/mdns_mojo_test/BUILD.gn
- tests/mdns/mdns_mojo_test/client.cpp
- tests/mdns/mdns_mojo_test/public/mojom/BUILD.gn
- tests/mdns/mdns_mojo_test/stub_mojo_service.cpp
- tests/mdns/test-mojo
- third_party/chromecast/mojom/mdns.mojom
On chromecast devices, the mdns is implemented by the chromecast application. This change calls the mojo RPC interface to publish services.
> [mDNS] mDNS implementation using mojo interface

- src/commissioner/commissioner.cpp
- src/commissioner/commissioner.hpp
- src/common/tlv.hpp
Add resign to allow other commissioners to petition in deconstruction.
Also made `CommissionerState` an `enum class` to prevent accidental misuse.
> [commissioner] add resign

- etc/docker/Dockerfile
_Update the descriptions for the new commit_
This PR optimizes the Dockerfile and uses one RUN cmd for operations that requires memory during build and operations that clear src and build dependencies to reduce the layers and docker image size.
With this PR, the image size could be reduced to 220M, compared to the existing docker which is 1.14G on dockerhub) 
> $ docker images
> REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
> otbr                          dockersize          f0e1845c38ad        12 minutes ago      220MB
> openthread/otbr_amd64_linux   latest              6fd18d60d957        13 days ago         1.14GB
> ubuntu                        latest              4c108a37151f        3 weeks ago         64.2MB
> [docker] reduce image size

- src/common/coap_libcoap.cpp
Lack of (unsigned char *) cast a pointer to structure pdu->hdr is
causing writes outside CoAP PDU buffer bounds.
> [coap] fix write outside buffer bounds

- .travis/check-raspbian
- script/_initrc
This PR removes dependency on `[[`, also fixed the broken travis test of **raspbian jessie**.
> [script] avoid bash extension

- src/agent/ncp_openthread.cpp
This PR fix the bug that the default return value of `ControllerOpenThread::RequestEvent` should be `OTBR_ERROR_NONE` rather than `OTBR_ERROR_ERRNO`.
> [ncp] fix the default return value of RequestEvent

- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/ncp.hpp
- src/agent/ncp_openthread.cpp
This PR includes the `Thread Version` is a DNS query response. According to the spec, `Thread Version` is **required**.
Currently supports only `ncp=openthread`.
Dependent PR: [4225](https://github.com/openthread/openthread/pull/4225).
This PR updated submodule openthread to include the dependent PR.
> [mdns] include thread version in query response

- .travis.yml
- src/agent/mdns_mojo.cpp
- src/agent/mdns_mojo.hpp
- tests/mdns/mdns_mojo_test/stub_mojo_service.cpp
- third_party/chromecast/mojom/mdns.mojom
The connect and receive api has been recently updated in chrominum.
Update accordingly.
The code divergence in libchrome and chromium forcing us to use different types and function names when linking to these libraries. I'm working with the chromium team to resolve this issue.
> [mojo] update mojo connect and receive api call

- Android.mk
- configure.ac
- include/Makefile.am
- include/openthread-br/config.h
- src/agent/Makefile.am
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/commissioner/Makefile.am
- src/common/Makefile.am
- src/dbus/Makefile.am
- src/utils/Makefile.am
- src/web/Makefile.am
- src/web/main.cpp
- src/web/web-service/wpan_service.hpp
- tests/dbus/Makefile.am
- tests/mdns/Makefile.am
- tests/unit/Makefile.am
- tools/Makefile.am
Check if there is autoconf header file inside openthread-br/config.h to
make code clean.
> [build] use openthread-br/config.h 

- src/agent/mdns_avahi.cpp
member method [CreateGroup](https://github.com/openthread/ot-br-posix/blob/affbbdb34b2c6743b1e83a1fd5ef50cf6e93d6ac/src/agent/mdns_avahi.cpp#L420) has no guarantee of success.
> [avahi] check if mGroup is nil before commit

- .travis/check-android-build
- Android.mk
- etc/libchrome_stub/generate_mojom_sources.mk
Generated mojo files should be in static libraries to ensure
the module is completely built before compilation of another module.
> [android] fix deterministic -j1 build failure.

- script/_disable_services
The BeagleBone Debian distribution has changed from Jessie to Strecth.
One of the changes in that migration was moving the server for the
Cloud9 IDE to nginx from apache.
One of the scripts called by the setup disables running webservers to
allow the OpenThread Border Router to run it's own server. This updates
the disable script to point to the current webserver on the BeagleBone.
> [beaglebone] disable nginx and apache

- Android.mk
- src/dbus/client/Makefile.am
- src/dbus/client/client_error.cpp
- src/dbus/client/client_error.hpp
- src/dbus/client/thread_api_dbus.cpp
- src/dbus/common/Makefile.am
- src/dbus/server/Makefile.am
- src/dbus/server/dbus_request.hpp
- src/dbus/server/error_helper.cpp
- src/dbus/server/error_helper.hpp
This removes users' dependency on OpenThread headers when compiling the
otbr-dbus-client library.
> [dbus] separate client/server error helpers

- src/dbus/server/dbus_thread_object.cpp
This change fixes the behavior of factory reset. It will wipe the persistent
network data now.
> [dbus] wipe persistent data on factory reset

- src/agent/thread_helper.cpp
This is the behavior of the current client code. Update implementation
to be compatible.
> [dbus] close unsecure port when timeout is zero

- tests/dbus/test_dbus_client.cpp
The rloc16 value can be zero, use 0xffff for an invalid value instead.
> [test] fix dbus client checks

- src/web/main.cpp
As explained in #450, an option require error appears when we check version number of otbr-web.
The typo is fixed and now `-v` option could correctly print version information.
> [web] fix option require error in otbr-web

- script/test
This commit changes the build type in `script/test` to Debug which is helpful when debugging is needed.
> [script] set build type to Debug by default

- script/_otbr
Sometimes OTBR failed to build with ninja:
```
-- Build files have been written to: /home/pi/ot-br-posix/build/otbr
+ ninja
ninja: error: opening build log: Permission denied
```
This PR makes sure ninja has permission to access the log files (i.e. .ninja_log and .ninja_deps)
> [scripts] fix ninja build log permissions

- script/_dns64
- script/_network_manager
This fixes setup script by 2 modifications:
- Changes network manager `ipv6.method` to `auto` to make WiFi AP work.
- Stops and disables `dnsmasq` before starting `bind9` to fix the "port 53 in use" issue.
> [setup] fix network manager and DNS setup

- script/_otbr
This PR allows developers to specify extra cmake options for `script/setup` using env `OTBR_OPTIONS`.
> [setup] allow specify cmake options via OS env

- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/dbus_thread_object.hpp
This change allows the dbus agent to send device role changed signals under unexpected external resets. (e.g. ot-ctl factoryreset and internal OpenThread resets)
> [dbus] fix handler registration under external reset

- src/web/web-service/web_server.cpp
This PR fixes a reflected XSS vulnerability of `otbr-web`. The exception message may contain user inputs so needs to escape sensitive characters.
Reproducing:
1.  Start `otbr-web` service on `localhost`.
1.  Run:
```bash
curl 'localhost/no_such_file.pl?"><script>alert(111);</script>'
```
Then the response will contain executable scripts.
> [web] fix reflected XSS

- CMakeLists.txt
- src/dbus/common/CMakeLists.txt
- src/web/CMakeLists.txt
- tests/unit/CMakeLists.txt
To support automated armv7 docker builds.
> [cmake] move minimum version to 3.10.2

- .travis/script.sh
unlink python2 before brew install, which fails for unable to link python as python3.
> [travis-ci] fix install python

- Android.mk
- src/agent/ncp_openthread.cpp
- src/dbus/server/dbus_thread_object.cpp
Correctly intialize/start/stop prefix handling in ncp logic.
> [ncp] fix legacy prefix handling

- .travis/check-docker
- src/web/web-service/frontend/index.html
- src/web/web-service/frontend/join.dialog.html
- src/web/web-service/frontend/res/js/app.js
- src/web/web-service/wpan_service.cpp
- tests/scripts/meshcop
As discussed in #545 , this PR changes all `NetworkKey` to `MasterKey` in Web module, so the naming of this terminology is consistent with the Thread Specification.
> [web] unify MasterKey and NetworkKey

- .github/workflows/build.yml
- src/dbus/common/error.hpp
- src/dbus/common/types.hpp
- src/openwrt/ubus/otubus.cpp
- src/openwrt/view/admin_thread/thread_setting.htm
- tests/scripts/check-android-build
To promote inclusivity and eliminate any unintentional bias.
> [mac-filter] change whitelist/blacklist to allowlist/denylist

- .github/workflows/docker.yml
- etc/docker/Dockerfile
This PR adds a new argument `OT_BACKBONE_CI` to the Dockerfile.
[OpenThread 1.2 Backbone CI](https://github.com/openthread/openthread/pull/5489) can use `OT_BACKBONE_CI=1` to build the Docker image for testing purpose:
- Install additional packages: `curl, ca-certificates`
- Does not remove source and build files in `/app` directory
- Does not remove unused packages and APT cache files
> [dockerfile] add ARG `OT_BACKBONE_CI`

- CMakeLists.txt
- etc/docker/docker_entrypoint.sh
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
This PR adds the `-B <backbone-ifname>`  argument to `otbr-agent`. 
If this argument is not given, the backbone is not initialized.
> [flags] configure backbone network interface name

- tests/dbus/test-client
We found failed cases where the Thread network has not been formed yet.
Increase the timeout to make it more stable.
> [test] increase the waiting time in dbus tests

- .github/workflows/build.yml
This PR adds the OpenThread 1.2 Backbone CI (same test of https://github.com/openthread/openthread/pull/5489) to OTBR .
> [github-actions] add OT1.2 Backbone CI

- etc/docker/Dockerfile
This allows initializing the submodules inside docker.
Fixes https://github.com/openthread/ot-br-posix/issues/570
> [docker] add ca-certificates to DEPS

- tests/dbus/test-client
- tests/scripts/bootstrap.sh
Chances are that the ot-cli-ftd node keeps receiving annoouncements
from the ot-cli-mtd node and cannot become a leader. Modify the launch
order to resolve this issue.
Fixes https://github.com/openthread/ot-br-posix/issues/569
> [test] fix Thread node launch order

- tests/scripts/bootstrap.sh
Resolves the following warning:
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
> [bootstrap] update brew install command

- examples/platforms/beagleboneblack/default
- script/_dhcpv6_pd
- script/_dns64
- script/_initrc
- script/_nat64
- script/_network_manager
This allows building for BeagleBone in the same fashion as RasPi.
BeagleBone uses connaman by default for network management. The [BeagleBone Black build guide](https://openthread.io/guides/border-router/beaglebone-black) should be updated to explain how to replace connman with Network Manager.
> [platform] verify Network Manager with BeagleBone

- .github/workflows/build.yml
- script/test
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/types.hpp
As discussed in #587 ,  we avoid using `std::hash` in OTBR-REST. 
Build check did not disclose this issue because OTBR-REST is not set as default enabled in test,  we also fix this in this PR.
> [web] fix OTBR-REST build fail in GCC 4.8.3

- etc/docker/Dockerfile
- script/bootstrap
This PR further compacts Docker image size by removing packages for building but not useful in runtime. 
This PR reduces the otbr docker image size from 572MB to 452MB.
> [docker] compact docker image size

- src/dbus/server/dbus_agent.cpp
`dbusError` is freed before used in logging. This caused wrong logging message.
> [dbus] fix using `dbusError` after free

- etc/docker/Dockerfile
This adds `lcov` as a backbone CI dependency. Needed by https://github.com/openthread/openthread/pull/5635.
> [docker] add backbone CI dependency

- src/web/web-service/wpan_service.cpp
- src/web/web-service/wpan_service.hpp
This PR:
- Use `dataset` for forming network.  
- Escape whitespaces in networkname
Fixes #578.
> [web-service] escape networkname

- src/backbone_router/backbone_agent.cpp
- src/common/types.cpp
- src/common/types.hpp
This removes the dependency of `openthread/ip6.h` from `common/types.hpp`.
> [common] remove client dependency of OpenThread header

- Android.mk
- src/agent/main.cpp
- src/agent/ncp_openthread.hpp
- src/agent/thread_helper.cpp
- src/common/CMakeLists.txt
- src/common/region_code.cpp
- src/common/region_code.hpp
- src/dbus/client/thread_api_dbus.cpp
- src/dbus/client/thread_api_dbus.hpp
- src/dbus/common/constants.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/dbus_thread_object.hpp
- src/dbus/server/introspect.xml
- tests/dbus/test-client
- tests/dbus/test_dbus_client.cpp
The PR adds region support which will determine the preferred channels
and the allowed channels when forming or joining a Thread network.
- Add region and channel mask logic.
- Add region to command line arguments.
- Add d-bus get and set api.
> [agent] add region support

- src/openwrt/view/admin_thread/thread_setting.htm
On OpenWrt 19.07,Modify the order to avoid call "connect_ubus" and "threadget" failed.
before:
fix:
> [openwrt] fix otbr attempt to call global 'threadget' (a nil value)

- etc/docker/Dockerfile
- script/bootstrap
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/ncp.hpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/backbone_router/CMakeLists.txt
- src/backbone_router/backbone_agent.cpp
- src/backbone_router/constants.hpp
- src/backbone_router/nd_proxy.cpp
- src/backbone_router/nd_proxy.hpp
- src/common/code_utils.hpp
- src/common/logging.cpp
- src/common/types.cpp
- src/common/types.hpp
- tools/CMakeLists.txt
This commit implements the ND Proxy on OTBR for Thread 1.2 DUA feature:
**Tested by https://github.com/openthread/openthread/pull/5595 (merged)**
> [backbone-router] implement Backbone ND proxy

- src/openwrt/otbr-agent.init.in
- src/openwrt/view/admin_thread/thread_setting.htm
The statement script needs to be on the first line, otherwise executing "/etc/init.d/otbr-agent start" has no effect.
> [openwrt] fix startup script no effect

- src/common/code_utils.hpp
This removes the dependency of `openthread/platform/toolchain.h` from `common/code_utils.hpp`, for the same reason as <https://github.com/openthread/ot-br-posix/pull/601>.
> [code-utils] remove client dependency of toolchain.h

- script/_network_manager
This commit disables DNS of dnsmasq when DNS64 is enabled, because
bind9 provides DNS service already.
This commit also moves packages installation out from `script/bootstrap` into service setup script.
> [script] disable DNS of dnsmasq when DNS64 is on

- src/agent/ncp_openthread.cpp
https://github.com/openthread/openthread/pull/5466 allows ot-ctl to reconnect to otbr-agent or ot-daemon seamlessly. 
However, otbr-agent didn't set `gPlatResetReason` correctly thus this feature is not working for otbr-agent. 
This commit fix this issue.
> [plat] set gPlatResetReason for software reset

- third_party/openthread/mbedtls-config.h
The Mbedtls ECDSA implementation is required by SRP client&server to sign message and verify signature.
See also openthread changes https://github.com/openthread/openthread/blob/677e2f01ecd71733cc82597bab22a6312120845d/third_party/mbedtls/mbedtls-config.h#L103-L111
```c++
#if OPENTHREAD_CONFIG_ECDSA_ENABLE
#define MBEDTLS_BASE64_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_OID_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PK_WRITE_C
#endif
```
> [mbedtls] enable ECDSA support

- src/agent/thread_helper.cpp
- src/agent/thread_helper.hpp
- src/dbus/client/thread_api_dbus.cpp
- src/dbus/client/thread_api_dbus.hpp
- src/dbus/common/constants.hpp
- src/dbus/common/dbus_message_helper.cpp
- src/dbus/common/dbus_message_helper.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/dbus_thread_object.hpp
- src/dbus/server/introspect.xml
- tests/dbus/test_dbus_client.cpp
This change allows users to get and set the active dataset via the dbus
api. It also adds an `Attach` interface to allow users to start the
Thread network without specifying network parameters.
> [dbus] add active dataset api

- .github/workflows/build.yml
Fixes #653
Seems codecov does not work on ubuntu-20.04 here. The actual cause is not found yet. 
Revert one job to use `ubuntu-18.04` to fix codecov issue.
> [codecov] fix codecov drop

- .gitignore
- src/agent/border_agent.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/CMakeLists.txt
- tests/mdns/main.cpp
- tests/mdns/test-multiple-custom-hosts
- tests/mdns/test-single-custom-host
- tests/mdns/test_init
This PR adds the ability to publish a service with custom host name & address.
For a Duckhorn BR, we need to help advertise a service registered by a Thread device. the Service resides on the end device and has specific host name & address. To support it, this PR adds below changes:
1. add an additional `aHostName` param to the `PublishService` API to allow specifying a custom host name;
2. add API `UnpublishService` to un-publish a service when the Thread device de-registers it from the BR. We cannot simply stop the Publisher because there may be many services from different Thread end devices.
3. add API `PublishHost` to publish a host name & address pair. The service cannot be resolved if the host it points to doesn't have a valid address RR.
4. add API `UnpublishHost` to un-publish …
> [mdns] add mDNS API to publish & un-publish custom host

- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/main.cpp
In cases the TXT record can not be determined at compile time (For services from Thread end devices, arbitrary TXT records may be provided at runntime), we need to support specifying a list of TXT name/value entries.
> [mdns] accept a list of TXT entries

- src/dbus/server/dbus_agent.cpp
- src/dbus/server/dbus_agent.hpp
Some disabled watch will not be toggled causing writable file descriptor
to be triggered infinitely. The toggle feature is optional in d-bus.
This patch fixes this bug.
> [dbus] add watch enable check

- script/bootstrap
This commit installs the dnsutils package for reference device. 
The dnsutils package includes tools like `dig`, which can be used to test DNS servers on BR.
> [bootstrap] install dnsutils for reference device

- .github/workflows/documentation.yml
OTBR_DBUS is required for generating the dbus server docs.
> [doc] fix doc build cmake flags

- Android.mk
This allow users to override the dbus user and group with non-root
configuration.
> [build] make dbus user and group configurable in Android.mk

- Android.mk
- src/dbus/server/CMakeLists.txt
This makes the build more deterministic and prevents incremental build
issues.
> [build] eliminate generated files from the source directory

- src/dbus/client/client_error.cpp
- src/dbus/client/thread_api_dbus.cpp
- tests/dbus/test-client
- tests/dbus/test_dbus_client.cpp
- tests/rest/test-rest-server
The reply dbus message will not contain error code when error happens.
Currently all the error codes will be OTBR_ERROR_DBUS.
This CL checks separate DBusError to correctly handle the error codes
and adds corresponding tests.
> [dbus] fix wrong error code when error happens

- src/dbus/client/thread_api_dbus.cpp
The removed line 356 in PR#688 is an accidental remove.
> [dbus] fix accidental line removal

- src/agent/advertising_proxy.cpp
- src/common/types.cpp
- src/common/types.hpp
This removes the dependency of openthread/error.h from common/types.hpp.
> [types] remove dependency of OpenThread header

- src/common/CMakeLists.txt
- src/common/code_utils.hpp
- src/common/task_runner.cpp
- src/common/task_runner.hpp
- tests/unit/CMakeLists.txt
- tests/unit/test_task_runner.cpp
This PR adds a `TaskRunner` module that executes tasks on the mainloop.
The `TaskRunner` is useful to dispatch a callback back to the mainloop.
(e.g. handle mDNS callbacks which may be invoked from another thread).
We are not using [eventfd](https://man7.org/linux/man-pages/man2/eventfd.2.html) because it is linux-specific.
> [common] add Task Runner

- src/dbus/client/CMakeLists.txt
- src/dbus/client/thread_api_dbus.hpp
This file uses `OTBR_UNUSED_VARIABLE` which is in `common/code_utils.hpp`.
> [dbus] add missing header inclusion

- src/openwrt/ubus/otubus.cpp
- src/rest/resource.cpp
This PR sets the `DIAG_GET` response callback every time the `otThreadSendDiagnosticGet` is called. This is because the callback may be changed to other modules (e,g. `OTBR_REST`, `OT_CLI`).
addresses issue: #689 
Related PR in openthread: https://github.com/openthread/openthread/pull/6192
> [netdiag] fix network diagnostic get response callback

- src/dbus/client/thread_api_dbus.hpp
`common/code_utils.hpp` includes macros like `VerifiOrDie` which are not protected by C++ namespace, so it will easily get conflicted with other definitions.
We should not include `common/code_utils.hpp` in public headers.
Blocking: https://github.com/project-chip/connectedhomeip/pull/5062
> [dbus] remove inclusion of code_utils.hpp in dbus api header

- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/rest/rest_web_server.cpp
- src/rest/rest_web_server.hpp
- src/utils/CMakeLists.txt
- src/utils/socket_utils.cpp
- src/utils/socket_utils.hpp
- tests/dbus/test-client
- tests/dbus/test_dbus_client.cpp
Premature reset has causing a number of bugs.
This commit fix the bugs and avoid potential future bugs by resetting otbr-agent using `execvp`, which will bootstrap the whole process completely.
> [agent] full reset using execvp

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- tests/mdns/test-multiple-custom-hosts
- tests/mdns/test-single-custom-host
Currently, only mDNSResponder can be used to test the OpenThread SRP server. Provide the functionality necessary to test registration of new services using Avahi daemon.
Avahi forbids modifying entry groups which have already been committed. As a result, in order to support methods for publishing and removing a single host/service, each host and each service is processed as a separate Avahi entry group.
> [dns-sd] implement missing Avahi bindings

- CMakeLists.txt
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/backbone_router/backbone_agent.cpp
- src/backbone_router/backbone_agent.hpp
- src/backbone_router/nd_proxy.cpp
- src/backbone_router/nd_proxy.hpp
- third_party/openthread/CMakeLists.txt
This commit adds the `OTBR_DUA_ROUTING` option, which configures whether the DUA routing related features (e.g. DUA ND Proxying) are enabled for the Backbone Router.
The `OTBR_DUA_ROUTING` option is `OFF` by default. The option also configures OT option `OT_BACKBONE_ROUTER_DUA_NDPROXYING` correspondingly.
Required by #712 and #586
> [backbone-router] add OTBR_DUA_ROUTING option (OFF by default)

- src/agent/agent_instance.cpp
- src/agent/agent_instance.hpp
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/main.cpp
- src/agent/ncp.hpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/backbone_router/backbone_agent.cpp
- src/backbone_router/backbone_agent.hpp
- src/backbone_router/nd_proxy.cpp
- src/backbone_router/nd_proxy.hpp
- src/common/CMakeLists.txt
- src/common/mainloop.hpp
- src/common/task_runner.cpp
- src/common/task_runner.hpp
- src/dbus/server/dbus_agent.cpp
- src/dbus/server/dbus_agent.hpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- src/rest/connection.cpp
- src/rest/connection.hpp
- src/rest/rest_web_server.cpp
- src/rest/rest_web_server.hpp
- tests/mdns/main.cpp
- tests/unit/test_task_runner.cpp
This PR unifies that mainloop interface to always use the `MainloopContext` structure rather than fd sets. We also define a `MainloopProcessor` interface to ensure that each module defines exactly the same mainloop processing methods.
> [utils] unify mainloop interface

- CMakeLists.txt
- src/backbone_router/backbone_agent.cpp
- third_party/openthread/CMakeLists.txt
This commit introduces several `Backbone Router` configuration changes:
- Enable `Backbone Router` service by default. (Users can still turn off `Backbone Router` using `ot-ctl bbr disable`.)
- Disalbe `DUA TMF PROXY` when `DUA ROUTING` is disabled.
- Set `OT_MLR=ON` for `BACKBONE_ROUTER` setup option
> [bbr] update Backbone Router configurations

- tests/scripts/check-raspbian
This commit fixes #728 by replacing default cmake distribution with cmake-3.10.3.
For the root cause of the failure, see https://gitlab.kitware.com/cmake/cmake/-/issues/20568..
> [tests] pin cmake to version 3.10.3

- src/agent/advertising_proxy.cpp
- src/agent/advertising_proxy.hpp
This commit includes two small updates/fixes:
1. fix counting service update callback numbers;
2. rename `mCount` of `OutstandingUpdate` to `mCallbackCount` which is more informative.
> [advertising-proxy] fix unpublish a host

- src/agent/border_agent.cpp
- src/agent/main.cpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
example output:
```
☁  ot-br-posix [print-thread-version] ⚡  sudo otbr-agent -I wpan0 -B eno1 -d 7 -v 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
otbr-agent[765464]: Running 0.3.0-cf3a67383-dirty
otbr-agent[765464]: Thread version: 1.2.0
otbr-agent[765464]: Thread interface: wpan0
otbr-agent[765464]: Backbone interface: eno1
```
> [agent] print thread version at start

- src/web/web-service/wpan_service.cpp
This PR introduces two changes:
- Set default prefix length to 64 if not given (similar to form and join operation)
- Call `netdata register` to remove/add prefix immediatlelly
> [web] improve add/delete prefix functionality

- script/_rt_tables
- src/backbone_router/CMakeLists.txt
- src/backbone_router/backbone_agent.cpp
- src/backbone_router/backbone_agent.hpp
- src/backbone_router/dua_routing_manager.cpp
- src/backbone_router/dua_routing_manager.hpp
This PR manages Backbone routes for Domain Prefix on PBBR.
- Tested by https://github.com/openthread/openthread/pull/5644
```bash
$ ip -6 route add fd00:7d03:7d03:7d03::/64 dev wpan0 proto static metric 1
```
```bash
$ ip -6 rule add iif wpan0 table openthread
$ ip -6 route add fd00:7d03:7d03:7d03::/64 dev eth0 proto static table openthread
```
> [backbone-router] implement DUA policy routing

- Android.mk
- etc/cmake/options.cmake
- src/agent/CMakeLists.txt
- src/agent/advertising_proxy.cpp
- src/agent/border_agent.cpp
- src/agent/border_agent.hpp
- src/agent/discovery_proxy.cpp
- src/agent/discovery_proxy.hpp
- src/common/CMakeLists.txt
- src/common/code_utils.hpp
- src/common/dns_utils.cpp
- src/common/dns_utils.hpp
- src/common/types.cpp
- src/common/types.hpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- third_party/openthread/CMakeLists.txt
This commit implements DNS-SD Discovery Proxy ([RFC 8766](https://tools.ietf.org/html/rfc8766)) over mDNSResponder.
> [dnssd] implement DNS-SD Discovery Proxy

- tests/scripts/check-scripts
Addresses some of the failures in `check-scripts`.
Fixes #786.
> [tests] wait longer for services to be ready

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
`TxtList` is a list of DNS TXT records to publish, represented as memory ranges for keys and values of the records.
While memory ranges for the values point directly to a `otSrpServerService` object's member whose lifetime is longer
than lifetime of the `TxtList`, memory ranges for the keys pointed to a member of `otDnsTxtEntryIterator` structure,
allocated on stack during the translation.
It resulted in publishing garbage TXT records.
Fix the issue by using `std::string` to store the keys instead of raw pointers/lengths.
Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>
> [mdns] fix pointer to object on stack in TxtList

- src/agent/discovery_proxy.cpp
- src/agent/discovery_proxy.hpp
- src/common/dns_utils.cpp
- src/common/dns_utils.hpp
- tests/unit/CMakeLists.txt
- tests/unit/test_dns_utils.cpp
This commit adds a new method `SplitFullDnsName` which handles instance names with dots correctly.
> [dns] handle instance names with dots

- .github/workflows/border_router.yml
- src/agent/main.cpp
- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/agent/otbr-agent.default.in
- third_party/openthread/CMakeLists.txt
This commit enables TREL by default.
**TREL is enabled by default using the Backbone interface**
> [trel] enable TREL by default

- src/agent/ncp_openthread.cpp
- src/agent/ncp_openthread.hpp
- src/dbus/server/dbus_thread_object.cpp
- tests/dbus/test_dbus_client.cpp
Full reset is intended to be used only for testing purposes. This changes the behaviors of DBus APIs back.
> [dbus] use pseudo reset in DBus APIs

- script/_otbr
- tools/testharness_discovery/CMakeLists.txt
- tools/testharness_discovery/testharness-discovery
- tools/testharness_discovery/testharness-discovery.init.in
- tools/testharness_discovery/testharness-discovery.service.in
This commit implements the TestHarness BBR Discovery protocol so that TestHarness can discover OTBRs connected to the same Backbone link, without UART connections. 
Verified that it works:
```
pi@raspberrypi:~/ot-br-posix $ service testharness-discovery status
● testharness-discovery.service - TestHarness Discovery Service
Loaded: loaded (/lib/systemd/system/testharness-discovery.service; disabled; vendor preset: enabled)
Active: inactive (dead)
pi@raspberrypi:~/ot-br-posix $ sudo service testharness-discovery start
pi@raspberrypi:~/ot-br-posix $ sudo service testharness-discovery status
● testharness-discovery.service - TestHarness Discovery Service
Loaded: loaded (/lib/systemd/system/testharness-discovery.service; disabled; vendor preset: enabled)
Active: active (running) since Tue …
```
> [certification] support TestHarness BBR discovery

- src/agent/discovery_proxy.cpp
> [dnssd] fix printing string after its destruction

- src/agent/discovery_proxy.cpp
- src/agent/discovery_proxy.hpp
The newly introduces `otDnssdGetQuery` apis allows platform
implementations to use the queries stored in the dns-sd server. Remove
the local map to reduce complexity.
Depends-On: https://github.com/openthread/openthread/pull/6611
> [dnssd] use queries in dns-sd server rather than local map

- .github/workflows/build.yml
- Android.mk
- tests/scripts/check-android-build
Currently in the github action for checking android build, the env
`OTBR_MDNS` doesn't take effect because the script is actually run in
a docker image. Thus when building it, `libmdnsd` and `PublisherMDnsSd`
are not compiled. This PR adds `OTBR_MDNS` env variable to the docker
and FLAGS, INCLUDES for using mDNSResponder in ot-br-posix.
> [android] fix android build check for mDNSResponder

- src/mdns/mdns_avahi.hpp
I met following error while running the `tests/scripts/thread-cert/border_router/test_dnssd_server.py` test using avahi as the mDNS daemon.
```
708 May 23 09:46:20 fb1254174230 otbr-agent[111]: [INFO]-MDNS----: Avahi client ready.
709 May 23 09:46:20 fb1254174230 otbr-agent[111]: [INFO]-AGENT---: Publish meshcop service OpenThread._meshcop._udp.local.
710 May 23 09:46:20 fb1254174230 otbr-agent[111]: [ERR ]-MDNS----: Failed to publish service: Message too long!
``` 
Apparently it happened because the avahi TXT record buffer was not big enough. Therefore I increased the buffer size and the error disappeared.
> [dns-sd] enlarge kMaxSizeOfTxtRecord for avahi

- src/agent/discovery_proxy.cpp
This commit fixes potential Discovery Proxy crash when the mDNS implementation replied with an empty host name.
> [dns] fix potential Discovery Proxy crash

- src/mdns/mdns_avahi.cpp
Current mDNS-avahi implementation publishes the SRP client IPv6 addresses
in only IPv6 space. This results in the host being not discoverable with IPv4 queries
on infra link. This commit fixes this issue by advertising the AAAA record in both
IPv4 and IPv6 spaces.
> [mdns] avahi publish an address/host with both IPv4 and IPv6

- third_party/openthread/mbedtls-config.h
Turn on mbedtls PSK support for CoAP testing on reference OTBR (similar to ECDSA)
> [cmake] include CoAPS PSK support for OTBR

- CMakeLists.txt
- etc/openwrt/openthread-br/Makefile
This commit fixes the OpenWrt check which is caused by its recent change
that makes ninja as the default build tool. Besides, this commit also
fixes generating version by eliminating redirect the stderr.
fixes #894
> [test] fix OpenWrt check

- src/agent/advertising_proxy.cpp
- src/agent/advertising_proxy.hpp
- src/agent/border_agent.cpp
- src/mdns/mdns.hpp
When mDNS daemon restarts, our mDNS library may need to re-advertise all hosts and services. Thus I extracted this functionality and made it a public method. 
Also, on `kReady`, SRP server will publish all registered hosts and services. This is helpful when the advertising proxy reconnects to the mDNS provider.
> [adproxy] re-register all services when the mDNS publisher becomes ready

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
Currently I don't see an easy way to get TTL information via avahi API. This PR is a workaround to set TTL as 10 all the time to avoid zero TTLs.
> [dnssd] set TTL as 10 for entries discovered by avahi

- src/agent/advertising_proxy.cpp
- src/agent/advertising_proxy.hpp
- src/agent/border_agent.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/main.cpp
- tests/mdns/test-service-subtypes
- tests/mdns/test_init
After recent changes in the SRP client & server, SRP services
can now have a base DNS type (such as _meshcop._udp) or
a subtype such as _subtype1._sub._meshcop._udp.
* Make advertising-proxy group the services by the base type
and pass a list of the subtype labels to the DNS publisher.
* Update both the mDNSResponder and Avahi implementations
so that it is possible publish a services with additional
subtypes and to update the subtypes.
* Add unit tests.
> [dns-sd] support service subtypes in advertising proxy

- .github/workflows/docker.yml
- etc/docker/Dockerfile
- script/bootstrap
Fixes https://github.com/project-chip/connectedhomeip/issues/8235
Installing `libjsoncpp-dev` on Ubuntu since it will automatically install the correct `libjsoncpp<Version>` package.
**Ubuntu 21.04:**
```
The following NEW packages will be installed:
libjsoncpp-dev libjsoncpp24
```
**Ubuntu 18.04:**
```
The following NEW packages will be installed:
libjsoncpp-dev libjsoncpp1
```
> [setup] fix libjsoncpp1 not found on Ubuntu 21.04

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
Previously we didn't implement the strategy for resolving service name conflicts while using avahi mdns. Therefore, when there is a service name conflict, the registration will fail silently. Especially, this issue affects the situation when their are two border routers on the same infra link, where there will only have one meshcop service successfully registered.
Have tested locally, will add the test case once https://github.com/openthread/openthread/pull/6865 is checked in.
This PR should fix issue: https://github.com/openthread/ot-br-posix/issues/826
> [mdns] resolve service name conflicts when using avahi

- .github/workflows/border_router.yml
This commit fixes border router CI failures caused by https://github.com/openthread/openthread/pull/6838 changes.
> [github-actions] fix border router CI failures

- CMakeLists.txt
- src/agent/border_agent.cpp
- src/common/types.hpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.hpp
Per [RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762), the name should be "mDNS".
> [mdns] rename "MDNS" to "mDNS"

- tests/scripts/meshcop
This commit fixes parsing border agent port when there is a newline
charater in the text record by parsing the non-parsable output format
of avahi-browse.
> [test] fix parsing border agent port

- src/mdns/mdns_mdnssd.cpp
Without this change clang may complain `aServiceRef` is unused in some situations.
> [mdns] fix unused variable of aServiceRef

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
This commit fixes the bug that mDNS using Avahi only browses or resolves services using IPv6 sockets. 
Note that `avahi-daemon` may be configured to not use IPv6 socket:
```
use-ipv6=  Takes a boolean value ("yes" or "no"). If set to "no" avahi-daemon will not use
IPv6 sockets. Default is "yes".
```
> [mdns-avahi] browse or resolve using unspecified protocol

- src/web/web-service/ot_client.cpp
RCP with USB transport needs more time for reinitialization after hard resetting due to reattaching the USB device to host OS.
Depends on:
> [web] extend web client timeout

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
Previously in mDNSResponder implementation, otbr-agent won't update the service port when `PublishService` is called.
> [mdns] update the service port in mDNSResponder implementation

- .github/workflows/macOS.yml
This PR aims to fix https://github.com/openthread/ot-br-posix/issues/1002.
When brew install ninja, python 3.9 is being installed as a dependency. However, the installation failed because there is a conflict on binary /usr/local/bin/2to3.
> [github-actions] fix brew install issue on macOS

- src/agent/border_agent.cpp
- src/dbus/server/dbus_thread_object.cpp
- src/openwrt/ubus/otubus.cpp
This PR aims to update the usage of `otThreadGetNetworkKey` and `otThreadGetPskc` based on the updates proposed in openthread/openthread#6862. This should be merged at the same time with openthread/openthread#6862.
Depends-On: openthread/openthread#6862
> [crypto] Update otThreadGetNetworkKey and otThreadGetPskc usage

- examples/platforms/nxp/linux-imx/aarch64.cmake
Added the arm64 toolchain file for cmake. This enabled the cross compile based on NXP
i.MX8M Linux SDK.
TEST:  source ${PATH_TO_NXP_LINUX_SDK}/environment-setup-cortexa53-crypto-poky-linux
./script/cmake-build -DOTBR_BORDER_ROUTING=ON -DOTBR_WEB=ON \
-DBUILD_TESTING=OFF -DOTBR_DBUS=ON -DOTBR_DNSSD_DISCOVERY_PROXY=ON \
-DOTBR_SRP_ADVERTISING_PROXY=ON -DOT_THREAD_VERSION=1.2 \
-DOTBR_INFRA_IF_NAME=mlan0 \
-DCMAKE_TOOLCHAIN_FILE=./examples/platforms/nxp/linux-imx/aarch64.cmake
> [platform] add arm64 toolchain file for cmake

- src/agent/ncp_openthread.cpp
- src/common/logging.cpp
- src/common/logging.hpp
OTBR is providing custom `otPlatLog` function which overwrites the default posix logging function. The problem is that the OTBR `otPlatLog` function will filter out logs based on current OTBR log level, this will result in the situation that we cannot print more OT logs with command `ot-ctl log level <level-value>` (when dynamic logging is enabled).
> [logging] fix OpenThread dynamic logging

- src/dbus/server/dbus_thread_object.cpp
dbus client's call to 'GetAll' properties fails
with following error, if OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE is not enabled.
Error log:-
[INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.GetAll
[ERR ]-UTILS---: Replied to org.freedesktop.DBus.Properties.GetAll with result io.openthread.Error.NotImplemented
This patch fixes above issue, by applying conditional
registration of following properties:
- OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_SAMPLE_COUNT
- OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_ALL_CHANNEL_QUALITIES
Signed-off-by: Anupam Roy <anupam.r@samsung.com>
> [dbus] fix failure to  get 'All' OpenThread properties

- tests/scripts/check-android-build
To address the following issue:
```
get -nv https://dbus.freedesktop.org/releases/dbus/dbus-1.4.26.tar.gz
ERROR: cannot verify dbus.freedesktop.org's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
Issued certificate has expired.
To connect to dbus.freedesktop.org insecurely, use `--no-check-certificate'.
Error: Process completed with exit code 5.
```
> [tests] use `--no-check-certificates` when invoking `wget`

- src/agent/advertising_proxy.cpp
- src/agent/advertising_proxy.hpp
- src/agent/border_agent.cpp
Currently, handlers called after completing an asynchronous
update of a DNS host or service simply decrement the number
of outstanding operations. It may lead to incorrect
handling of several SRP updates related to a single host,
sent within a short period of time, such as the ones below:
```
UPDATE1:
EXISTING_HOST
SERVICE1
UPDATE2:
EXISTING_HOST
SERVICE1
```
It may happen that both UPDATE1.EXISTING_HOST and
UPDATE2.EXISTING_HOST decrement the number of outstanding
operations for UPDATE1 and UPDATE1 is considered completed
even before UPDATE1.EXISTING_HOST.SERVICE1 is published.
Moreover, since the handlers can be called synchronously
in certain scenarios, it may occur that an update object
is released before PublishHostAndItsServices() exits which
may lead to accessing an invalid memory …
> [advertising-proxy] harden duplicate SRP update handling

- src/backbone_router/nd_proxy.hpp
- src/common/task_runner.hpp
- src/dbus/server/dbus_agent.hpp
- src/dbus/server/dbus_thread_object.hpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.hpp
- src/ncp/ncp_openthread.hpp
- src/openwrt/ubus/otubus.hpp
- src/rest/connection.hpp
- src/rest/rest_web_server.hpp
There are few benefits of documenting the same interface again in derived
classes but only introduce the burden of keeping them consistent when the
base class documentations are updated.
> [docs] remove redundant documentation

- CMakeLists.txt
- src/border_agent/border_agent.cpp
vn: vendor name
mn: model name
These fields are defined as optional in the spec.
> [meshcop] add vn and mn fields in meshcop service's TXT record

- src/border_agent/border_agent.cpp
- src/common/task_runner.hpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- src/sdp_proxy/advertising_proxy.cpp
- src/sdp_proxy/advertising_proxy.hpp
- tests/mdns/main.cpp
We are inconsistenly using both const char * and std::string in the
code which is sure bad practice. We have been seen bugs caused by
raw char * strings and I think it should be safer to use std::string
for easier life-time management.
This commit unifies the mDNS and advertising proxy modules to always
use std::string against const char * and std::vector<uint8_t> against
const uint8_t * whenever appliable. This makes the code more maintainable
and avoids potential memory segments.
This commit also removes the unused `aProtocol` and `aDomain` parameters
of `Publisher::Create()`.
------
This PR depends on https://github.com/openthread/ot-br-posix/pull/1072 so please review only the second commit, thanks.
> [mdns] unify mDNS interface to use std::string

- src/rest/resource.cpp
Removes the `TypeList` TLV (18) from the list of TLV type being requested as this is an invalid TLV type to request, which breaks getting diagnostic information from thread routers running OpenThread < https://github.com/openthread/openthread/commit/582c2c136ad798db0b3d2f0e495b5d620d9bcd0b (including the latest OpenThread Reference)
FIxes #1035
> [netdiag] do not request TypeList TLV type when retrieving diagnostics

- src/web/web-service/ot_client.cpp
- src/web/web-service/ot_client.hpp
This commit ensures to flush any received CLI output before issuing
the command to make parsing the output of the command more reliable.
> [web-service] flush any lingering output before issuing command

- src/web/web-service/frontend/index.html
- src/web/web-service/frontend/res/js/app.js
- Updated Passphrase label for clarity
- Added minLength requirement to Passphrase (6 minimum)
- Updated default Passphrase from `123456` to `j01Nme` to show that this field allows numbers/upper/lower characters
Let me know if this looks good; happy to make any changes.
> [web-service] update usage notes around `passphrase`

- doc/CMakeLists.txt
The `otbr-dbus-server-doc-copy` target depends on the output of the
Doxygen build. Add a dependency on the Doxgyen build.
---
Fixes the following error:
```
Doxygen build started
-- Configuring done
-- Generating done
-- Build files have been written to: /home/runner/work/ot-br-posix/ot-br-posix/build-doc
Writing index.html for refentry(gdbus-io.openthread.BorderRouter)
Built target otbr-dbus-server-doc
cp: cannot create regular file '/home/runner/work/ot-br-posix/ot-br-posix/build-doc/doc/html/dbus-api.html': No such file or directory
make[3]: *** [doc/CMakeFiles/otbr-dbus-server-doc-copy.dir/build.make:70: doc/CMakeFiles/otbr-dbus-server-doc-copy] Error 1
make[2]: *** [CMakeFiles/Makefile2:1942: doc/CMakeFiles/otbr-dbus-server-doc-copy.dir/all] Error 2
make[1]: *** …
```
> [docs] add dependency when building dbus docs

- src/mdns/mdns_avahi.cpp
This commit fixes a bug that `aName` is `nullptr` when `aEvent` is not `AVAHI_BROWSER_NEW`. So, we should only use 
`aName` on `AVAHI_BROWSER_NEW`.
> [mdns-avahi] fix potential crash on browsing

- src/agent/main.cpp
- src/ncp/ncp_openthread.cpp
- src/ncp/ncp_openthread.hpp
`otbr-agent` will exit directly if `--radio-version` is passed in
parameters. This PR sets the DryRun option in PosixConfig when
`radio-version` is set. In this way, the posix instance will only
initialize very few things to avoid permission issues.
> [agent] set dry-run option in Thread config if printRadioVersion is true

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- src/sdp_proxy/discovery_proxy.cpp
- src/sdp_proxy/discovery_proxy.hpp
Mdns::Publisher used to allow only one subscriber to add subscription callbacks via `SetSubscriptionCallbacks`. 
This PR enhances Mdns::Publisher to allow multiple subscribers to add and remove subscription callbacks. 
Hint: `Discovery Proxy` and `TREL DNSSD` will both need to add subscription callbacks.
> [mdns] support multiple subscribers

- src/mdns/mdns_mdnssd.cpp
`kDNSServiceFlagsMoreComing` does not mean there will be no more answers. 
So, we should not quit resolving when `kDNSServiceFlagsMoreComing` is not set.
- related change: use `kDNSServiceFlagsTimeout` to allow instance resolving to finish when timeout
Quote from dns_sd.h:
```c++
/* MoreComing indicates to a callback that at least one more result is
* queued and will be delivered following immediately after this one.
* When the MoreComing flag is set, applications should not immediately
* update their UI, because this can result in a great deal of ugly flickering
* on the screen, and can waste a great deal of CPU time repeatedly updating
* the screen with content that is then immediately erased, over and over.
* Applications should wait until MoreComing is not set, and then
* update their …
```
> [mdns] fix `kDNSServiceFlagsMoreComing` flag handling

- src/mdns/mdns_avahi.cpp
Background:
We used to use `assert` in `HandleResolveResult` to make sure the Avahi resolver is a valid resolver, which make sense because only valid resolvers can have callbacks. But there was a crash issue with the original code so we changed to use `VerifyOrExit`. Turn out the actual issue is that we should call `RemoveServiceResolver` as early as possible so that the resolver won't be freed twice.
> [mdns-avahi] use assert to make sure Service Resolver is valid

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/sdp_proxy/discovery_proxy.cpp
This commit enhance mDNS implementation over Avahi to support notification of service removing. 
mDNSResponder support will be implemented in a future PR. 
Required by #1109
> [mdns-avahi] support mDNS service removing

- src/common/code_utils.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
We are passing a pointer to the `ServiceSubscription` to Avahi methods like `avahi_service_browser_new` and `avahi_service_resolver_new` as the userdata. 
However, since `ServiceSubscription` objects were directly stored in a `vector<ServiceSubscription>`, any update to the vector causes the `ServiceSubscription` objects to move, leading to potential invalid pointer access. 
This commit fixes this issue by storing `ServiceSubscription` pointers in the vector. 
This commit also fixes the bug that the `ServiceSubscription` and `HostSubscription` objects may be freed in resolved callbacks.
> [mdns-avahi] fix potential invalid memory access

- src/mdns/mdns_mdnssd.cpp
`kDNSServiceFlagsMoreComing` is meant to make UI rendering more efficiently. 
```
/* MoreComing indicates to a callback that at least one more result is
* queued and will be delivered following immediately after this one.
* When the MoreComing flag is set, applications should not immediately
* update their UI, because this can result in a great deal of ugly flickering
* on the screen, and can waste a great deal of CPU time repeatedly updating
* the screen with content that is then immediately erased, over and over.
* Applications should wait until MoreComing is not set, and then
* update their UI when no more changes are imminent.
* When MoreComing is not set, that doesn't mean there will be no more
* answers EVER, just that there are no more answers immediately
* available right now at …
```
> [mdns-mdnssd] fix `kDNSServiceFlagsMoreComing` flag handling (part 2)

- src/agent/CMakeLists.txt
- src/agent/otbr-agent.service.in
This PR updates the `.service` file to start the mDNS daemon before starting otbr-agent. 
This PR fixes #1138 .
> [border-router] start mDNS daemon before starting otbr-agent

- .github/workflows/border_router.yml
This is a workaround for the border router test cases in CI. The CI failed in test_firewall.py because it hasn't turned on the DUA routing. I updated the OTBR options for building the docker and bumped the openthread submodule in this PR.
I thought the border router CI behave the same in ot-br-posix and openthread repos but that wasn't the case.
> [continuous-integration] enable DUA options in border router CI

- src/common/callback.hpp
- tests/unit/CMakeLists.txt
- tests/unit/test_once_callback.cpp
This commit adds a new facility which wraps up a std::function
and makes sure that a function can be invoked for at most once.
This is useful for async operations to guarantee that the callback
for receiving the result will be only invoked once.
> [common] add OnceCallback which can be invoked for at most once

- src/common/code_utils.hpp
This commit uses `__FILE__` in failure logs instead of `__FUNCTION__`.
It's difficult to locate the error when using `__FUNCTION__` because many methods are using the same name, e.g. `Init`.
> [utils] use `__FILE__` in failure logs

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This commit makes sure `DNSServiceProcessResult` is always called at the end of `Process`, so as to avoid potential memory issues.
> [mdnssd] call `DNSServiceProcessResult` at the end of `Process`

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/border_agent/border_agent.hpp
- src/ncp/ncp_openthread.cpp
- src/ncp/ncp_openthread.hpp
- src/rest/resource.cpp
This commit refactors radio version printing:
- Use a dedicated function for printing radio version
- Make `ControllerOpenThread` a member of `Application` so that `Application` is always properly constructed before initializing OpenThread instances.
> [agent] refactor radio version printing

- tools/reference_device/testharness-discovery
Current implementation returns on Windows platforms by default IPv4 address and with this PR we will start to return IPv6 link local.
> [certification] return ipv6 in testharness-discovery script

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/ncp/ncp_openthread.cpp
- src/ncp/ncp_openthread.hpp
Background:
- OpenThread Instance was the last member to destruct in Application, and `otSysDeinit` will be called when destructing OpenThread Instance. However, `otSysDeinit` may call methods of other Application members, which have been destructed at the moment. 
This commit introduces the `Deinit()` method to `ControllerOpenThread` and other classes to make sure OpenThread are properly de-initialized before destructing `Application`. The advantages are:
- `ControllerOpenThread` initializes OT instance in `Init`, so adding `Deinit` makes it symmetrical with `Init`. 
- Provide a predictable runtime environment (Application object fully constructed) for OT instance from `otSysInit` to `otSysDeinit`, making sure OT can safely access Application members during its lifetime.
> [application] de-initialize `Application` and OpenThread instance 

- .github/workflows/border_router.yml
This commit enhances Border Router tests reliability:
- Set MAX_JOBS = 3
- Set fail-fast = false
- Cache test results for re-runs
> [github-actions] border_router test enhancements

- src/agent/CMakeLists.txt
- src/agent/application.cpp
- src/agent/otbr-agent.service.in
- tests/scripts/check-scripts
This commit notifies service managers(systemd or upstart(ChromeOS)) that Thread service is ready. This commit also enhances systemd unit file so that otbr-agent will depends on d-bus socket unit.
> [agent] notify service manager when ready

- tests/scripts/check-scripts
This commit switch to cmake when building ot-rcp during tests.
> [test] use cmake to build ot-rcp

- script/_otbr
- src/agent/CMakeLists.txt
- src/agent/otbr-agent.default.in
- src/ncp/ncp_openthread.cpp
- src/ncp/ncp_openthread.hpp
This commit enhances `OTBR_NO_AUTO_ATTACH` option to disable auto Thread attaching for Reference Device:
- Use `-DOTBR_NO_AUTO_ATTACH=1` to disable auto  Thread attaching
> [certification] disable auto Thread attaching for Reference Device

- src/dbus/server/dbus_object.cpp
This commit refines DBus GetProperty error logs:
- Use INFO log level if the property is valid but handler returns error (used to be WARN)
> [dbus] refine DBus `GetProperty` error logs

- script/_dhcpv6_pd
- script/_network_manager
- script/console
- script/otbr-firewall
- script/server
- script/setup
- script/update
Add `set -euxo pipefail` to startup scripts. Then shellcheck complained about some issues in the unchanged shell scripts. I fixed the issues in this PR as well.
> [script] add `set -euxo pipefail` for startup scripts

- Android.mk
- etc/cmake/options.cmake
- etc/docker/docker_entrypoint.sh
- src/border_agent/CMakeLists.txt
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/common/logging.cpp
- src/common/logging.hpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/trel_dnssd/CMakeLists.txt
- src/trel_dnssd/trel_dnssd.cpp
- src/trel_dnssd/trel_dnssd.hpp
- tests/unit/test_logging.cpp
- third_party/openthread/CMakeLists.txt
This commit implements TREL DNS-SD module:
- Register local TREL service to mDNS publishers
- Browse remote TREL services from mDNS Publishers and maintain TREL peers
Some hints on implementation:
- TREL DNS-SD uses Extended Address as the TREL service instance name
- TREL DNS-SD pauses until all three conditions are met:
1. TREL DNS-SD was enabled by TREL core
2. TREL network interface (e.g. WiFi interface) is ready
3. mDNS Publisher is ready
Depends on #1183
> [trel-dnssd] Integrate TREL DNS-SD with avahi and mdnssd

- etc/docker/docker_entrypoint.sh
Both, --disable-default-prefix-route and --disable-default-prefix-slaac
have been used for wpantund which is no longer supported by the Docker
entrypoint script. Remove them to avoid confusion.
> [docker] remove unused arguments from Docker entrypoint

- script/test
- src/trel_dnssd/trel_dnssd.cpp
- src/trel_dnssd/trel_dnssd.hpp
This commit fixes TREL DNS-SD compile issue regarding https://github.com/openthread/ot-br-posix/pull/1113
> [trel-dnssd] fix compile

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
Current implementation invokes the service/host registration callback before removing the
`ServiceRegistraion` entry from the `ServiceRegistraionMap`. This will result in invalid access
to the `ServiceRegistration` entry when it's freed from the callback. This commit changes to
invoke the callback after removing the entry.
> [mdns] remove ServiceRegistration before invoking the callback

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
`otbr-agent` should reconnect to the mDNS service when the mDNS restarts. Basically, it should clear published services and subscribed services.
Test: https://github.com/openthread/openthread/pull/7363
> [mdns] handle mDNS daemon restart for mDNSResponder and Avahi

- src/sdp_proxy/advertising_proxy.cpp
This PR fixes https://github.com/openthread/ot-br-posix/issues/1251.
I'll add a build test to cover uninitialized variables.
> [advertising-proxy] fix uninitialized variable

- src/web/web-service/web_server.cpp
Explicitly setting Content-Type avoids confusion in cases where proxy or similar
intermediaries are involved.
> [web] set text/html Content-Type for html files

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
- src/sdp_proxy/advertising_proxy.cpp
We should publish/unpublish SRP services before publishing/unpublishing
a SRP host because we have no guarantee of either the `otSrpHost` object
will be released or not after calling `Mdns::Publisher::UnpublishHost`.
Tests are covered in https://github.com/openthread/openthread/pull/7440.
------
Fixes: https://github.com/openthread/ot-br-posix/issues/1272
> [advertising-proxy] unpublish services before unpublishing a SRP host

- script/_firewall
- script/otbr-firewall
This PR fixes https://github.com/openthread/ot-br-posix/issues/1286.
Also, this PR clears the firewall rules when the firewall service is uninstalled. Previously firewall rules aren't cleared immediately when the service is uninstalled, which may not be a desired behavior.
> [firewall] clear firewall rules before starting a new firewall 

- script/otbr-firewall
Removing the `-p ip` argument because it's a no-op and it may not be supported by some old versions of iptables.
> [firewall] remove `-p ip` argument in ip6tables rules

- src/border_agent/border_agent.cpp
- src/sdp_proxy/advertising_proxy.cpp
- src/sdp_proxy/discovery_proxy.cpp
When the D-BUS API `Reset` is invoked, 
- re-register `UpdateMeshCopTxtHandler`
- reset advertising proxy callbacks
- reset discovery proxy callbacks
> [dbus] fix OTBR's behavior when `Reset` is invoked

- .github/ISSUE_TEMPLATE.md
- CMakeLists.txt
- README.md
Replace link to openthread-users Google Group with link to GitHub OpenThread Discussions, clarify issue reporting links.
> [docs] community discussion change

- src/border_agent/border_agent.cpp
otbr-agent generates `WARNING` level logs when there are frequent meshcop service updates: 
```
otbr-agent[2638658]: [WARN]-BA------: Result of publish meshcop service OpenThread BorderRouter._meshcop._udp.local: Aborted
otbr-agent[2638658]: [WARN]-BA------: Result of publish meshcop service OpenThread BorderRouter._meshcop._udp.local: Aborted
```
Such a log line is generated because an ongoing meshcop service registration is canceled for some reason (a newer registration preempts the previous registration, or border agent wants to stop advertising the service). However, this behavior is working as expected and shouldn't be regarded as an error. Hence I lowered the log level to `INFO` in such cases.
> [border-agent] don't treat `OTBR_ERROR_ABORTED` as an error in logs

- src/sdp_proxy/discovery_proxy.cpp
I checked all logging lines by `grep -rn otbrLog src/` and `discovery_proxy.cpp` is the only file using lower case for every first letter in log messages.
> [logging] use capitalized first letter for log messages

- src/web/web-service/ot_client.cpp
The select.h header file is needed for fd_set(). Depending on the
compiler and libc combinations this will result in an error when
not included. I saw the error with gcc and musl on our builds.
Signed-off-by: Stefan Schmidt <stefan.schmidt@huawei.com>
> [web-service] ot-client: add needed header for fd_set() call

- src/agent/main.cpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
When `otPlatReset` is called on `otbr-agent`, it should de-init the old `otbr::Application` so that the resources will be properly disposed, otherwise there will be dangling resources. Also, `otbr::Application` should de-init the TREL module when itself is de-initing.
One example is that if we call `ot-ctl factoryreset`, the old `otbr::Application` won't be destructed so that the publisher will keep the old mDNS service registrations until the process exits. In such a situation, there will be two different MeshCoP services published by the same `otbr-agent` process. This test case is introduced in https://github.com/openthread/openthread/pull/7592.
Also, this PR adds a verification at `Publisher` public methods to ensure that `Publisher` is at `kReady` state.
> [platform] de-init application in `otPlatReset` and verify `Publisher` state in public methods

- src/sdp_proxy/advertising_proxy.cpp
This commit updates `AdvertisingProxy` so that when it is unpublishing
a host or service entry on the underlying `Mdns::Publisher` if the
returned error is `OTBR_ERROR_NOT_FOUND` the error is treated as
success and reported as such to OT core `Srp::Server`. This ensures
that an SRP update request to remove a not previously registered
host/service is not rejected by the platform and therefore by the
`ot::Srp:Server`
> [adv-proxy] treat `NOT_FOUND` as success when unpublishing host/service

- tests/dbus/test-client
- tests/scripts/bootstrap.sh
This PR adds a test case to verify D-BUS APIs are working well after a `Reset` call.
This PR also updates the mDNSResponder to latest in `tests/scripts/bootstrap.sh`.
> [tests] add a test case of D-BUS API `Reset`

- src/agent/main.cpp
This commit refine the booting logs fore better debugging:
- Use `NOTE` log level instead of `INFO` since the log information is important
- Combine multiple logs to one log
An example of final log:
```
[NOTE]-AGENT---: Running version 0.3.0-7f48d63a4b; Thread version: 1.2.0, interface: wpan0; Backbone interface: eth0; Radio URL: spinel+hdlc+forkpty:///home/pi/bin/ot-rcp?forkpty-arg=1 trel://eth0
```
> [agent] refine booting logs

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- tests/scripts/meshcop
This PR appends last 2 bytes of extended address to the MeshCoP service instance name. This is used for reducing service instance name conflicts when there are two BRs of the same model connected to the same wifi.
An example of the new service instance name is `OpenThread BorderRouter #B76D`.
> [meshcop] append last 2 bytes of ext addr to service instance name

- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
- tests/dbus/CMakeLists.txt
- tests/dbus/test-client
This PR changes the behavior of `AttachAllNodesTo` when there is an active dataset but the device isn't attached to it:
Before this PR: if the device is in `detached` or `disabled` state, and it has an active dataset, it returns an error.
After this PR: if the device is in `detached` or `disabled` state, and it has an active dataset, it attaches to the network specified by the active dataset, and then sends a `MGMT_PENDING_SET` command to set the pending dataset to the dataset specified by the argument.
> [dbus] allow `AttachAllNodesTo` when has active dataset but detached

- .github/workflows/build.yml
- src/dbus/client/thread_api_dbus.cpp
- src/dbus/client/thread_api_dbus.hpp
- src/dbus/common/constants.hpp
- src/dbus/common/dbus_message_helper.hpp
- src/dbus/common/dbus_message_helper_openthread.cpp
- src/dbus/common/types.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/dbus_thread_object.hpp
- src/dbus/server/introspect.xml
- tests/dbus/test_dbus_client.cpp
- tests/rest/test-rest-server
This PR implements the D-BUS API `GetSrpServerInfo` for getting the information of the SRP server. 
This PR depends on the new SRP server APIs introduced in https://github.com/openthread/openthread/pull/7680 which is not merged yet. Hence it cannot pass the CI for now.
> [dbus] implement D-BUS API `GetSrpServerInfo`

- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/meshcop.yml
This commit sets `fail-fast: false` for matrix in GitHub Actions so
that tests in a matrix do not fail all at once. It's more convenient
now that we can re-run failed tests.
> [github-actions] set `fail-fast: false` for matrix

- src/agent/application.cpp
- src/agent/application.hpp
This commit remove potential data race on `sShouldTerminate`, which is accessed in both main loop and the signal handler.
> [agent] remove potential data race on `sShouldTerminate`

- src/mdns/mdns_mdnssd.cpp
Previously `otbr-agent` treats `Bad Reference` error as `Warning` level when logging. However, the `Bad Reference` is sometimes expected.
For example, when're querying PTR record via discovery proxy and there are multiple instances being discovered. 
1. `otbr-agent` calls `GetAddrInfo` on every discovered instance. `ServiceRef`s are created accordingly.
2. In a `Process` call:
1. All ready `ServiceRef`s are pushed into `readyServices`. Then `otbr-agent` processes every `ServiceRef` in `readyServices`.
2. When the first `GetAddrInfo` callback returns with a valid address, it finishes the resolution.
3. Discovery proxy unsubscribes the service. The related `ServiceRefs` are all destructed. However, they are still being referenced in `readyServices`. When a destructed `ServiceRef` is …
> [mdns] downgrade the log level for `Bad Reference` error with `mDNSResponder`

- src/backbone_router/CMakeLists.txt
Link `netfilter_queue` library only when `OTBR_DUA_ROUTING` is on.
> [build] link `netfilter_queue` on demand

- script/_otbr
- third_party/openthread/CMakeLists.txt
1. Have the OTBR POSIX app use the default Thread version on the stack.
2. Turn on OTBR_DUA_ROUTING and OT_DUA for reference devices.
3. Fix check for version (not 1.1) for DUA and MLR options.
> [build] fixes for Thread Version configuration

- src/dbus/common/dbus_message_helper.hpp
- src/dbus/common/dbus_message_helper_openthread.cpp
- src/dbus/common/types.hpp
- src/dbus/server/dbus_thread_object.cpp
- tests/dbus/test_dbus_client.cpp
According to the convention, we should not use any openthread headers in this `dbus/common/types.hpp`. Introducing the openthread headers may sometimes break downstream builds.
> [dbus] fix `dbus/common/types.hpp`

- src/common/code_utils.hpp
- src/dbus/server/dbus_request.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/introspect.xml
- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
- tests/dbus/test-client
This commit:
1. Makes the DBus API `AttachAllNodesTo` return the delay between the method returns and the dataset takes effect.
2. Ensures that when `AttachAllNodesTo` returns, the node is attached.
> [dbus] return delay timer from `AttachAllNodesTo`

- tests/dbus/test_dbus_client.cpp
This commit adds some delay to DBus client tests to give the network data some time to propagate.
> [tests] fix DBus intermittent failures

- .github/workflows/border_router.yml
- etc/cmake/options.cmake
- third_party/openthread/CMakeLists.txt
This commit adds an option `OTBR_BORDER_ROUTING_NAT64` for setting `OT_BORDER_ROUTING_NAT64` in ot-br-posix.
> [nat64] add OTBR_BORDER_ROUTING_NAT64 option

- .github/workflows/docker.yml
`Hirsute` has reached end of life: https://fridge.ubuntu.com/2022/01/21/ubuntu-21-04-hirsute-hippo-end-of-life-reached-on-january-20-2022. It causes CI failures like https://github.com/openthread/ot-br-posix/runs/7494641990?check_suite_focus=true. 
We should test it on the latest Ubuntu LTS `Jammy` instead.
> [continuous-integration] replace `Hirsute` with `Jammy` as the Ubuntu release in docker CI

- src/common/task_runner.cpp
- src/common/task_runner.hpp
There is an issue in `TaskRunner` that it declares `Task<void>` as a const parameter in interfaces (e.g. `void TaskRunner::Post(const Task<void> aTask)`). In the implementation it `std::move`s the `aTask` and pushed it into an STL container. This `std::move` on the const value doesn't lead to the move constructor of `Task<void>` which may have better performance. It leads to the copy constructor instead. To fix this, we need to make the `aTask` a non-const parameter.
> [task-runner] fix `std::move` on const values

- tests/scripts/bootstrap.sh
To avoid errors such as this: https://github.com/openthread/ot-br-posix/runs/7634987232?check_suite_focus=true
> [tests] upgrade pip before installing cmake

- src/border_agent/border_agent.cpp
BBR states should only be active when Thread state is active.
> [border-agent] fix BBR states in MeshCoP service TXT record

- src/sdp_proxy/advertising_proxy.cpp
- src/sdp_proxy/advertising_proxy.hpp
This PR lets advertising proxy filter out mesh local addresses when publishing SRP hosts. If an SRP host only has mesh local addresses, the advertising proxy will register the service by mDNS with no address.
> [advertising-proxy] don't publish mesh local addresses for hosts

- script/test
- src/web/web-service/frontend/CMakeLists.txt
This commit makes `npm install` only be called when necessary, i.e.
package.json is updated or the output files are not generated.
> [web] call npm install when necessary

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- src/sdp_proxy/advertising_proxy.cpp
- tests/mdns/main.cpp
This PR:
- Allows Advertising Proxy to publish multiple host addresses. 
- Allows Publisher to publish multiple host addresses.
Test is covered in https://github.com/openthread/openthread/pull/8003/.
> [advertising-proxy] support publishing multiple host addresses

- .github/workflows/border_router.yml
To address this failure: https://github.com/openthread/ot-br-posix/runs/7861845103?check_suite_focus=true
```
======================================================================
FAIL: test (__main__.Nat64MultiBorderRouter)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./tests/scripts/thread-cert/border_router/nat64/test_multi_border_routers.py", line 118, in test
self.assertEqual(nat64_prefix, br2_infra_nat64_prefix)
AssertionError: 'fd67:b595:c3ab:2:0:0::/96' != 'fdf9:4f70:b5e2:2:0:0::/96'
- fd67:b595:c3ab:2:0:0::/96
+ fdf9:4f70:b5e2:2:0:0::/96
----------------------------------------------------------------------
```
> [github-actions] add NAT64 env

- script/_otbr
Force re-evaluation of OTBR version strings (both OTBR version for otbr-agent daemon and OT version for the POSIX stack) if not supplied by the user.  This prevents them from using previously cached values from CMakeCache in case the project is being re-built over a previously installed / cached version.
> [script] don't use cached version strings if re-installing OTBR

- script/_otbr
- script/bootstrap
This PR fixes the conditions to enable the openthread NAT64 and to disable installing tayga.
> [nat64] fix the condition to enable ot nat64 translator and not install tayga

- .github/workflows/border_router.yml
To address the NAT64 check failure blocking:
- https://github.com/openthread/ot-br-posix/pull/1553
> [github-actions] set `NAT64_SERVICE=openthread`

- script/_dns64
When building on Debian with NAT64=1 and DNS64=0, the setup script will complain "dns64 is not tested on debian"
Since DNS64 is not necessary for NAT64, the script should continue in this case instead of die.
> [build] correct the condition when complaining about DNS64

- etc/cmake/options.cmake
- script/_otbr
- src/ncp/ncp_openthread.cpp
- third_party/openthread/CMakeLists.txt
This PR adds the OTBR_NAT64 flag since we cannot use OT_CONFIG_NAT64_* flags in ot-br-posix.
Note: We will remove tayga support later, and https://github.com/openthread/ot-br-posix/pull/1539/ is merged, so in `script/_otbr` we only enable OTBR_NAT64 when NAT64 is set and NAT64_SERVICE is openthread.
> [nat64] enable NAT64 on start

- script/bootstrap
- tests/scripts/bootstrap.sh
- tests/scripts/check-android-build
Fetch mDNSResponder's source code from https://github.com/apple-oss-distributions/mDNSResponder.
Fixes https://github.com/openthread/ot-br-posix/issues/1591.
> [mdns] replace the source of mDNSResponder

- Android.mk
This PR links the `libanl` library to the otbr-agent module in Android.mk. This library is needed for properly referencing the `getaddrinfo_a` function in openthread/src/posix/platform/netif.cpp
> [nat64] link libanl library to the otbr-agent module in Android.mk

- etc/cmake/options.cmake
- etc/docker/Dockerfile
- src/dbus/common/constants.hpp
- src/dbus/common/dbus_message_helper.hpp
- src/dbus/common/dbus_message_helper_openthread.cpp
- src/dbus/common/types.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/dbus_thread_object.hpp
- src/dbus/server/introspect.xml
- third_party/openthread/CMakeLists.txt
This PR implements the D-BUS API `GetBorderRoutingCounters`. 
Test covered in https://github.com/openthread/openthread/pull/8341.
> [dbus] implement D-BUS API `GetBorderRoutingCounters`

- etc/cmake/options.cmake
Fix an issue that Border Routing counters is not available when `OTBR_BORDER_ROUTING` is off but `OTBR_BACKBONE_ROUTER` is on.
> [build] fix the condition of enabling Border Routing counters

- script/_disable_services
There is no check for having `systemctl` in the[ _disable_services](https://github.com/openthread/ot-br-posix/blob/main/script/_disable_services) script even though this check exists all around the project. This causes the setup to fail if the machine does not have the `systemctl` command.
Added necessary condition before using `systemctl`.
Fixes #1607
> [scripts] fix: check if systemctl exists before using it

- .github/dependabot.yml
Add a Dependabot configuration that checks once a week if the GitHub Actions are still using the latest version. If not, it opens a PR to update them.
It will actually open few PRs, since only major versions are specified (like v3), so only on a major release (like v4) it will update and open a PR. But it helps actively keep GitHub Actions workflows up to date and secure.
See [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).
> [github-actions] add Dependabot configuration for GitHub Actions updates

- .github/workflows/meshcop.yml
Check is currently failing for unknown reasons: https://github.com/openthread/ot-br-posix/actions/runs/3518681133/attempts/15
> [github-actions] disable `meshcop (mDNSResponder)` check

- src/dbus/server/dbus_thread_object.cpp
Some link counters are assigned with wrong values in DBus API.
> [dbus] fix link counter values

- src/dbus/server/dbus_thread_object.cpp
- tests/dbus/keep_running.sh
This commit makes the DBus API "LeaveNetwork" use a specific exit code so the platform can differentiate normal exits and exits that should be followed by a restart.
> [dbus] change exit code for "LeaveNetwork"

- .github/workflows/build.yml
- etc/cmake/options.cmake
- src/ncp/ncp_openthread.cpp
The `AutoEnableMode` delegates the control of SRP server to the Border Routing Manager.
The `AutoEnableMode` was introduced to openthread in https://github.com/openthread/openthread/pull/8129.
> [srp-server] support `AutoEnableMode` for SRP server in OTBR 

- etc/cmake/options.cmake
- src/border_agent/border_agent.cpp
The latest spec requires an OMR field in the TXT record of the MeshCoP mDNS service.
> [meshcop] publish OMR prefix in TXT record

- src/rest/json.cpp
- src/rest/json.hpp
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/types.hpp
Support getting and setting the active dataset via REST. The active data set is returned as operational dataset encoded as TLV hex string. The `PUT` method along with the body with the dataset encoded in the same format can be used to set the current active dataset.
> [rest] add active dataset API

- .github/workflows/macOS.yml
This PR fixes the `brew link` error in macOS CI.
> [continuous-integration] fix macOS CI

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/rest/rest_web_server.cpp
- src/rest/rest_web_server.hpp
Allow to bind to a specific address to listen to for REST requests. This allows to limit access to the REST interface e.g. from localhost only.
> [rest] allow to specify REST listen address

- script/bootstrap
No reason to limit wget to IPv4 only, which breaks IPv6 only machines.
Fixes #1697
> [bootstrap] fix to work on IPv6 only machines

- src/rest/response.cpp
A space is already added in Response::Serialize(). According to the HTTP specification there should only be a single space between the protcol version and the status code.
> [rest] remove superfluous space in HTTP status line

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
- tests/mdns/main.cpp
- tests/mdns/test-single-empty-service-name
This PR has 2 enhancements for mDNS publisher which may be useful for supporting SRPL.
- Fix a potential bug: A service subscription callback may modify the container `mDiscoveredCallbacks`. This can invalidate an iterator and results in a crash.
- Supports publishing a service using the hostname as the service instance name.
> [mdns] publish a service using the default hostname as the instance name

- etc/docker/docker_entrypoint.sh
On some systems where I try to run the image, it seems that there is a race and sometimes the script tries to read the logs before syslog is ready.
I'm not sure if somebody else encountered this problem.
Here I propose a quick workaround.
Here is an example output where 1 retry was necessary:
```
...
++ printenv WEB_GUI
+ value=1
+ [[ -z 1 ]]
+ [[ 1 == 1 ]]
+ sudo service otbr-web status
* otbr-web is not running
+ sudo service otbr-web start
* Starting thread web interface otbr-web                                                                                                                                          [ OK ] 
+ . /dev/null
tail: cannot open '/var/log/syslog' for reading: No such file or directory
tail: no files remaining
Jan 20 11:39:34 nuc2 otbr-agent[129]: 00:00:00.039 …
```
> [docker] retry reading syslog

- etc/docker/docker_entrypoint.sh
- script/server
- tests/scripts/check-docker
Catch the docker sigterm and handle a clean shutdown.
At least those advantages come to mind:
1. Allows for a faster shutdown (about 1.5s as seen in the example below) because we don't have to wait until docker times out (10s) and kills everything.
```
container-otbr-autostart-otbr-1   | Jan 21 14:28:04 nuc2 otbr-agent[93]: 00:00:15.619 [I] BorderRouter--: RouterAdvert: Added RIO for fd04:2240:0:20::/64 (lifetime=1800)
container-otbr-autostart-otbr-1   | Jan 21 14:28:04 nuc2 otbr-agent[93]: 00:00:15.619 [I] BorderRouter--: Sent Router Advertisement on infra netif 2
container-otbr-autostart-otbr-1   | Jan 21 14:28:04 nuc2 otbr-agent[93]: 00:00:15.619 [I] BorderRouter--: Start evaluating routing policy, scheduled in 16000 milliseconds
container-otbr-autostart-otbr-1   | Jan 21 14:28:04 nuc2 …
```
> [docker] perform a proper shutdown

- src/ncp/ncp_openthread.cpp
This PR uses otTrelSetEnabled api instead of the deprecated otTrelEnable/otTrelDisable apis.
Related to https://github.com/openthread/openthread/pull/8731
> [trel] use `otTrelSetEnabled` instead of `otTrelEnable`/`otTrelDisable`

- etc/docker/Dockerfile
This PR changes the order of the steps for building the OTBR docker image. In this way we can leverage more on the docker build cache and save time when building an image. 
When we want to build an image after only modifying C++ code, we won't need to rerun the bootstrap step.
Local runs comparison:
- Before:
- Build without cache: 7m32.835s
- Build with cache: 6m40.570s
- After:
- Build without cache: 6m32.783s
- Build with cache: 2m13.498s
> [docker] accelerate building an OTBR docker image by cache

- script/clang-format
`script/clang-format` is supposed to add an EOF newline for every file passed in as an argument. However, the script only processed the first file. This can cause `script/make-pretty check` to fail even after `script/make-pretty clang`.
> [pretty] fix `script/clang-format`

- src/rest/response.cpp
By default, HTTP 1.1 connections should stay open after a transaction. However, that is not how the current REST server implementation behaves: After each transaction the HTTP connection is being closed by the server.
Set the Connection header to "close" to tell the client about this behavior.
> [rest] explicitly set Connection header to close

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
There is a difference between avahi and dns-sd browse operation. An update in a discovered instance doesn't trigger any avahi browse events, while for dns-sd rmv/add events are triggered.
In the current avahi mdns design, after service browse we resolve the discovered instance once, when instance is resolved the resolver is removed.
Trel uses dnssd browse to discover peers, when a discovered peer changes ipv6 address, trel would not know the change and still try to send packets to the old address.
This PR changes the avahi mdns to keep service resolver until the instance is removed, so any updates to the instance will be noticed.
A followup to this PR is to add test in openthread.
> [mdns] keep avahi service resolver until instance is removed

- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
Recently we got a crash issue on `otbr-agent`. From the coredump, it's a caused by a `bad_function_call` exception:
```
#4  0x00478f22 in std::__1::__throw_bad_function_call () at prebuilt/toolchain/armv7a/usr/bin/../include/c++/v1/functional:1441
#5  0x00492834 in otbr::agent::ThreadHelper::MgmtSetResponseHandler (this=<optimized out>, aResult=OT_ERROR_NONE) at ot-br-posix/src/utils/thread_helper.cpp:670
#6  0x004a9238 in ot::MeshCoP::DatasetManager::HandleMgmtSetResponse (this=0x53bfdc <ot::gInstanceRaw+134420>, aMessage=<optimized out>, aMessageInfo=<optimized out>, aError=<optimized out>) at openthread/src/core/meshcop/dataset_manager.cpp:358
#7  0x0049c3a2 in ot::Coap::CoapBase::ProcessReceivedResponse (this=0x0, aMessage=..., aMessageInfo=...) at …
```
> [dbus] fix null attach handler issue

- README.md
I found that there were quite a few developers' questions which at the end can be solved
by following the Border Router codelab. So this commit updates the README.md to promot
the Border Router codelab as the best way for a developer to set up a 1.3 Border Router
with OTBR.
> [docs] link the Border Router codelab in README

- .github/workflows/border_router.yml
- script/_otbr
Actually missing from previous PR.
Would suggest merge without sequash.
> [nat64] enable upstream DNS forwarding when NAT64 is enabled

- .github/workflows/border_router.yml
- .github/workflows/docker.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [github-actions] replace deprecated `set-output` commands

- src/rest/json.cpp
- src/rest/json.hpp
- src/rest/openapi.yaml
- src/rest/parser.cpp
- src/rest/request.cpp
- src/rest/request.hpp
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/response.cpp
- src/rest/response.hpp
- src/rest/types.hpp
- src/utils/hex.cpp
- src/utils/hex.hpp
This PR extends the REST API to support reading and writing Active and Pending Operational Datasets. It largely implements what has been discussed in https://github.com/openthread/openthread/discussions/8567.
It adds the following endpoints and methods:
* /node/dataset/active [`GET`, `OPTIONS`, `POST`, `PUT`]
* /node/dataset/pending [`GET`, `OPTIONS`, `POST`, `PUT`]
The `GET` method returns current datasets, `POST` allows to create a new dataset (with defaults as initialized by the OpenThread implementation just like `ot-ctl dataset init new`). Any fields provided with `POST` will overwrite the defaults, hence a call like
```
curl -X POST http://localhost:8081/node/dataset/pending -d '{ "Delay": 30000, "ActiveTimestamp": 10 }'
```
Is equivalent to:
```
ot-ctl dataset init new
ot-ctl …
```
> [rest] add Operational Dataset API

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/rest/rest_web_server.cpp
- src/rest/rest_web_server.hpp
Allow to bind to a specific port to listen to for REST requests. Note that the built-in web interface always assumes the REST to be available on port 8081!
> [rest] allow to specify REST listen port

- src/rest/json.cpp
- src/rest/openapi.yaml
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/types.hpp
Add BaId to the node JSON object and add a dedicated endpoint
/node/ba-id to retrive the border agent ID.
Also return node information even when the border router is
detached.
> [rest] return border agent ID

- src/dbus/common/dbus_message_helper.hpp
- src/dbus/common/dbus_message_helper_openthread.cpp
- src/dbus/server/dbus_thread_object.cpp
- src/dbus/server/introspect.xml
I ran into an issue while trying to use the `dbus` `Scan` API. For my platform (imx6ull, built with yocto), I was able to repeatably cause `otbr` to error by running:
```
dbus-send --reply-timeout=30000 --print-reply --system --type="method_call" --dest=io.openthread.BorderRouter.wpan0 /io/openthread/BorderRouter/wpan0 io.openthread.BorderRouter.Scan
```
Callstack:
```
[ 00 ] __libc_do_syscall
[ 01 ] __pthread_kill_implementation ( pthread_kill.c:43 )
[ 02 ] raise ( raise.c:26 )
[ 03 ] abort ( abort.c:79 )
[ 04 ] 0x76ee4f63
[ 05 ] free_mem
[ 06 ] 0x76ed56a5
[ 07 ] 0x76eedbbe
[ 08 ] 0x76eec106
[ 09 ] 0x76ed5927
[ 10 ] 0x76ef27e2
[ 11 ] 0x76eedbbe
[ 12 ] 0x76eecbe2
[ 13 ] 0x76eec106
[ 14 ] 0x76eec106
[ 15 ] 0x76ec0d15
[ 16 ] 0x76eedbbe
[ 17 ] 0x76ec0bdf
[ 18 ] 0x76eedbbe
[ 19 ] …
```
> [dbus] fix `Scan` crashing

- src/common/CMakeLists.txt
- src/common/api_strings.cpp
- src/common/api_strings.hpp
- src/dbus/client/thread_api_dbus.cpp
- src/dbus/common/constants.hpp
- src/dbus/server/dbus_thread_object.cpp
- src/rest/json.cpp
- src/rest/json.hpp
- src/rest/openapi.yaml
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/types.hpp
- tests/rest/test_rest.py
Allow to enable and disable the Thread protocol operation.
> [rest] support Thread state change

- script/bootstrap
This is used for leveraging `avahi-publish` tool in BR test cases like https://github.com/openthread/openthread/pull/9075.
> [scripts] install `avahi-utils` in `script/bootstrap`

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
Avahi only returns one of the host's addresses in the service resolution callback. However, the address may be link-local so it may not be preferred from Thread's perspective. We want to go through the complete list of addresses associated with the host and choose a routable address. Therefore we use `RecordBrowser` which can do this job.
> [mdns] let avahi use `RecordBrowser` to resolve addresses of a service

- src/openwrt/view/admin_thread/thread_view.htm
This delegates the decision to use HTTPS or HTTP to the browser, so if the OpenWrt web server is using HTTPS, there will be no mixed content error preventing D3.js from loading.
> [openwrt] load D3.js over webserver protocol

- script/_nat64
Current firewall rules uses a static CIDR for NAT64. This will block all traffic if we change the NAT64 CIDR。
This PR uses fwmark to identify the traffic from wpan0 interface for NAT44.
This is mainly for testing purpose.
Test: https://github.com/openthread/openthread/actions/runs/5114000045/jobs/9193809926
> [docker] support updating nat64 CIDR during runtime

- .github/workflows/macOS.yml
- src/proto/CMakeLists.txt
Fix Mac compile issue for latest brew protobuf library. Detail error log:
static_assert(PROTOBUF_CPLUSPLUS_MIN(201402L), "Protobuf only supports C++14 and newer.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [github-actions] fix macOS workflow error due to protobuf library

- src/rest/resource.cpp
When there is already a dataset, and setting properties using the PUT method and an incomplete JSON dataset, some fields of the dataset variable might not be initialized. This leads to uninitialized data being used as active dataset.
Make sure we initialize the dataset variable. This makes sure that all components of the dataset are considered not set.
> [rest] initialize dataset

- src/rest/resource.cpp
Deactivate the IPv6 interface when disabling the OTBR. This follows the Attach/Deatach semantics of the D-Bus API.
> [rest] deactive IPv6 interface when disabling the OTBR

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
https://github.com/openthread/ot-br-posix/blob/main/src/mdns/mdns_avahi.cpp#L1261
`PublisherAvahi::ServiceResolver::HandleResolveHostResult` passes the reference of `ServiceResolver::mType` to `OnServiceResolved()` function which calls each registered service discovery callback on the resolved service. The ServiceResolver may be removed by a callback, when there are more callbacks called afterwards, there will be a crash as the `mType` is gone.
> [mdns] pass copy of `mType` for `OnServiceResolved`

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
This commit updates all base class `Publisher::On{Item}Resolved()` callbacks to use value parameters instead of `const` reference. This change ensures that the objects passed to these callbacks will not be freed until the callbacks have completed and prevent any potential problem. In particular user may unsubscribe (invoke `UnsubscribeService()` or `UnsubscribeHost()`) from the callback.
----
This is follow up https://github.com/openthread/ot-br-posix/pull/1910.
> [mdns] all `On{Item}Resolved()` callbacks to use value parameters

- src/common/callback.hpp
This commit updates the `OnceCallback` move constructor and move assignment operator to ensure that the passed-in rvalue reference is cleared.
----
Should help address https://github.com/openthread/ot-br-posix/issues/1912.
> [callback] update `OnceCallback` to clear moved-from rvalue reference

- src/common/code_utils.hpp
- tests/scripts/openwrt
This commit updates the `SuccessOrExit` macro to accept an action before goto "exit". It allows us to add a log when error happens. For example, we can write:
```
SuccessOrExit((error = writeDatasetToSettings()), otbrLogErr("Failed to write dataset to settings"));
```
So that we know exactly which step a method fails at.
------
This commit also prints the error/status code for macro `SuccessOrDie`.
> [utils] update SuccessOrExit for error tracking

- src/sdp_proxy/advertising_proxy.cpp
----
Depends-On: openthread/openthread#9208
This updates is related to 
- https://github.com/openthread/openthread/pull/9208
> [adv-proxy] use new `otSrpServer` API for service sub-types

- src/rest/openapi.yaml
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/response.cpp
Add REST API to support erasing all persistent information, effectively factory resetting the OTBR. The implementation follows the semantic of the D-Bus API and automatically disables the Thread network.
After erasing all persistent information the dataset is cleared too. So this allows to build a new Thread network with subsequent use of the PUT method to the /node/dataset/active endpoint.
> [rest] support erasing all persistent info

- src/dbus/server/dbus_object.cpp
Currently each time dbus property handler is called, there will be a log.
This will cause flooding log when the dbus client is doing polling:
```
2023-02-26 11:45:47.084  9117  9117 I otbr-agent: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.Get
2023-02-26 11:45:47.085  9117  9117 I otbr-agent: [INFO]-DBUS----: GetProperty io.openthread.BorderRouter.DeviceRole
2023-02-26 11:45:47.109  9117  9117 I otbr-agent: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.Get
2023-02-26 11:45:47.109  9117  9117 I otbr-agent: [INFO]-DBUS----: GetProperty io.openthread.BorderRouter.LinkMode
2023-02-26 11:45:47.115  9117  9117 I otbr-agent: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.Get
2023-02-26 11:45:47.115  9117  9117 I otbr-agent: …
```
> [dbus] change info logs of property handler to debug

- src/agent/main.cpp
- src/common/logging.cpp
- src/common/logging.hpp
- src/web/main.cpp
On Android, we use the "ot-daemon" name for the runnable program
and want the syslog id be updated to "ot-daemon" as well. Instead of
hard coding the syslog id, this commit derive the id from the program
name so it works for both linux and Android.
For example, logs on Android will be like:
```
ot-daemon[2152867]: [NOTE]-AGENT---: Running 0.3.0-090e5b55-dirty
ot-daemon[2152867]: [NOTE]-AGENT---: Thread version: 1.3.0
ot-daemon[2152867]: [NOTE]-AGENT---: Thread interface: wpan0
```
> [logging] use program name for log id

- src/agent/vendor.hpp
BinderServer on Android will need to retrieve the `mNcp` object from the VendorServer.
See [aosp/2648679](https://android-review.git.corp.google.com/c/platform/external/ot-br-posix/+) for BinderServer implementation
> [utils] add mNcp to VendorServer

- src/agent/CMakeLists.txt
`ExecStartPre` may require an absolute path for the executable.
Fixes #1960.
> [scripts] fix `ExecStartPre` in `otbr-agent.service`

- etc/docker/Dockerfile
This saves ~28MB by clearing out `/tmp`
```shell
root@4f33863bee35:/tmp# ll
total 2936
drwxrwxrwt  1 root root    4096 Sep  1 21:20 ./
drwxr-xr-x  1 root root    4096 Sep  1 21:52 ../
drwxr-xr-x 12 root root    4096 Sep  1 21:18 mDNSResponder-1790.80.10/
-rw-r--r--  1 root root 2989629 Sep  1 21:18 mDNSResponder-1790.80.10.tar.gz
drwxr-xr-x  3 root root    4096 Sep  1 21:20 npm-2233-869f1b4a/
root@4f33863bee35:/tmp# du -sh . --block-size=M
28M     .
```
> [docker] cleanup `/tmp`

- src/border_agent/border_agent.cpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/sdp_proxy/advertising_proxy.cpp
- src/trel_dnssd/trel_dnssd.cpp
- tests/mdns/main.cpp
This commit updates `TxtEntry`, `EncodeTxtData()`, and `DecodeTxtData()` to support boolean attributes, which are encoded as `key` string without the `=` character. It also ensures that `EncodeTxtData()` will generate valid TXT data (containing a single zero byte) when given an empty `TxtList`. Additionally, this commit updates `AdvertisingProxy::MakeTxtList()` to use `DecodeTxtData()`, and adds a test to validate the encoder and decoder behavior.
> [mdns] update 'TxtEntry'  to handle boolean attribute

- src/agent/CMakeLists.txt
- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/vendor.hpp
- src/ncp/ncp_openthread.hpp
This PR include two commits:
1. reverts https://github.com/openthread/ot-br-posix/pull/1967 as it breaks community use cases
2. Make VendorServer more generic to be used by multiple vendors. See https://github.com/openthread/ot-br-posix/pull/1967#issuecomment-1702407419
------
Prefer merging this PR as separate commits
> [utils] generic vendor server

- src/border_agent/border_agent.cpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- src/sdp_proxy/advertising_proxy.cpp
- src/sdp_proxy/advertising_proxy.hpp
- src/trel_dnssd/trel_dnssd.cpp
- src/trel_dnssd/trel_dnssd.hpp
- tests/mdns/main.cpp
This commit updates `Mdns::Publisher::PublishService()` to take encoded TXT data as its input, harmonizing the `Publish` API with the `Subscribe` API, which also uses encoded TXT data. This makes it easier to use with advertising proxy and TREL, avoiding the extra step of decoding already encoded TXT data to call `PublishService()`.
---
- ~This PR currently contains the commit from PR https://github.com/openthread/ot-br-posix/pull/1992.~ 
- ~Please check/review the second commit only.~
> [mdns] change `PublishService()` to get encoded TXT data as input

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This commit contains smaller changes in `Mdns::Publisher`:
- Use the already defined `AddressList` in methods
- Declare `OnCompleted()` method in `{Host/Service}Registeration` that is intended for use by the base class only as `private` instead of `public`
> [mdns] small enhancements

- src/mdns/mdns_mdnssd.cpp
This commit changes the `PublisherMDnsSd::PublishHostImpl` so that the allocated `DnssdHostRegistration` instance is tracked as a `std::unique_ptr`. This  ensures that the allocated instance is correctly freed if any steps after the allocation fail before we get to `AddHostRegistration()`.
> [mdns-mdnssd] ensure allocated `DnssdHostRegistration` is freed

- src/mdns/mdns.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/main.cpp
This commit updates the test to use "_meshcop._udp" as the service type (removing ending `.` char) as the service type should not end with dot character.
It also updates the documentation of `Mdns::Publisher` methods to indicate that the service type strings must not end with dot character.
> [tests] fix service type names used in `mdns/main` tests

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This commit updates `PublisherMDnsSd::Process()`, which processes ready `DNSServiceRef`s from the main run loop. We now track the list of ready service refs in a member variable, `mServiceRefsToProcess`.
As we iterate over the list of `mServiceRefsToProcess`, the call to `DNSServiceProcessResult()` can itself invoke callbacks into `PublisherMDnsSd` and OT, which in turn, may change the state of Publisher and potentially trigger a previously valid `ServiceRef` in the list to be deallocated.
This commit adds `HandleServiceRefDeallocating()`, which is called whenever a `ServiceRef` is being deallocated. From this method, we update the entry in the `mServiceRefsToProcess` list to `nullptr` to avoid calling `DNSServiceProcessResult()` on an already freed `ServiceRef`.
----
Related to …
> [mdns-mdnssd] handle deallocated `ServiceRef`s as processing run loop

- src/dbus/server/dbus_thread_object.cpp
- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
Change aPublisher to pointer type. If it is not NULL, populate the MDNS telemetry; otherwise do not populate MDNS telemetry. This helps to reduce thread_helper's dependency issue on border_agent aPublisher.
> [telemetry] refine telemetry calculation function's `aPublisher` type

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This commit updates the `Stop()` method to behave differently based on a `StopMode` input. If called from `DNSServiceProcessResult()` call where we get a `kDNSServiceErr_ServiceNotRunning` error, we need to restart the `Publisher` and should immediately de-allocate all `ServiceRefs`, including `mHostsRef`. Otherwise, during a `kNormalStop`, we first clear the `m{Host/Service}Registrations` lists before de-allocating the `mHostsRef`. This ensures that `mHostsRef` and all its related child `DNSRecordRef`s remain valid when `DnssdHostRegistration` destructor is called, which accesses and uses them to update the published AAAA (IPv6 address) records.
----
- ~This PR currently contains the commit from https://github.com/openthread/ot-br-posix/pull/2012.~
- ~Please check and review the second …
> [mdns-mdnssd] fix access of freed `mHostsRef` in `Stop()`

- tests/dbus/test_dbus_client.cpp
---
Should help address CI test failures in https://github.com/openthread/ot-br-posix/pull/2025
We have this line here in the test_dbus_client code:
```c++
    TEST_ASSERT(api->GetPreferredChannelMask(preferredChannelMask) == ClientError::ERROR_NONE);
    TEST_ASSERT(preferredChannelMask == 0x7fff800);
```
The value we expect is different from what we get as `134180864` or `0x7ff7000` in the CI runs (which I guess was changed as part of OpenThread PR https://github.com/openthread/openthread/pull/9391)
This PR removes the assert check so to unblock #2025. We can re-add the check later (if we want) once the OT commit is updated on `ot-br-posix` and have the commit from https://github.com/openthread/openthread/pull/9391.
> [tests] remove the assert on `preferredChannelMask` value

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This commit updates and enhances the `Mdns::PublisherMDnsSd` class, which implements the `Mdns::Publisher` interface using MDNSResponder as its underlying DNS-SD provider.
The following changes are made related to service registration:
- Registration simplified: The `PublishServiceImpl()` method is updated to allocate a `DnssdServiceRegistration` object first and add it to the list of registrations before asking it to register itself. This simplifies the code path for invoking the `ResultCallback` on success or failure (one path to handle all cases) and also makes it clear that the `DNSServiceRef` object is owned and managed by the `DnssdServiceRegistration` instance.
- The `HandleRegisterResult` callback passed to the MDNSResponder `DNSServiceRegister()` function is now defined and …
> [mdns-mdnssd] simplify service and host registrations

- src/mdns/mdns_avahi.cpp
Avahi provides a mechanism to integrate it to a `select()` style run loop where an implementation can provide an `AvahiWatch` and an `AvahiTimeout` structure along with a set of related APIs (as function pointers given to Avahi client) for it to allocate new watch/timeout entries or update or free them. A watch entry provides a set of events to watch for and expects its given callback to be invoked when the events occur. A timeout provides an abstraction for a timer.
This commit updates `AvahiPoller` (which integrates Avahi to run loop as a `MainloopProcessor`) to protect against situations where entries get freed or updated as Avahi callbacks are invoked from `AvahiPoller::Process()`.
When we invoke the callback for an `AvahiWatch` or `AvahiTimeout` the Avahi module can call any of APIs …
> [mdns-avahi] handle freed `AvahiWatch/Timeout` entries as processing run loop

- etc/cmake/options.cmake
- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/vendor.hpp
This allows VendorServer to visit application and all parts of application through Get API. This addresses the issues like: BorderAgent is not accessible from VendorServer.
> [agent] add application integration for VendorServer instead of NCP

- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
This commit updates the `Mdns::Publisher::DiscoveredHostInfo` struct to include the `mNetifIndex` field, which provides the network interface index for a discovered host. This information is already provided by the `DiscoveredInstanceInfo` struct for a discovered service instance.
Both Avahi and MDNSResponder implementations are updated to provide the `mNetifIndex` field.
> [mdns] report the network interface index for discovered host info

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
This commit updates how the `DiscoverCallback` are tracked in `Mdns::Publisher` and how the callbacks are invoked. In particular, the `mDiscoverCallbacks` list itself can get updated as the callbacks are invoked. The new code ensures that we can handle such a situation from both `OnServiceResolved()` or `OnHostResolved()`.
----
The `OnServiceResolved()` was updated in PR #1742 to handle if the list gets updated from callback. Similar situation can happen in `OnHostResolved()` and from host callbacks. This PR changes the model to handle both situations.
> [mdns] handle list change from `DiscoverCallback` (host or service)

- .github/workflows/docker.yml
- tests/scripts/check-docker
OpenThread has deprecated the configuration `OT_POSIX_CONFIG_RCP_BUS`. It causes build issues in https://github.com/openthread/ot-br-posix/issues/2060. This commit updates the github action test scripts to avoid using the configuration `OT_POSIX_CONFIG_RCP_BUS`. This commit also updates OpenThread to the lates to avoid the github action test issues.
> [github-actions] deprecate the configuration OT_POSIX_CONFIG_RCP_BUS

- src/utils/pskc.cpp
This commit addresses a potential buffer overflow vulnerability in the `Pskc::SetSalt` method.
Root Issue:
The `Pskc::SetSalt` method copies data into `mSalt` without sufficiently checking that the combined length of the data being copied (`saltPrefix`, `aExtPanId`, `aNetworkName`) doesn't exceed the size of `mSalt`. This leads to a stack buffer overflow, which may cause stack corruption, resulting in undefined behavior and potential security risks.
Fix:
1. Added a check to ensure that the total length of data to be copied into `mSalt` doesn't exceed its size.
2. Added a warning log if the network name is too long and needs to be truncated.
3. Utilized `std::min` to copy only as much of the network name as can fit into the remaining space in `mSalt`.
This ensures that no buffer overflow …
> [utils] fix buffer overflow in `Pskc::SetSalt`

- src/agent/CMakeLists.txt
OpenThread has moved the file `radio_spinel.cpp` to the new lib `openthread-radio-spinel` in https://github.com/openthread/openthread/pull/9530. This commit adds the lib `openthread-radio-spinel` to lib dependencies to avoid build errors.
> [build] add `openthread-radio-spinel` to lib dependencies

- src/trel_dnssd/trel_dnssd.cpp
This commit updates `TrelDnssd` to select the numerically smallest IPv6 address when a peer advertises multiple IPv6 addresses. This prioritizes globally-unique addresses (GUA) over unique-local addresses (ULA) with `fc00::/7` prefix, followed by link-local addresses (`fe80::/10`).
----
Should address https://github.com/openthread/ot-br-posix/issues/2116.
> [trel-dnssd] prioritize wider-scope IPv6 address of TREL peers

- src/dbus/server/introspect.xml
Fix the error calling `AddOnMeshPrefix` https://github.com/openthread/ot-br-posix/issues/2079#issuecomment-1833488124. The interface in `introspect.xml` has been out-of-sync for.
Verification: adding a prefix.
```
$ sudo gdbus call --system --dest io.openthread.BorderRouter.wpan0 --method=io.openthread.BorderRouter.AddOnMeshPrefix --object-path /io/openthread/BorderRouter/wpan0 "(([0xfd,0x11,0x12,0x13,0x13,0x14,0x15,0x16], 64),0x5343, 0x01, false,false,false,false,false,false,false,false,false)"
()
```
```
> netdata show
Prefixes:
fd11:1213:1314:1516::/64 high d800
Routes:
Services:
44970 01 1f000500000e10 s d800
Contexts:
fd11:1213:1314:1516::/64 1 c
Commissioning:
12688 - - -
Done
```
> [dbus] fix `introspect.xml` for `AddOnMeshPrefix()`

- src/dbus/common/dbus_message_helper.cpp
- src/dbus/common/dbus_message_helper.hpp
- src/dbus/common/dbus_message_helper_openthread.cpp
`dbus_message_iter_recurse` will crash when the DBUS message iterator is not pointing at a proper type (see https://github.com/openthread/ot-br-posix/issues/2079). Therefore we'd better check the data type before calling `dbus_message_iter_recurse`.
> [dbus] introduce `DbusMessageIterRecurse` that checks the type of data

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/CMakeLists.txt
- tests/mdns/test_subscribe.cpp
This PR covers following things:
- Previously we didn't handle the removal of addresses properly when resolving a host/service. This causes an issue that when there's an ongoing browse of a specific service type (`_trel._udp`, for example), the callback of `OnServiceResolved` will also give stale addresses of the resolved host.
- In mDNSResponder implementation, we used a flag `kDNSServiceFlagsTimeout` which prevents from doing an ongoing service instance resolution. I removed this flag so that it does an ongoing resolution. The new behavior aligns better with the `Mdns::Publisher`'s API definition.
- In mDNSResponder implementation, don't remove the service instance resolution after an address is resolved. This allows the implementation to return multiple addresses.
- Added a unit test …
> [mdns] fixes of mDNS subscriptions

- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
Add the counters of queries, responses, failures handled by upstream DNS server
> [telemetry] add protobuf for upstream DNS metrics

- src/common/types.hpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
- tests/mdns/main.cpp
This commit adds new methods in `Mdns::Publisher` to publish or unpublish a key record for a given (host or service instance) name. New methods are implemented for both MDNSResponder and Avahi sub-classes.
In the MDNSResponder implementation, if a key registration is for a service instance name matching a service registration,
`DNSServiceAddRecord()` is used to associate the new record with the service. Otherwise, `DNSServiceRegisterRecord()` is used to register the KEY record on its own. The implementation handles cases when related service and key registrations are updated or unregistered.
This commit also simplifies and updates the `test/mdns/main.cpp` tests, adding a common `Test()` function that takes a function pointer to run the test and handles all common boilerplate code, as well …
> [mdns] add `PublishKey()` & `UnpublishKey()` methods

- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
Add upstream query state 
Need to use both upstream query state and srp server state to indicate the upstream server state
- SRP Server Disabled
- SRP Server Enabled, Upstream DNS forwarding disabled
- SRP Server Enabled, Upstream DNS forwarding enabled.
> [telemetry] add upstream dns query state

- src/proto/CMakeLists.txt
Protobuf which higher than 22 need link absl. Add the linked shared library to pass the build.
> [dbus] add absl support for higher version protobuf

- .github/workflows/macOS.yml
- src/agent/application.cpp
- src/agent/application.hpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/sdp_proxy/advertising_proxy.cpp
- src/sdp_proxy/advertising_proxy.hpp
- src/sdp_proxy/discovery_proxy.cpp
- src/sdp_proxy/discovery_proxy.hpp
- src/trel_dnssd/trel_dnssd.cpp
- src/trel_dnssd/trel_dnssd.hpp
`BorderAgent` class currently contains mDNS Publisher, Advertising Proxy, Discovery Proxy and TrelDnssd. Actually these contained components should be controlled by `Application` instead of `BorderAgent`. Then these components can be fetched by vendor server from `Application`. This PR also unifies the public methods of these components a bit.
> [border-agent] decouple `BorderAgent` class from irrelevant responsibilities 

- src/openwrt/ubus/otubus.cpp
To address changes in https://github.com/openthread/openthread/pull/9866
> [openwrt] remove usage of `OT_NETWORK_DIAGNOSTIC_TYPELIST_MAX_ENTRIES`

- src/mdns/mdns_mdnssd.cpp
This commit updates `UnsubscribeService/Host()` to allow them to be called with service or host name that may not be present in the list. This situation may happen if duplicate queries are received for the same names.
---
- Suggested fix for https://github.com/openthread/ot-br-posix/issues/2203.
> [mdns] allow `UnsubscribeService/Host()` to remove non-present entries

- src/sdp_proxy/discovery_proxy.cpp
Remove the `assert` checks on query name parse errors and instead skip over such entries. Query names are external input (received as DNS query message from other devices) and discovery proxy code should not assume that external input will follow the proper query name format.
---
- Suggested fix for https://github.com/openthread/ot-br-posix/issues/2207
> [discovery-proxy] remove `assert` checks on query name parse errors

- src/mdns/mdns_avahi.cpp
This commit adds a similar change to #2206 but for Avahi example. It updates `UnsubscribeService/Host()` to allow them to be called with service or host name that may not be present in the list. This situation may happen if duplicate queries are received for the same names.
> [mdns-avahi] allow `UnsubscribeService/Host()` to remove non-present entries

- src/agent/main.cpp
- src/common/logging.cpp
- src/common/logging.hpp
- src/web/main.cpp
- tests/mdns/main.cpp
- tests/mdns/test_subscribe.cpp
- tests/unit/test_logging.cpp
Adds an optional flag to otbr-agent to allow disabling of logging to syslog.
Current behavior has logs sent to both standard output as well as the file indicated by syslog. With this flag enabled, logs would only be sent to standard output.
> [logging] add command line arg to disable syslog

- src/mdns/mdns_avahi.cpp
This change avoids `assert(false)` on `AvahiEntryGroupState` and `AvahiClientState` `switch` statements. This prevents potential crashes if Avahi introduces new states in future versions.
> [mdns-avahi] handle potential unknown Avahi states gracefully

- src/ncp/ncp_openthread.cpp
This is to avoid having stale/undesired handlers when calling `ControllerOpenThread::Init()`.
> [ncp] clear handlers and callbacks in `ControllerOpenThread::Deinit()`

- src/agent/application.cpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/common/types.hpp
Existing implementation will publish the _meshcop._udp service
immediately when the program is started, even when there is no
provisioned Thread network. This works as expected as the Thread spec
defines.
The problem is that for non-Android linux platforms, the vendor,
product name are customized via build time flags but customization needs
to be runtime for Android because all Android device shares the same
Thread stack in the mainline module.
To support Android, we make updates to allow delaying the advertisement
of _meshcop._udp service after the customized vendor/product name has
been provided via the new "OTBR_STOP_BORDER_AGENT_ON_INIT" build flag
and the "BorderAgent::SetMeshcopServiceValues()" method.
Check https://android-review.git.corp.google.com/c/platform/packages/modules/Conne …
> [meshcop] support runtime custom vendor and product name

- src/border_agent/border_agent.cpp
This PR lets the `BorderAgent` register the Thread state callback in the constructor instead of `Start()` so that it won't register a new callback every time it starts.
> [border-agent] remove duplicate callback registrations

- etc/docker/Dockerfile
This is used for reserving a UDP port on thread network interface.
> [continuous-integration] install `socat` for docker-based BR tests

- etc/cmake/options.cmake
- src/border_agent/border_agent.cpp
A BA at all times set the ePSKc Support flag (bit 11) in the State Bitmap (sb) TXT record of its MeshCoP DNS-SD service to '1' if the OTBR_EPSKC_ENABLE = ON;
Test: mDNS package capture - sb value changes to "00 00 08 21" from original value "00 00 00 21"
> [border-agent] update State Bitmap for ePSKc capability

- src/ncp/ncp_openthread.cpp
- src/proto/feature_flag.proto
The PR adds a feature flag to control the link metrics manager.
> [feature-flag] add a feature flag to control link metrics manager

- src/web/web-service/web_server.cpp
boost::filesystem::extension() is deprecated in new boost versions
> [build] fix on macOS

- src/backbone_router/backbone_agent.cpp
- src/backbone_router/backbone_agent.hpp
Flag `OTBR_ENABLE_BACKBONE_ROUTER_ON_INIT` is created for enabling BBR on init. It's set to OTBR_ENABLE_BACKBONE_ROUTER by default and this works when infra link is statically configured. If infra link is dynamically configured then this flag should be set to 0, the component that sets infra link should enable/disable BBR feature with the otBackboneRouterSetEnabled API.
> [bbr] add a flag to enable BBR on init

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
Meshcop-e service is published when receiving DNS query for PTR records and BA is in the "ba ephemeralkey" active mode with the same instance name with Meshcop service and different UDP port number for the DTLS connection using ePSKc.
Test:
1. Active ePSKc mode using "ba ephemeralkey" commands, verified Meshcop-e package and service
2. DTLS connection could successfully set using ePSKc mode with Candidate Commissioner.
3. DTLS connection using ePSKc by inputing wrong ePSK in Candidate Commissioner, Meshcop-e service has been unpublished and no negative impacted with Meshcop service.
4. Meshcop-e service unpublished after timeout.
> [border-agent] add `_meshcop-e` service for ePSKc mode

- script/bootstrap
- script/server
Ensure the Avahi daemon is installed and started only when OTBR_MDNS == "avahi". This prevents multiple mDNS stacks from running especially in container environments.
I saw in the CONTRIBUTING documentation that CI checks should pass but I'm not sure how to get them to run in my fork.
Fixes #2280
> [avahi] conditionalize Avahi Service Start and Installation (#2280)

- third_party/openthread/mbedtls-config.h
This commit removes configuration sanity check for MbedTLS versions higher or equal to 3.0.0.
This is a follow-up after https://github.com/openthread/openthread/pull/10263 and needed to migrate to Mbed TLS 3.6.0.
> [mbedtls] stop checking configuration explicitly

- src/agent/application.cpp
- src/agent/application.hpp
This PR refactors the constructor of the `Application` class so that
the initialization could be flexible.
This PR is a replacement of #2299 and a child PR of #2283. With this
change, we can choose to **not** initialize other submodules when
the co-processor is an NCP.
> [application] refactor constructor to allow flexible initialization

- src/common/types.cpp
- src/common/types.hpp
- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
- tests/dbus/test_dbus_client.cpp
- tests/unit/CMakeLists.txt
- tests/unit/test_common_types.cpp
This commit added new entry `ExternalRoutes` inside message `wpan_border_router` to indicate the information about the external route added in leader network data
The `ExternalRoutes` has three bool fields:
- `has_default_route_added`: if leader network data has `route ::/0`
- `has_ula_route_added`: if leader network data has route `fc00::/7`
- `has_others_route_added`: if leader network has others route
These information are collectly only when both TELEMETRY_DATA_API and BORDER_ROUTING are enabled.
This commit also enhanced the class `otbr::Ip6Address` and class `otbr::Ip6Prefix` by adding some more constructors, so that the ipv6 address/prefix can be easily constructed by a string. The `operator==` of `Ip6Prefix` is also added to compare the prefix length and first N-bit of the prefix, …
> [telemetry] add external route related telemetry

- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_controller.hpp
This PR defines the Thread Controller Interface which is intended to
provide a set of unified, async thread control APIs for both NCP and
RCP cases.
This PR is a child PR of #2283. In this PR, only `GetDeviceRole` is
added. `HostRcp` implemented the interface and the dbus handler is
updated to directly call this unified API.
> [controller] add Thread controller interface for unified APIs

- tests/dbus/test_dbus_client.cpp
Router ID is in range [0, MAX_ROUTER_ID] therefore zero is a valid RLOC16. The test case was wrongly checking if the RLOC16 is greater than zero.
An example failure: https://github.com/openthread/ot-br-posix/actions/runs/9361612569/job/25768930225?pr=2312.
> [tests] fix the telemetry test for verifying the RLOC16

- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
- tests/dbus/test_dbus_client.cpp
This PR refactors the telemetry code processing PD info to achieve two goals:
- Handle the error when calling OT API. Previously the issue was ignored which may cause uploading wrong data.
- Introduce helper methods for processing PD info.
- Fix the D-BUS unit test and check more fields.
> [telemetry] fix and refactor the PD processing

- src/ncp/rcp_host.cpp
This PR updates the usage of `otPlatformConfig` as the definition is changed in openthread/openthread#10344.
This PR also bumps [third_party/openthread/repo](https://github.com/openthread/openthread) from d6eb56c to cdeb02b
> [controller] update the usage of otPlatformConfig

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
See also https://android-review.git.corp.google.com/c/platform/external/ot-br-posix/+/3111060
for how this change is used and tested.
> [meshcop] support non-standard TXT entries at runtime

- src/agent/CMakeLists.txt
- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/common/code_utils.hpp
- src/ncp/CMakeLists.txt
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_controller.cpp
- src/ncp/thread_controller.hpp
This PR is also a breakdown of #2283 
This PR adds a factory method `CreateInstance` to provide polymorphism
for the `ThreadController`. This PR moves the construction and initialization
of the components to RCP specific methods and only contructs these
modules when the Co-processor is an RCP.
> [controller] allows polymorphism of the controller

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
- src/ncp/CMakeLists.txt
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.cpp
- src/ncp/thread_host.hpp
This PR renames `ThreadController` to `ThreadHost`.
As discussed in #2329, since the implementation class are called
as `RcpHost` and `NcpHost`, the interface name should also be named
as 'Host'.
> [controller] rename to ThreadController to ThreadHost

- src/agent/main.cpp
Current code uses `__ANDROID__` for determine the Android platform while that flag
is also available on android-based but non-aosp devices. To avoid misconfiguration,
this commit uses `OTBR_ENABLE_PLATFORM_ANDROID` for selecting the standard
Android devices.
> [android] use OTBR_ENABLE_PLATFORM_ANDROID for android platform

- etc/docker/docker_entrypoint.sh
Passing OTBR_OPTIONS=-DOT_LOG_LEVEL=INFO does not actually change the debug level as expected. Instead a -d command line option is required.
The current docker_entrypoint.sh file hard codes -d7 (Debug level) on the command line.
This PR changes the hard coded value to a ```--debug-level``` command line argument like the existing ```--radio_url```, ```--interface``` options.
This allows setting the debug level in the docker-compose file.
Closes #2323
> [docker] add ability to set debug-level

- .github/workflows/ncp_mode.yml
- script/test
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/thread_host.cpp
- tests/scripts/expect/ncp_version.exp
- tests/scripts/ncp_mode
This PR adds the `NcpHost` class which is the implementation of
`ThreadController` under NCP case.
This PR updates `ThreadController::Create` to create `NcpHost` under
the NCP case, allowing `otbr-agent` to start when the co-processor is
a NCP, though no functionalities have been implemented yet.
This PR also adds a CI workflow to use expect script to test otbr-agent
in NCP case. For this PR, a simple test is added to start otbr-agent
with NCP (dry run) and check the co-processor version.
This PR is a subset of PR https://github.com/openthread/ot-br-posix/pull/2283
> [controller] add ncp host

- .github/workflows/ncp_mode.yml
- tests/scripts/expect/ncp_version.exp
- tests/scripts/ncp_mode
This PR fixes the expect test. Currently even the expect script fails, the exit_code is still 0 in `test_teardown`. And the CI won't fail.
> [tests] fix expect test

- src/agent/application.cpp
- src/agent/application.hpp
- src/common/types.cpp
- src/common/types.hpp
- src/dbus/server/CMakeLists.txt
- src/dbus/server/dbus_agent.cpp
- src/dbus/server/dbus_agent.hpp
- src/dbus/server/dbus_object.cpp
- src/dbus/server/dbus_object.hpp
- src/dbus/server/dbus_thread_object_ncp.cpp
- src/dbus/server/dbus_thread_object_ncp.hpp
- src/dbus/server/dbus_thread_object_rcp.cpp
- src/dbus/server/dbus_thread_object_rcp.hpp
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.cpp
- src/ncp/thread_host.hpp
- src/sdp_proxy/advertising_proxy.cpp
- tests/scripts/expect/ncp_get_device_role.exp
- tests/scripts/ncp_mode
This PR refactors the `DBusAgent` so that it can work under NCP mode.
The DBus server will provide different methods under RCP mode and NCP mode. Currently under NCP mode, only `GetDeviceRole` is provided.
This PR renames `DBusThreadObject` to `DBusThreadObjectRcp` and added a new class `DBusThreadObjectNcp` which will handle the DBus requests under NCP mode. This PR also implements `AsyncPropertyHandler` to handle GetProperty requests by calling async methods of `NcpHost`.
A test case is added to test `GetDeviceRole` under NCP.
This PR is also a breakdown of PR #2283.
> [ncp] implement dbus server for NCP mode

- src/ncp/CMakeLists.txt
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/rcp_host.cpp
- tests/scripts/expect/ncp_get_device_role.exp
This PR implements NcpSpinel for the host to interact with the host.
In this PR, the first method `GetDeviceRole` is implemented and used
in NcpHost to get the device role.
> [ncp] add ncp spinel and implement GetDeviceRole

- src/agent/CMakeLists.txt
This commit fixes the following warnings:
```bash
CMake Warning (dev) at src/agent/CMakeLists.txt:36
(target_link_libraries):
Policy CMP0079 is not set: target_link_libraries allows use with
targets in
other directories.  Run "cmake --help-policy CMP0079" for policy
details.
Use the cmake_policy command to set the policy and suppress this
warning.
Target
openthread-radio-spinel
is not created in this directory.  For compatibility with older
versions of
CMake, link library
openthread-spinel-rcp
will be looked up in the directory in which the target was created
rather
than in this calling directory.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> [cmake] fix cmake warnings

- tests/scripts/expect/_common.exp
- tests/scripts/expect/ncp_get_device_role.exp
- tests/scripts/ncp_mode
This PR enhances the expect test framework for testing NCP mode:
1. Add util methods to simplify the tests
2. Allow the bash script to run specific test for easier local testing
3. Build ot-cli node and allow create CLI node in the tests
> [tests] enhance expect test framework for ncp_mode

- .github/workflows/ncp_mode.yml
- script/test
This PR updates the build directory of otbr-agent in ncp_mode CI tests to a different path. This allows us to build a docker image from the same repo later. Currently if we build otbr-agent in default path and then we build a docker image, it will find existing cmake cache and report an error. 
Building docker image is to test border routing features of NCP in simulation environmrnt.
> [github-actions] update the build directory for otbr-agent

- src/agent/application.cpp
Vendor server's constructor may depend on members of Application that are created inside CreateRcpMode(), moving VendorServer creation to end of CreateRcpMode() to avoid dereference of null pointers.
> [utils] move VendorServer creation to CreateRcpMode()

- .github/workflows/meshcop.yml
- .github/workflows/ncp_mode.yml
This PR fixes the code coverage issue in github actions in `ncp_mode` and `meshcop`. The option `OTBR_COVERAGE` is not enabled when building so no coverage data can be found and uploaded.
> [github-actions] fix code coverage of ncp mode CI

- .github/workflows/border_router.yml
The OTBR testing artifacts used to be at `third_party/openthread/repo/` but they are now at `third_party/openthread/repo/ot_testing/`
> [continuous-integration] fix the path for uploading artifacts when BR test fails

- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
- tests/dbus/test_dbus_client.cpp
`peer_br_count` is the number of border routers retrieved from network data.
> [telemetry] add `peer_br_count` in WpanTopoFull

- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
- tests/dbus/test_dbus_client.cpp
- Add new field `peer_br_count` which is the total number of peer border routers on the same infra link
- Also move all InfraLinkInfo section into a new function `RetrieveInfraLinkInfo()`
> [telemetry] add `peer_br_count` in InfraLinkInfo

- src/dbus/common/types.hpp
There are no other `u_int16_t` occurrences in the entire repository, and this is indeed undefined.
> [dbus] fix `u_int16_t` typo

- script/clang-format
Homebrew installation of clang-format (satisfying >14.0 requirement) outputs the following version string:
```
Homebrew clang-format version 14.0.6
```
This change fixes the following error while running make-pretty:
```
*** ERROR: Homebrew clang-format version 14.0.6; clang-format 14.0 required
```
-----------------------
Similar PR made on [openthread](https://github.com/openthread/openthread/pull/10042) before
> [clang-format] accept different patch versions of `clang-format`

- src/ncp/ncp_spinel.cpp
Fix an issue in `ncp_spinel.cpp` related to a dummy va_list variable being uninitialized. It causes problems with certain architectures and compiler flags, and initializing it using va_start doesn't work since it's not in a variadic function.
> [ncp] fix a compilation issue in `ncp_spinel.cpp`

- src/border_agent/border_agent.cpp
- src/dbus/server/dbus_thread_object_ncp.cpp
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
- src/utils/thread_helper.cpp
This PR adds a new interface `NetworkProperties` to provide a unified, synchronized way to access network properties for both NCP and RCP.
* For RCP, the property getters are implemented by OT APIs with an OT instance.
* For NCP, the property getters are implemented by the replica of the data that comes from NCP.
This is important for adding NCP support because in some cases the network properties are required by some functionality and we don't want to make an asynchronous call simply to get the property. As one example, in AdvertisingProxy, we need to the MeshLocal Prefix to check if an address is mesh local address. Currently this is done by OT API, which is not available under NCP mode. However, the information is contained in the active dataset and NCP will always notify the host …
> [host] add network properties class

- script/test
- src/ncp/posix/CMakeLists.txt
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- src/ncp/posix/netif_linux.cpp
- src/ncp/posix/netif_unix.cpp
- tests/gtest/CMakeLists.txt
- tests/gtest/test_netif.cpp
This PR adds a posix platform module for NCP mode. Under NCP mode, the platform operation won't depend OT posix platform implementation and will use the posix platform implementation added in this PR instead.
This PR only adds the netif module and support creating the Thread network interface (wpan0) and setting the MTU. The other functionalities will be added in following PRs. The netif module hasn't been integrated with the NcpHost. In this PR, the posix platform is added as a library and has its own unit test (also implemented by gtest).
The netif implementations are different on different platforms: linux, apple, bsd... This PR only implements it on linux and adds an empty implementation for other posix platforms.
> [posix] add posix netif module

- src/ncp/rcp_host.cpp
`TXT: tv=1.4.0` is expected as in Table 8-4
> [version] update 1.4 to 1.4.0 for conformance

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
This PR updates the general logic of the handling of incoming spinel frames in NcpSpinel.
Currently the dispatching depends on the incoming key (what we actually received), which brings some implementation troubles. For example, the response of a get command and a set command could sometimes be the same thing: the property.
In this PR, we use `mCmdTable` together with `mWaitingKeyTable` to record each sent command and do the handling based on `mCmdTable[tid]` and `mWaitingKeyTable[tid]` (what we expect to receive). This makes it much easier to further add more handlings later.
> [ncp] update the frame handling of ncp spinel

- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- src/ncp/posix/netif_linux.cpp
- src/ncp/posix/netif_unix.cpp
- tests/gtest/test_netif.cpp
This PR sets the addr gen mode of wpan interface to NONE on linux.
This PR depends on https://github.com/openthread/ot-br-posix/pull/2410. #2410 needs to be merged first.
> [posix] set addr gen mode to none on linux 

- src/common/types.cpp
- src/common/types.hpp
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- src/ncp/posix/netif_linux.cpp
- src/ncp/posix/netif_unix.cpp
- tests/gtest/test_netif.cpp
This PR implements `UpdateIp6UnicastAddresses` method for `Posix::Netif` module to add/remove unicast address on the wpan interface. A unit test is added together.
The method `UpdateIp6UnicastAddresses` takes a vector of Ip6 addresses as input (because the address update from the NCP is the entire address table) and update the entire address list to the interface. However, it doesn't do it by removing all and then adding all. Instead, it compares the existing unicast addresses against the new addresses to decide which addresses to add/remove and then issue netlink requests to do the changes.
> [posix] add unicast address update in netif module

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
This PR resolves the remaining issue as [discussed](https://github.com/openthread/ot-br-posix/pull/2355#discussion_r1699198730) in https://github.com/openthread/ot-br-posix/pull/2355 
This PR updates the implementation of `NcpSpinel::DatasetSetActiveTlvs` to use the new spinel property `SPINEL_PROP_THREAD_ACTIVE_DATASET_TLVS` to set the active dataset on NCP. In this way, the dataset is transported as TLVs instead of a structure.
> [ncp] update implementation of NcpSpinel DatasetSetActiveTlvs

- tests/scripts/ncp_mode
This PR enhances the ncp_mode test script to run all the expect test script under a directory to avoid we need to add a new entry here when there is a new test.
> [tests] enhance the ncp mode test script

- src/border_agent/border_agent.cpp
Depends-On: openthread/openthread#10596
> [epskc] enable by default for Thread 1.4

- src/dbus/server/dbus_thread_object_ncp.cpp
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
- tests/scripts/expect/ncp_schedule_migration.exp
- tests/scripts/expect/ncp_test_schedule_migration_dbus_api.exp
This PR adds the `ScheduleMigration` API to `ThreadHost` as well as the implementation for NcpHost.
The PR also replaces the empty implementation in DBusNcp with the real implementation by calling the API. The PR adds an expect test to verify the result of a migration.
> [controller] add schedule migration API

- src/common/types.hpp
- src/ncp/CMakeLists.txt
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- src/ncp/posix/netif_unix.cpp
- tests/gtest/test_netif.cpp
- tests/scripts/expect/ncp_netif_address_update.exp
This PR integrates the Netif module with the `NcpHost` so that the unicast address table received from NCP will be updated to the network interface.
The PR adds a expect test to verify the addresses are added/removed correctly.
> [ncp] integrate netif unicast address update

- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- tests/gtest/test_netif.cpp
This PR addes multicast addresses update method of `Netif` module.
This PR contains a small unit test case to verify the implementation.
> [posix] add multicast address update in netif module

- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- tests/gtest/test_netif.cpp
This PR adds the SetState for Netif module to set the interface ON/OFF.
In this PR this hasn't been integrated with NCP yet. (After receiving NCP property update, the state of wpan interface changed accordingly). This will be done later.
> [posix] add netif SetState

- src/ncp/ncp_host.cpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- tests/scripts/expect/ncp_netif_address_update.exp
This PR integrates the `Netif::SetNetifState` with `NcpSpinel` so that when the netif state on NCP changes, the wpan state on the host updates accordingly.
> [ncp] integrate netif isUp state update

- src/ncp/ncp_host.cpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- tests/scripts/expect/ncp_netif_address_update.exp
This PR integrates `Netif` multicast address update with `NcpSpinel` so that wpan will join the multicast group that NCP joins.
> [ncp] integrate netif multicast address update

- src/proto/thread_telemetry.proto
- src/utils/thread_helper.cpp
- tests/dbus/test_dbus_client.cpp
The epskc_state and border_agent_state has no clear metrics, remove from uploading.
> [telemetry] remove uploading epskc_state and border_agent_state

- src/common/types.hpp
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- tests/gtest/test_netif.cpp
This PR implements netif TUN Ip6 receiving.
When netif module receives an Ip6 packet, it will pass it to the system network stack through wpan interface. The PR also adds a unit test to verify an application can receive UDP packets from wpan through netif.
This PR hasn't integrated Ip6 receiving with NCP(forward the packet from NCP to the system network stack). This will be done in future PRs.
> [posix] add netif TUN Ip6Receive

- src/backbone_router/nd_proxy.cpp
- src/common/mainloop.cpp
- src/common/mainloop.hpp
- src/common/task_runner.cpp
- src/dbus/server/dbus_agent.cpp
- src/mdns/mdns_mdnssd.cpp
- src/ncp/posix/netif.cpp
- src/openwrt/ubus/otubus.cpp
- src/rest/rest_web_server.cpp
- src/utils/infra_link_selector.cpp
This PR adds methods to `MainloopContext` to encapsulate the process to add an fd to some fd sets of it and update the maxFd. This simplifies the implementation. Previous [discussion](https://github.com/openthread/ot-br-posix/pull/2452#discussion_r1739337131) for this change.
> [application] simplify fdset update

- src/ncp/ncp_host.cpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- tests/scripts/expect/_common.exp
- tests/scripts/expect/ncp_netif_tx_rx.exp
This PR integrates the Netif TX/RX functionality with NCP spinel.
This PR enables bidirectional IP packet exchange between the wpan interface and NCP. This PR adds a ping test to verify the connectivity.
The PR depends on #2452.
> [ncp] integrate Netif TX/RX with Ncp

- src/ncp/ncp_host.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- tests/gtest/test_netif.cpp
This PR does a small refactoring for `Netif` and `NcpSpinel`.
`Netif::Ip6Send` depends on the implementation of `NcpSpinel`. And there are more methods to come. (For example, `SubcribeMulticastAddress`). Currently we pass the Ip6Send implementation to `Netif` in `Netif::Init` through a std::function object. But then, each time we add a new method, we need to update the signature of `Netif::Init`(making it very long) and the calling of `Netif::Init`, which is not preferred. This PR adds a dependencies class `NetifDependencies` to encapsulate all the implementation functions for Netif and let `NcpSpinel` implement this interface.
> [netif] refactor Netif and NcpSpinel

- src/ncp/ncp_spinel.cpp
This PR fixes a tiny issue in NcpSpinel log.
Currently the logging for `HandleNotification` is:
```
otbr-agent[876792]: [INFO]-NcpSpin-: HandleNotification: HandleNotification: OK 
```
The PR removes the redundant function name.
> [log] fix ncp spinel log

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/posix/netif.cpp
- src/ncp/posix/netif.hpp
- tests/gtest/test_netif.cpp
This PR adds wpan multicast group join functionality for NCP.
This PR allows the applications to join/leave multicast groups in the Thread network. The functionality is implemented by listening to MLD reports sent by kernel. And then the Netif module will send the join/leave request to the NCP and let NCP join/leave the multicast group. Previous work on this in OT: https://github.com/openthread/openthread/pull/4687
In this PR, `NcpSpinel::Ip6MulAddrUpdateSubscription` is implemented as empty. This will be implemented in a following PR. This PR adds a unit test case to verify that the MLD reports can be successfully received and handled.
> [netif] add wpan multicast group join for NCP

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/posix/netif.cpp
This PR integrates the netif multicast address subscirption update with the NCP.
With this PR, applications can listen to a multicast address on wpan interface and receive multicast messages from the Thread network.
The implementation of `NcpSpinel::Ip6MulAddrUpdateSubscription` uses `SPINEL_CMD_PROP_VALUE_INSERT` and REMOVE. This PR extends NcpSpinel to support using these commands.
It's a little hard to add an integration test for this. Because there isn't any native tools to easily listen on a multicast address and check what has received. I've verified it locally with a simple c++ program.
> [ncp] integrate netif multicast address subscription

- script/bootstrap
1.4 certification testing requires some throughput testing as part of test case 7.1 BR TCP throughput performance
> [bootstrap] install iperf3 for reference devices

- src/web/main.cpp
Commit c88a5fce6659 ("[logging] add command line arg to disable syslog") allows to disable logging to syslog via command line argument. Support the same -s command line argument for otbr-web as well.
> [logging] support disable syslog for otbr-web as well

- etc/docker/docker_entrypoint.sh
- tests/scripts/check-docker
This commit adds an environment variable to specify the otbr-web port in docker, so that it can avoid port conflict with other services in host network mode.
> [docker] add environment variable for HTTP server

- src/ncp/posix/CMakeLists.txt
- src/ncp/posix/infra_if.cpp
- src/ncp/posix/infra_if.hpp
- tests/gtest/CMakeLists.txt
- tests/gtest/test_infra_if.cpp
This PR adds the InfraIf module on the host side.
This is to support border routing for NCP case. See this https://github.com/openthread/ot-br-posix/issues/2398#issuecomment-2348518919 for the whole picture of this series of changes.
In this PR, `InfraIf` module only implements `SetInfraIf` method. This method is intended to be called by `NcpHost` during initialization or through ThreadHost API (for example, for the android case, where the infra if is ready later). This method will initialize the infra if and the border routing module on NCP.
This PR adds a unit test to verify the `InfraIfDependency` is called correctly.
> [infra if] add platform infra if module

- script/_initrc
This fixes an issue where the `otbr-agent` would not be properly stopped when the container receives SIGTERM (e.g. `docker stop otbr`).
In such scenarios, the agent would not be able to use dbus upon restart and the service would be in a broken state. This happens on container restart, docker service restart, host reboot, etc.
> [docker] fix access to DBus when restarting container / rebooting host

- src/ncp/posix/infra_if.cpp
- src/ncp/posix/infra_if.hpp
- tests/gtest/test_infra_if.cpp
This PR implements Infra If state update in the InfraIf module.
This PR enables the `InfraIf` module to listen to the state change of the infrastructure interface and then notify the change to the NCP. This is achieved by listening to netlink events. The implementation is basically the same as OT posix InfraIf.
This PR adds a unit test case to verify `InfraIfDependency::SetInfraIf` is called correctly when the InfraIf state changes.
> [infra if] implement infra if state update

- tests/dbus/test-client
This commit increases the reply timeout for AttachToAllNodes due to the increased leader restore timeout.
> [test] increase reply timeout for AttachToAllNodes

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds a new method `SetThreadEnabled` as a ThreadHost API.
The method is added so that the Android binder API can be easily implemented without the need to handle NCP/RCP case. In this PR, `RcpHost::SetThreadEnabled` is impelmented and `NcpHost::SetThreadEnabled` will be implemented later.
> [host] add SetThreadEnabled to ThreadHost APIs

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds active dataset tlvs to `NetworkProperties` so that for both NCP and RCP active dataset can be accessed directly.
The active dataset is used in many places in the platform code. For example, in android `SetThreadEnabled`, it will only enable Thread when the active dataset is a valid one.
I verified the NCP case locally by log (dumping the active set and see if it's correctly set). If writing a test for it, we need add one more dbus API, which seems unworthy now.
> [host] add active dataset as a network property

- src/ncp/posix/infra_if.cpp
- src/ncp/posix/infra_if.hpp
This PR implements `SendIcmp6Nd` in the `InfraIf` module.
The method is used to send an ICMPv6 ND message (on host) when NCP calls `otPlatInfraIfSendIcmp6Nd`. In this PR, the method hasn't been called. It will be later integrated with `NcpSpinel`. The implementation of this method is the same as OT posix [implementation](https://github.com/openthread/openthread/blob/main/src/posix/platform/infra_if.cpp#L214).
> [infra if] implement infra if send icmp6 nd

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds the `SetCountryCode` method to `ThreadHost`.
The PR implements this method for `RcpHost`. The implementation for NCP will be added later.
> [thread-host] add set country code api

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds the GetChannelMask method to ThreadHost.
The PR implements this method for RcpHost. The implementation for NCP will be added later.
> [thread-host] add get channel mask

- CMakeLists.txt
- src/agent/CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/logging.cpp
- src/common/logging.hpp
- src/ncp/thread_host.cpp
- src/ncp/thread_host.hpp
- tests/gtest/CMakeLists.txt
- tests/gtest/fake_posix_platform.cpp
- tests/gtest/test_rcp_host_api.cpp
This PR adds a unit test framework for testing ThreadHost APIs (RCP).
It's implemeneted by building `rcp_host.cpp` with `FakePlatform` in OT. A few small changes are done to make this work:
* implement openthread posix system APIs in  `fake_posix_platform.cpp`. (like `otSysInit`, `otSysMainloopProcess `) `ot::FakePlatform` doesn't include these things and I think it's better to put it here.
* Remove the fixed build dependency of `otbr-common` on `openthread-posix` so that the unit test executable can link to the fake system API implementation instead those in `openthread-posix`.
* Move `ThreadHost::ConvertToOtLogLevel` to `logging.hpp`. Because otherwise we have to build `thread_host.cpp` into the test executable and then have more dependencies on NcpHost.
This PR also implements the …
> [test] add unit test framework for ThreadHost APIs (RCP)

- src/ncp/posix/infra_if.cpp
- src/ncp/posix/infra_if.hpp
- tests/gtest/test_infra_if.cpp
This PR implements Icmp6Nd receiving in the InfraIf module.
The method is used to receive ICMPv6 ND messages (on host) and forward them to the NCP. The implementation of this method is the same as OT posix [implementation](https://github.com/openthread/openthread/blob/main/src/posix/platform/infra_if.cpp#L593). In this PR, the forwarding to NCP hasn't been implemented. It will be later integrated with NcpSpinel. 
This PR also adds a test case to verify that `HandleIcmp6Nd` is called correctly when the infrastructure interface receives an ICMP6 ND message.
> [infra if] add infra if icmp6 nd receiving

- src/agent/application.cpp
- src/agent/application.hpp
- src/border_agent/border_agent.hpp
- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/sdp_proxy/advertising_proxy.hpp
- src/sdp_proxy/discovery_proxy.hpp
- src/trel_dnssd/trel_dnssd.hpp
This PR refactors the mDNS State subscription using the Subject-Observer pattern.
The PR makes the state subscription more flexible. Currently the mDNS state is published in `Application::HandleMdnsState`. Now we have both NCP and RCP case. This function will be difficult to implement. With this new pattern, we can register different observers during NCP/RCP initialization.
> [mdns] refactor mDNS State subscription

- src/agent/main.cpp
This PR expands on the existing `--help` text by including short and long option names when available, and by adding options that were missing.
The current `--help` text is now:
```
Usage: ./otbr-agent [-I interfaceName] [-B backboneIfName] [-d DEBUG_LEVEL] [-v] [-s] [--auto-attach[=0/1]] RADIO_URL [RADIO_URL]
-I, --thread-ifname    Name of the Thread network interface (default: wpan0).
-B, --backbone-ifname  Name of the backbone network interfaces (can be specified multiple times).
-d, --debug-level      The log level (EMERG=0, ALERT=1, CRIT=2, ERR=3, WARNING=4, NOTICE=5, INFO=6, DEBUG=7).
-v, --verbose          Enable verbose logging.
-s, --syslog-disable   Disable syslog and print to standard out.
-h, --help             Show this help text.
-V, --version          Print the …
```
> [border-agent] improve the documentation returned by --help

- tests/gtest/fake_posix_platform.cpp
- tests/gtest/test_rcp_host_api.cpp
This PR adds a unit test for `RcpHost::SetCountryCode`.
The PR also fixes an issue of current usage of `FakePlatform`. In each gtest case, we should get a new OT Instance. Otherwise the OT instance used in last gtest case will have some remaining tasks which are invalid to process.
> [tests] add unit test for RcpHost SetCountryCode

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds the SetChannelMaxPower method to ThreadHost.
The PR implements this method for RcpHost. The implementation for NCP will be added later.
> [thread-host] add set channel max power api

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
Only the encoder is needed for the encoding functions. This commit voids passing unnecessary context to them.
> [ncp] pass necessary encoder to encoding func

- src/trel_dnssd/trel_dnssd.cpp
As it's possible to switch network interface for TREL in https://github.com/openthread/openthread/pull/10872, updated trel_dnssd.cpp in 2 places:
1). Initialize() can be called multiple times now, so it should clear the mTrelNetifIndex at the beginning to refresh the index according to the given interface name.
2). HandleMdnsState() may be invoked when TrelDnssd is not initialized, we should still update the mMdnsPublisherReady status, so it's ready to publish a service when TrelDnssd becomes initialized.
> [trel] updates for switching trel interface

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- src/ncp/thread_host.cpp
- tests/scripts/bootstrap.sh
- tests/scripts/expect/_common.exp
- tests/scripts/expect/ncp_border_routing.exp
- tests/scripts/ncp_mode
This PR integrates the `InfraIf` module with `NcpHost` to make the border routing function work under NCP mode.
The PR also adds an integration test to test the border routing functionality. To execute this test, docker is used to simulate two devices connected by a infrastructure link (docker network bridge). otbr-agent runs inside the docker and we ping from the host machine to a simulated cli ftd nodes using its OMR address. Some code is added in the test scripts to support testing with docker.
> [ncp] integrate InfraIf module with NcpHost to make border routing work

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds `AddThreadStateChangedCallback` as a `ThreadHost` API.
Because this method is also needed under NCP mode. The PR doesn't change the implementation in RcpHost and adds an empty implementation in NcpHost.
> [thread-host] make AddThreadStateChangedCallback as a ThreadHost API

- src/agent/application.cpp
- src/agent/application.hpp
- src/agent/main.cpp
This PR refactors the `Application` class.
In specific:
1. Decouple `Application` with `InfraLinkSelector` by moving `InfraLinkSelector` out of the `Application` class. The current dependency causes that we cannot move the creation of `ThreadHost` instance out of the constructor of the `Application` class.
2. Move `Ncp::ThreadHost::Create` out of the `Application` constructor.
This change solves the fuzzer test issue in Android: When we create an `Application` object, we have to initlialize the radio which will cause error in the fuzz environment. With this change, we can pass a FuzzThreadHost object to the `Application`.
> [application] move ThreadHost::Create out of the Application class

- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
This PR fixes a critical issue in NcpSpinel parsing methods.
The parsing methods use `uint8_t` as the length of input frame which is not sufficient for large frame like Ip6StreamNet, which could be at most 1000+ bytes.
> [ncp] fix ncp spinel parsing methods

- .github/workflows/macOS.yml
Fix macOS build issue caused by pkg-config conflicts.
Unlinking pkg-config before reinstalling it in the MacOS build workflow. This resolves issues arising from stale or conflicting installations of pkg-config, which can lead to build failures.
> [github-actions] fix MacOS build error: unlink pkg-config before reinstalling

- script/reference-device/dhcp6_pd_daemon.py
Removes unnecessary sudo commands from dhcp6_pd_daemon.py.
The script was already running as root due to the `User=root` setting in the `systemd` service file. The internal `sudo` calls were redundant and caused issues with dbus context switching, preventing the script from receiving dbus signals correctly. This change removes the `sudo` calls, ensuring the script operates within a consistent dbus context and resolves the signal handling problems.
This commit addresses the issue where the dhcp6_pd_daemon was not responding to changes in the Dhcp6PdState dbus property.
> [pd] pd daemon service: remove redundant subprocess 'sudo' in python script

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
This PR adds a few common network properties to `ThreadHost`.
The direct usage of these properties is in Android platform when refreshing the state. With this PR, that process can work for both NCP & RCP. This PR only implements the Get methods for RCP. The NCP version will be implemented later.
> [thread-host] add common network properties

- src/ncp/posix/infra_if.hpp
This PR adds virtual destructor for InfraIf::Dependencies.
On some platforms this will cause build warnings and errors.
> [posix] add virtual destructor for InfraIf::Dependencies

- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
- tests/gtest/test_rcp_host_api.cpp
This PR adds `AddThreadEnabledStateChangedCallback` to `ThreadHost` and implements it for RcpHost.
Since the `ThreadEnabledState` is subscribed by some platform services, (for example, on Android) and this state is also required to implement `Join`, `Leave`, `ScheduleMigration` and `SetThreadEnabled`, this PR adds the `ThreadEnabledState` to `RcpHost` and provide an API to allow other components to subscribe to this state.
This PR makes the behavior of `ScheduleMigration` and `SetThreadEnabled` same as the Android binder API. And the unit test is updated accordingly.
> [thread-host] add ThreadEnabled state callback

- .github/workflows/macOS.yml
There are macOS workflow failures for new PRs like [this](https://github.com/openthread/ot-br-posix/actions/runs/12006912636/job/33467422370?pr=2618): 
```
Error: No such keg: /opt/homebrew/Cellar/pkg-config
```
I checked [macos-14-Readme.md](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md) and noticed that some dependencies (like `pkg-config`) of the macOS workflow are already satisfied by the image so we don't have to reinstall them again.
Also, this PR removes `dbus` in the macOS workflow because D-BUS is not enabled when building OTBR.
> [continuous-integration] fix and clean up macOS.yml

- src/agent/main.cpp
- src/common/logging.cpp
Developers can use the command `ot-ctl log level 5` to change the default log level to DEBUG. Sometimes, the `ot-daemon` crashes before developers can run the ot-ctl command on Android.
This commit adds the Android log system support, so that developers can run the command `setprop log.tag.ot-daemon DEBUG` to change the log level before the ot-daemon runs. The log output format is the same with using the Linux log system.
> [log] add Android log system support

- tests/scripts/ncp_mode
The PR fixes issue in the github action for testing NCP border routing.
Without `sudo` the option cannot be set successfully, and border routing cannot work in the test. Currently the expect script isn't strong enough to detect this problem. I'll enhance the script soon.
> [github-actions] fix NCP border routing setup

- src/dbus/server/dbus_thread_object_ncp.cpp
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- src/ncp/thread_host.hpp
- tests/gtest/test_rcp_host_api.cpp
This PR updates the `ThreadHost::Leave` method.
This PR adds a parameter `aEraseDataset` to the method. This PR also implements this method for `RcpHost`. The implementation is consistent with the android implementation. The PR also adds a unit test for `RcpHost::Leave`.
> [thread-host] update Leave method

- .github/workflows/ncp_mode.yml
- src/agent/application.cpp
- src/agent/application.hpp
- src/ncp/ncp_host.cpp
- src/ncp/ncp_host.hpp
- src/ncp/ncp_spinel.cpp
- src/ncp/ncp_spinel.hpp
- tests/scripts/bootstrap.sh
- tests/scripts/expect/ncp_srp_server.exp
- tests/scripts/ncp_mode
This PR integrates the mDNS Publisher with NcpHost to make advertising proxy work under NCP mode.
The PR adds an expect test to verify the advertising proxy function under NCP mode. To do the test, `avahi-browser` is used. So it's added into the bootstrap of the CI for ncp_mode.
As an abstraction: 
1. The PR adds `NcpSpinel::SrpServerSetEnabled` and `NcpSpinel::SrpServerSetAutoEnableMode` to control the SRP server on the NCP.
2. The PR adds the handling of `SPINEL_PROP_DNSSD_HOST`, `SPINEL_PROP_DNSSD_SERVICE` and `SPINEL_PROP_DNSSD_KEY_RECORD` to help NCP to publish the dnssd entries (by using the mDNSPublisher on the host).
> [ncp] integrate SRP Server and Advertising Proxy for NCP

- src/ncp/rcp_host.cpp
- src/ncp/rcp_host.hpp
- tests/gtest/test_rcp_host_api.cpp
This PR implements the RcpHost::Join method.
The implementation is exactly the same as Android binder API's implementation. This PR also adds a unit test to check the Join method.
> [thread-host] implement join for rcp host

- src/common/api_strings.cpp
- src/common/api_strings.hpp
- src/rest/json.cpp
- src/rest/json.hpp
- src/rest/openapi.yaml
- src/rest/resource.cpp
- src/rest/resource.hpp
- src/rest/types.hpp
- src/utils/hex.cpp
- src/utils/hex.hpp
Added endpoints to the REST server to expose commissioner functionality over the REST API
These changes intend to implement commissioner functionality in the same style as the current rest API offering.
- The `/node/commissioner/state` endpoint allows the user to get/set the commissioner state using GET and PUT requests respectively.
- The `/node/commissioner/joiner` allows the user to manage joiners accepted by the commissioner, supporting POST, GET and DELETE request methods to add, get and remove a joiner respectively. 
All added endpoints and their usage have been documented in the openapi.yaml
Example usage:
Please give me feedback and let me know of any required changes 😄
> [rest] add commissioner api

- src/dbus/server/dbus_thread_object_rcp.cpp
This PR simplifies the way to get OT instance in DbusThreadObjectRcp.
> [dbus] simplify getting OT instance in dbus RCP thread object

- src/rest/openapi.yaml
- src/rest/resource.cpp
- src/rest/resource.hpp
- tests/rest/test_rest.py
We'd like to access the current NCP/RCP coprocessor firmware version string from the REST API. I've added a new API endpoint under `/node/coprocessor/version` that fetches it with `GetCoprocessorVersion()`.
> [rest] add coprocessor version string API

- src/host/posix/CMakeLists.txt
- src/host/posix/dnssd.cpp
- src/host/posix/dnssd.hpp
This PR adds `DnssdPlatform` module to implement OT platform DNSSD APIs.
This PR follows up the unmerged PR: https://github.com/openthread/ot-br-posix/pull/2042
This PR is part of the effort to move the BorderAgent MeshCoP Service Publisher into OT core: https://github.com/openthread/ot-br-posix/issues/2658
In this PR, `DnssdPlatform` is added but not used yet. It will be enabled and used later when the native Border Agent MeshCoP Service publishing is ready.
In this PR, these platform DNSSD APIs are implemented while the rest of them has an empty implementation and will be implemented when necessary:
* otPlatDnssdGetState
* otPlatDnssdRegisterService
* otPlatDnssdUnregisterService
* otPlatDnssdRegisterHost
* otPlatDnssdUnregisterHost
* otPlatDnssdRegisterKey
* otPlatDnssdUnregisterKey
> [platform] implement platform dnssd apis

- src/host/rcp_host.hpp
These methods are already moved to the 'BackboneRouter' class and has no implementation in 'RcpHost'.
> [host] remove unused methods in RcpHost

- src/web/CMakeLists.txt
Do not unconditionally set `Boost_USE_STATIC_LIBS` but instead default it to `true`.
This allows building with shared Boost libraries, which can be useful for OS distribution packaging, for example.
The default is the same if not defined, so this is a backwards compatible change: unless explicitly set to `false`, static Boost libs will still be used.
In particular, this is useful for NixOS, where the static Boost lib will not work.
See also:
* #2652 
* https://github.com/NixOS/nixpkgs/pull/332296#pullrequestreview-2523338288
> [build] allow using shared boost libraries

- CMakeLists.txt
Add `INSTALL_SYSTEMD_UNIT` which can explicitly be set to `false` to disable installing the service unit even if systemd is available.
If not defined, it defaults to true, i.e. the systemed service unit is created. As a result, this change is backwards compatible: it's required to _opt-out_ of systemd unit installation.
In particular, this is useful for NixOS, where a systemd unit will be created independently from the CMake build.
See also:
* https://github.com/NixOS/nixpkgs/pull/332296#pullrequestreview-2523338288
> [build] allow disabling systemd service unit install

- tests/scripts/bootstrap.sh
This PR removes the if branch of BUILD_TARGET of 'otbr-dbus-check' in the bootstrap script.
In our CI, there is no such target now. All the targets:
```
➜  ot-br-posix git:(clean_up_bootstrap) ✗ grep -rnI --exclude-dir={build,third_party} BUILD_TARGET ./.github/
./.github/workflows/openwrt.yml:52:        BUILD_TARGET: "openwrt-check"
./.github/workflows/build.yml:50:      run: BUILD_TARGET=pretty-check tests/scripts/bootstrap.sh
./.github/workflows/build.yml:62:      BUILD_TARGET: check
./.github/workflows/build.yml:85:      BUILD_TARGET: check
./.github/workflows/build.yml:104:      BUILD_TARGET: script-check
./.github/workflows/build.yml:120:      BUILD_TARGET: scan-build
./.github/workflows/build.yml:135:      BUILD_TARGET: package
./.github/workflows/build.yml:152:      BUILD_TARGET: …
```
> [tests] remove stale code in test bootstrap script

- src/dbus/common/constants.hpp
- src/dbus/server/dbus_thread_object_rcp.cpp
- src/dbus/server/dbus_thread_object_rcp.hpp
This PR adds DBus methods 'Join' and 'SetThreadEnabled' under RCP mode.
The background is to support these basic methods for both NCP & RCP mode so that we can write some test scripts that work for both NCP & RCP mode. For the long term, we also try to let NCP & RCP support the same DBus interfaces.
> [dbus] add Join and SetThreadEnabled method to Dbus RCP

- src/common/task_runner.cpp
This PR adds a check in TaskRunner::Process so that 'read' is only executed when the eventFd is set.
Currently if we use strace to see the i/o of otbr-agent, we can see many things like this:
```
read(7, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
read(9, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
read(4, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
read(7, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
read(9, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
read(4, 0x7ffc7c0f80ff, 1)              = -1 EAGAIN (Resource temporarily unavailable)
```
Though this is harmless, we should avoid it as possible for easier debugging …
> [task-runner] only perform read when FD is set

- .github/workflows/docker.yml
- etc/docker/Dockerfile
Reverts openthread/ot-br-posix#2698
Fixes https://github.com/openthread/openthread/issues/11233
> Revert "[docker] use `arm64` runner instead of `qemu`"

- src/mdns/mdns_mdnssd.cpp
Addressing the comment: https://github.com/openthread/ot-br-posix/pull/2677#discussion_r1956830008
> [mdns] check if the `Publisher` is ready in `Register()` and `Unregister()` for mDNSResponder

- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
- src/sdp_proxy/discovery_proxy.cpp
- src/sdp_proxy/discovery_proxy.hpp
This commit modifies the `Publisher` to stop filtering link-local addresses during service or host resolution. Instead, the `DiscoveryProxy` now handles link-local address filtering. This change allows the `Publisher` to properly resolve TREL peers, which require link-local addresses.
> [mdns-publisher] move link-local address filtering to DiscoveryProxy

- src/agent/application.cpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
This PR implements `Init()` and `Deinit()` for `BorderAgent`. This is to support the case on Android that we need to properly  re-initialize the `BorderAgent` after leaving a network. Previously the Thread state callback was registered in the constructor so it goes away after `Deinit` of `ThreadHost` and will never get back.
> [border-agent] add `Init()` and `Deinit()` for `BorderAgent` 

- src/host/ncp_spinel.cpp
This PR adds handling for some NCP properites.
Currently theere are some logs like:
```
2025-02-27T10:57:03.981495+08:00 otbr-agent[424273]: [CRIT]-NcpSpin-: Received unexpected response with (cmd:6, key:0), waiting (cmd:3, key:2353) for tid:3
2025-02-27T02:38:29.478937+00:00 rpi-4 otbr-agent[6900]: [WARN]-NcpSpin-: Received uncognized key: 5389
2025-02-27T02:38:29.479525+00:00 rpi-4 otbr-agent[6900]: [WARN]-NcpSpin-: Received uncognized key: 90
2025-02-27T02:38:29.480519+00:00 rpi-4 otbr-agent[6900]: [WARN]-NcpSpin-: Received uncognized key: 91
```
This PR adds handling for these properties to avoid these warning logs. For unsolicited notification cases, add `case` for these properties to avoid that they go to the default case and emit warnings.
> [ncp] add handling for unused properties to avoid warning logs

- .github/workflows/border_router.yml
- .github/workflows/build.yml
- .github/workflows/raspbian.yml
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
> [github-actions] update runner from `ubuntu-20.04` to `ubuntu-22.04`

- src/mdns/mdns.cpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_avahi.hpp
This commit enhances `Mdns::Publisher` using Avahi to utilize the events `AVAHI_BROWSER_ALL_FOR_NOW` which notify that all records have been processed and no further results are expected in the near future.
This improvement prevents premature "resolved" callbacks after receiving only the initial IPv6 address, thereby improving host and service address resolution. The `Publisher` now waits for these events to ensure it gathers all available addresses from the cache and query responses before signaling resolved callback. 
---
Resolves #2711
> [mdns-avahi] utilize Avahi events for complete result handling

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/dbus/server/dbus_thread_object_rcp.cpp
- src/utils/thread_helper.cpp
- src/utils/thread_helper.hpp
This PR refactors the MeshCoP TXT update method in BorderAgent.
This is a DBUS method for vendors to update their vendor MeshCoP TXT values. The current call stack is:
```
DBus Handler -> ThreadHelper MeshCoP update callback -> BorderAgent Handle MeshCoP update
```
ThreadHelper is totally unnecessary here. So the new stack is simpler:
```
DBus Handler -> BorderAgent Handle MeshCoP update
```
Another intention is to unbind the BorderAgent module from `ThreadHelper` so that it can works in NCP design.
> [border agent] refactor dbus meshcop txt update

- src/host/posix/CMakeLists.txt
- src/host/posix/udp_proxy.cpp
- src/host/posix/udp_proxy.hpp
- tests/gtest/CMakeLists.txt
- tests/gtest/test_udp_proxy.cpp
This PR adds a UDP Proxy module to do Thread commissioning under NCP architecture.
This PR is one of sub-task to support Border Agent under NCP mode. The UDP Proxy will also be used to do Thread commisssioning under RCP architecture and replace `OT_PLATFORM_UDP`.
Based on the OT border agent state changes (HandleBorderAgentStateChange), the module simply starts/stops listening on an UDP ephemeral port and if starts, sets a mapping between OT border agent UDP port and the port on host. And then it does bidrectional UDP forwarding:
* `Dependencies::UdpForward` will be implemented as OT UDP forwarding to OT core.
* `SendToPeer` will send a UDP packet to the remote peer using the local host port (that maps to OT border agent port) as the source port.
The module hasn't been integrated with the …
> [border-agent] add UDP Proxy module for Thread commissioning

- src/agent/application.cpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/rcp_host.cpp
- src/host/rcp_host.hpp
- src/host/thread_host.hpp
This PR refactors the Epskc state change handling in BorderAgent.
The PR adds an API `AddEphemeralKeyStateChangedCallback` in `ThreadHost` to add ephemeral key state callback so that the application rely on this API and unbind `BorderAgent` from OT instance. The intention is to make BorderAgent able to work in NCP mode as well.
> [border-agent] refactor epskc state change handling

- src/agent/application.cpp
- src/agent/application.hpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/ncp_spinel.hpp
- src/host/posix/netif.cpp
- src/host/posix/netif.hpp
- tests/dbus/test_dbus_client.cpp
- tests/gtest/test_infra_if.cpp
- tests/gtest/test_netif.cpp
This PR refactors the `otbr::Netif` module to move it from `NcpHost` to the `Application`.
The intention behind this PR:
1. We will soon introduce a new module `MulticastRoutingManager` which will need to get the Thread wpan interface index. While we can set a copy to `MulticastRoutingManager`, it's better to have a SSOT. And the `Netif` module will also be able to accessed from other modules in `Application` later.
2. Currently the `Netif` module is only used for NCP. But we will use it for the RCP design as well later and replace the netif module in openthread posix.
> [posix] refactor netif module

- tests/gtest/test_netif.cpp
This PR fixes a flaky unit test in test netif (`WpanIfRecvIp6PacketCorrectly_AfterReceivingFromNetif`).
The cause is that if we call `recvfrom` right after `Netif::Ip6Receive`, it is possible that the system hasn't passed the message and the program hangs on `recvfrom`. Then the program will hang forever.
I've seen the failure in CI for many times. I've verified the test locally for 10 times with this change.
> [test] fix flaky unit test of test_netif

- src/agent/application.cpp
- src/agent/application.hpp
- src/host/ncp_host.cpp
- src/host/ncp_spinel.cpp
- src/host/ncp_spinel.hpp
- tests/scripts/expect/_common.exp
- tests/scripts/expect/ncp_border_agent.exp
- tests/scripts/ncp_mode
This PR adds meshcop service publishing in NCP mode.
A expect test is also added in the PR to verify that the meshcop service is correctly published.
> [ncp] add meshcop service publishing in NCP mode

- src/dbus/server/dbus_request.hpp
The current behavior of `ReplyOtResult` is that it will print an `ERROR` logging when the error is not `OT_ERROR_NONE`. This may not be appropriate because the error may not indicate a fault in the system. For example, it shouldn't be concerning if `GetActiveDatasetTlvs` returns `NotFound` while the TBR hasn't got any credentials.
This PR lowers the log level to INFO to reduce false alarms.
> [dbus] lower the log level in `ReplyOtResult` on error to reduce false alarms 

- src/agent/application.cpp
- src/agent/application.hpp
- src/dbus/server/dbus_agent.cpp
- src/dbus/server/dbus_agent.hpp
- src/dbus/server/dbus_object.hpp
- src/dbus/server/dbus_thread_object_ncp.cpp
- src/dbus/server/dbus_thread_object_ncp.hpp
- src/dbus/server/dbus_thread_object_rcp.cpp
- src/dbus/server/dbus_thread_object_rcp.hpp
This PR refactors the DBusAgent module to unbind it with the BORDER_AGENT_ENABLE flag as well as simply the code.
Currently the `mDBusAgent` is guarded with `#if OTBR_ENABLE_DBUS_SERVER && OTBR_ENABLE_BORDER_AGENT`. `OTBR_ENABLE_BORDER_AGENT` shouldn't be a precondition to enable the DBus server. 
We have the current code because the DBusAgent relies on the BorderAgent when `OTBR_ENABLE_BORDER_AGENT` is enabled. However the code to inject the `BorderAgent` to DBusAgent is cumbersome: We have to write two versions of constructor or init for many classes. So as of now we only have one constructor which always accepts a `BorderAgent`.
This PR introduces a helper class `DBus::DependentComponents`. The constructor and init method will always accept this class. And we control the fields in this …
> [dbus] refactor dbus module to unbind it with border agent feature

- .github/workflows/ncp_mode.yml
- src/agent/application.cpp
- src/agent/application.hpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/ncp_spinel.cpp
- src/host/ncp_spinel.hpp
- src/host/rcp_host.cpp
- src/host/rcp_host.hpp
- src/host/thread_host.hpp
- tests/gtest/CMakeLists.txt
- tests/scripts/expect/_common.exp
- tests/scripts/expect/ncp_border_agent.exp
- tests/scripts/ncp_mode
This PR implements meshcop commissioning in NCP mode.
This PR also introduces ot-commissioner installation in the `ncp_mode` script and extends the expect test of ncp_border_agent to verify the commissioning function in NCP mode.
This PR adds `SetUdpForwardToHostCallback`to `ThreadHost` and let `ThreadHost` implements `UdpProxy::Dependencies`. As of now `RcpHost` has an empty implementation. In later PRs we will implement it for `RcpHost` and repalce the platform UDP.
> [ncp] add meshcop commissioning in NCP mode

- src/agent/application.cpp
- src/agent/application.hpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/ncp_spinel.hpp
- src/host/posix/infra_if.cpp
- src/host/posix/infra_if.hpp
- tests/gtest/test_infra_if.cpp
This PR refactors the otbr::InfraIf module to move it from NcpHost to the Application.
The intention behind the PR is same as https://github.com/openthread/ot-br-posix/pull/2768
> [posix] refactor the infraif module

- src/agent/application.cpp
- src/agent/application.hpp
- src/host/posix/infra_if.cpp
- src/host/posix/infra_if.hpp
- tests/gtest/test_infra_if.cpp
This is a minor refactor CL which lets the code prefer `std::string` over C-style strings for convenience and safety.
> [infra-if] use `std::string` for infra network interface names

- src/dbus/server/introspect.xml
There is currently a handler for TrelInfo, but no introspect entry.
Example fetching information structure:
```
dbus-send --system --dest=io.openthread.BorderRouter.wpan0 --print-reply /io/openthread/BorderRouter/wpan0 org.freedesktop.DBus.Properties.Get string:io.openthread.BorderRouter string:TrelInfo
method return time=1744738821.325205 sender=:1.76 -> destination=:1.81 serial=19 reply_serial=2
variant       struct {
boolean true
uint16 0
struct {
uint64 0
uint64 0
uint64 0
uint64 0
uint64 0
}
}
```
> [dbus] add TrelInfo to introspect.xml

- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/ncp_spinel.cpp
- src/host/ncp_spinel.hpp
- src/host/rcp_host.cpp
- src/host/rcp_host.hpp
- src/host/thread_host.hpp
This PR adds "otMeshLocalPrefix" to "NetworkProperties" interface.
The intention is to make mesh local prefix available in both NCP & RCP modes. The Multicast Routihng Manager that is under development needs to use the mesh local prefix for check.
In NCP mode, the mesh local prefix is obtained from the notification of `SPINEL_PROP_IPV6_ML_ADDR`. Current NCP alreadys updates this property but it doesn't updates `SPINEL_PROP_IPV6_ML_PREFIX` to the host. So `SPINEL_PROP_IPV6_ML_ADDR` is used.
I've verified locally that in NCP mode the mesh local prefix can be obtained by the interface correctly.
> [host] add network property for mesh local prefix

- src/host/posix/dnssd.cpp
Adds empty implementation for `otPlatDnssdStartRecordQuerier()` and `otPlatDnssdStopRecordQuerier()` in the `posix/dnssd.cpp` file.
> [dnssd] add stub/empty implementation for new `otPlatDnssd` APIs

- script/bootstrap
1.4 OTBR certification testing requires reference devices to send some ND RA messages via `rdisc6` (eg. test DH_1_7).
> [bootstrap] for reference devices, install ndisc6

- src/common/types.cpp
- src/common/types.hpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/posix/CMakeLists.txt
- src/host/posix/infra_if.hpp
- src/host/posix/multicast_routing_manager.cpp
- src/host/posix/multicast_routing_manager.hpp
- src/host/posix/netif.hpp
- tests/gtest/CMakeLists.txt
- tests/gtest/test_backbone_multicast_routing.cpp
This PR adds the MulticastRoutingManager module for backbone router multicast forwarding feature.
The implementation follows the [multicast module](https://github.com/openthread/openthread/blob/main/src/posix/platform/multicast_routing.hpp) in Openthread posix.
In this PR the module isn't integrated into application. A unit test is added to test it. It will then be first used for NCP mode to enable the multicast forwarding feature.
> [bbr] add multicast routing manager

- tests/scripts/ncp_mode
This PR fixes the CI failure of ncp_border_routing.
I found that after removing `--ipv6` the otbr in docker cannot get the OMR address. But in my local run, it can work without `--ipv6` option.
This PR adds the original `--ipv6` option back and delete the 9101::1/64 address so that the ping tests through backbone1 interface can use the on-link address.
> [ncp] fix the docker network for ncp integration tests

- src/host/posix/dnssd.cpp
This commit updates `DnssdPlatform::RegisterService()` so it can correctly handle registering a service for the local host. The `otPlatDnssdRegisterService()` indicates this by setting the `mHostName` field in the passed-in `otPlatDnssdService` structure to null. As documented: "The `mHostName` field specifies the host name of the service if it is not NULL. Otherwise, if it is NULL, it indicates that this service is for the device itself and leaves the host name selection to DNS-SD platform."
The `Mdns::Publisher::PublishService()` expects `std::string` as input and assumes an empty host string to indicate the service is for the local host.
> [dnssd-platform] fix registering services for local host

- src/host/posix/dnssd.cpp
- src/host/posix/dnssd.hpp
This commit adds `#if` checks for `OTBR_ENABLE_DNSSD_PLAT` to the `dnssd` modules, ensuring the `otPlatDnssd` APIs are not provided unless this feature is enabled.
The `OTBR_ENABLE_DNSSD_PLAT` option controls the corresponding OpenThread core `OT_PLATFORM_DNSSD` configuration, which indicates that `otPlatDnssd` APIs are provided by the platform layer.
> [dnssd-platform] check `OTBR_ENABLE_DNSSD_PLAT` config

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
This commit adds `#if OTBR_ENABLE_BORDER_AGENT` guards to `border_agent.hpp` and `border_agent.cpp`. This ensures that definitions within these files are only compiled if the `OTBR_ENABLE_BORDER_AGENT` feature is enabled.
> [border-agent] add `OTBR_ENABLE_BORDER_AGENT` guards

- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
This commit simplifies the generation of the MeshCoP service instance name. The method is shortened to `GetServiceInstanceName()` and now uses the internal `mBaseServiceInstanceName` to generate the name. This change removes an unnecessary input parameter, as `mBaseServiceInstanceName` was always passed to it.
> [border-agent] simplify MeshCoP service name generation

- .github/workflows/border_router.yml
- etc/cmake/options.cmake
- src/agent/application.cpp
- src/border_agent/border_agent.cpp
- src/border_agent/border_agent.hpp
This commit adds the `OTBR_BORDER_AGENT_MESHCOP_SERVICE` CMake option, which maps to the `OTBR_ENABLE_BORDER_AGENT_MESHCOP_SERVICE` macro.
This new configuration controls whether the OTBR platform's `BorderAgent` module publishes the `_meshcop._udp` mDNS service (including the ePSKc service). It can be used to disable platform layer service registration so to enable/allow OpenThread core's Border Agent module to handle this responsibility.
This configuration is enabled by default. It is explicitly disabled in GitHub workflows, specifically in `border_router.yml`, where OpenThread core mDNS/DNS-SD support (along with use of the native SRP advertising proxy) is enabled.
> [border-agent] add `OTBR_BORDER_AGENT_MESHCOP_SERVICE` CMake option

- third_party/openthread/CMakeLists.txt
This commit updates `openthread/CMakeLists.txt` to ensure that `OT_BORDER_AGENT_MESHCOP_SERVICE` (which controls whether OpenThread core's Border Agent registers the MeshCoP service) is set to the inverse of `OTBR_BORDER_AGENT_MESHCOP_SERVICE`. This ensures that either OpenThread core or the OTBR platform handles the MeshCoP service registration and the configs are consistent.
> [config] set `OT_BORDER_AGENT_MESHCOP_SERVICE` based on OTBR config

- src/agent/application.hpp
When setting up OTBR on a Raspberry Pi 4 (`INFRA_IF_NAME=eth1 ./script/setup`), I got this build failure:
```
/home/pi/Documents/git/ot-br-posix/src/agent/application.hpp:205:5: error: ‘Dnssd’ does not name a type
205 |     Dnssd::DiscoveryProxy &GetDiscoveryProxy(void)
|     ^~~~~                                                             
compilation terminated due to -Wfatal-errors.
```
I think the issue doesn't happen in CI or linux machine because the two headers are indirectly included in header `border_agent.hpp`. But that doesn't work for the toolchain on my Raspberry Pi 4. Let's still add the headers here.
> [application] add missing headers

- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/rcp_host.hpp
- src/host/thread_host.hpp
This PR adds an API 'IsInitialized' to `ThreadHost`.
The intention is to provide a method for the application side to know whether ThreadHost APIs are ready to call. An immediate use case is add checks in Android OtDaemonServer binder methods.
> [host] add IsInitialized method

- .github/workflows/raspbian.yml
- tests/scripts/bootstrap.sh
- tests/scripts/check-raspbian
This PR extends the test scripts so that it can test with the recently raspbian OS versions. The recent raspbian OS can only be downloaded in `.xz` format instead of `.zip` so the current test script doesn't work with it. The PR also adds a test to verify the latest 2025-05-13 version of raspios.
> [ci] add raspbian build check for bookworm version

- include/openthread-br/config.h
This PR introduces a new macro `OTBR_USER_CONFIG_HEADER_ENABLE`. When it's defined and `OTBR_CONFIG_FILE` is not defined, OTBR will use the user-provided header file `ot-br-posix-user-config.h` to configure the build time options.
This is similar to OpenThread's `openthread-core-user-config.h`.
> [build] provides an option to enable `ot-br-posix-user-config.h` header file

- src/host/posix/dnssd.cpp
This PR removes unnecessary usage of `OTBR_UNUSED_VARIABLE` in dnssd source.
> [dnssd] remove unnecessary OTBR_UNUSED_VARIABLE

- src/mdns/mdns.cpp
- src/mdns/mdns.hpp
- src/mdns/mdns_avahi.cpp
- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
This PR adds handling for the retryable mDNSResponder errors.
For example, on `kDNSServiceErr_DefunctConnection` we need to redo the registration or the query instead of giving up. Currently the retry interval is 5 seconds.
> [mdns] handle retryable mDNSResponder errors

- src/agent/CMakeLists.txt
- src/host/CMakeLists.txt
- tests/gtest/CMakeLists.txt
This PR renames the cmake library `otbr-ncp` to `otbr-host`.
The name is confusing. It's a legacy name corresponds to the removed class `NcpOpenThreadController`. Since the this library supports both RCP and NCP and its namespace is `Host`, let's rename the library.
> [cmake] rename the library otbr-ncp to otbr-host

- src/common/types.cpp
- src/common/types.hpp
- src/host/posix/CMakeLists.txt
- src/host/posix/dnssd.cpp
- src/host/posix/dnssd.hpp
- src/mdns/mdns.cpp
- tests/gtest/CMakeLists.txt
- tests/gtest/test_dnssd.cpp
Following https://github.com/openthread/ot-br-posix/pull/2042 and https://github.com/openthread/ot-br-posix/pull/2664, this PR implements other `otPlatDnssd` platform APIs in ot-br-posix. 
The PR implements all the dnssd platform APIs for browse/resolve except for `RecordQuerier` because currently the mdns publisher doesn't support record query. I plan to support this later.
The background for this PR is that I plan to use the natvie OT discovery proxy and remove the current Discovery Proxy module in ot-br-posix. I've noticed that OT now even supports native mDNS. But to support DNSSD runtime selection (OPENTHREAD_CONFIG_PLATFORM_DNSSD_ALLOW_RUN_TIME_SELECTION), we will also need an implementation on the posix platform.
The implementation in this PR basically follows the old PR …
> [dnssd] implement Dnssd Browser/Resolver APIs

- src/mdns/mdns_mdnssd.cpp
- tests/scripts/ncp_mode
This PR tries to fix the frequent CI failure of ncp_mode.
For example: https://github.com/openthread/ot-br-posix/actions/runs/16956074962/job/48058480421
I believe this time I find the true cause. I can reproduce this issue in CI environment **occasionally**. And I found when the issue occurred:
```
Aug 14 07:22:43 pkrvm0wrmc9nc7o otbr-agent[30503]: [INFO]-MDNS----: Registering service OpenThread BorderRouter #8D4B._meshcop._udp
Aug 14 07:23:44 pkrvm0wrmc9nc7o otbr-agent[30503]: dnssd_clientstub set_waitlimit:_daemon timed out (60 secs) without any response: Socket 21
Aug 14 07:23:44 pkrvm0wrmc9nc7o otbr-agent[30503]: [INFO]-MDNS----: After DNSServiceRegister
Aug 14 07:23:44 pkrvm0wrmc9nc7o otbr-agent[30503]: [INFO]-MDNS----: HandleRegisterResult with dnsError
Aug 14 07:23:44 …
```
> [tests] restart mDNSResponder service in ncp_mode test setup

- src/common/CMakeLists.txt
- src/host/CMakeLists.txt
- src/utils/CMakeLists.txt
This PR removes some unnecessary dependencies on `otbr-proto`
> [build] remove unnecessary link to otbr-proto

- src/mdns/mdns_mdnssd.cpp
- src/mdns/mdns_mdnssd.hpp
While testing TREL in our BR implementation we started seeing forced exits due to "too many open files".
Closer investigation showed a file descriptor leak that was growing by `n` descriptors every five minutes
where `n` is equal to the number of discoverable `_trel._udp` services on the network. These file descriptors
were found to be open sockets to `mdnsResponder` at `/var/run/mdnsd`. 
The root cause is due to accumulation of `ServiceInstanceResolution` objects in the `mResolvingInstances`
vector in `PublisherMDnsSd::ServiceSubscription` that are never removed. As a result the `DNSServiceRef`
handles owned by the `ServiceInstanceResolution` are never deallocated. I believe this issue may have
been introduced in [this PR](https://github.com/openthread/ot-br-posix/pull/2148) when the …
> [mdns] fix ServiceInstanceResolutions leak in mdnssd

- src/agent/application.cpp
- src/host/ncp_host.cpp
- src/host/ncp_host.hpp
- src/host/ncp_spinel.hpp
This change fixes a build failure in NCP mode that occurs when the Border Agent with MeshCoP service is enabled `OTBR_ENABLE_BORDER_AGENT && OTBR_ENABLE_BORDER_AGENT_MESHCOP_SERVICE` while the SRP advertising proxy `OTBR_ENABLE_SRP_ADVERTISING_PROXY` is disabled.
> [mdns] align preprocessor guard for `NcpHost::SetMdnsPublisher`

- src/common/logging.hpp
When compiling the file `src/common/logging.hpp` using the blaze for the Raspberry Pi platform, the compiler reports the following error:
Compiling third_party/ot_posix/src/common/logging.hpp failed: (Exit 1) arm-oe-linux-gnueabi-clang failed: error executing CppCompileHeader command (from cc_library rule target //third_party/ot_posix/src/common:common) arm-oe-linux-gnueabi-clang '--target=arm-oe-linux-gnueabi' '-mcpu=cortex-a7' '-mtune=cortex-a7' -mthumb ... (remaining 211 arguments skipped).  [forge_remote_host=jrbks1] third_party/ot_posix/src/common/logging.hpp:45:2: error: "OTBR_LOG_TAG is not defined"
45 | #error "OTBR_LOG_TAG is not defined"
This commit sets the default log tag to the string `OTBR` to avoid the build error.
> [log] set the default log tag to `OTBR`

- src/agent/CMakeLists.txt
- src/agent/realmain.cpp
- src/agent/realmain.hpp
The file `main.cpp` includes many functions for the OTBR Agent. To generate a library that contains all functions of the OTBR Agent, functions in `main.cpp` should be moved to another file to be re-used in the library.
This commit moves all methods in `main()` to a new file `realmain.cpp` and provides an API for running the OTBR Agent.
> [main] move all methods in the`main.cpp` file to the `realmain.cpp` file

- src/common/CMakeLists.txt
- src/host/CMakeLists.txt
- tests/gtest/CMakeLists.txt
This PR fixes the link dependency of `otbr-common` module.
The common module doesn't use any implementation in OT so it doesn't need to link `openthread-ftd` at all. Instead, the `otbr-host` module needs to link `openthread-ftd`.
Removing the dependency makes `otbr-common` reusable for some unit tests. (The unit test target doesn't link to the whole bunch of stuffs)
> [build] fix the link target of common module

- tests/dbus/test_dbus_client.cpp
The TREL state may not always be enabled when `CheckTrelInfo()` or `CheckTelemetryData()` are called, and assuming this state  makes the test brittle. This change removes theses assertions.
These checks were always flawed. Previously, `ot-br-posix` feature flags would disable TREL upon stack initialization, but then bringing the Thread netif up would re-enable all radio links, including TREL. The `test-dbus-client` was unintentionally validating this incorrect behavior.
Recent changes in OpenThread PR #11944 enhanced this behavior to distinguish between user and stack TREL enable requests. A key change is that a user's request to disable TREL is now persistent. If the user explicitly disables TREL, it remains disabled regardless of Thread stack state changes and other API calls. The user …
> [tests-dbus] remove assertion on `trelInfo.mEnabled` 

- script/update
The `update` script is broken since `_dhcpv6_pd` was removed.
> [script] fix dhcpv6_pd implementation in script/update

- tests/dbus/test-client
This commit removes the test steps that verify the presence of the `nn` (network name) TXT entry in the MeshCoP DNS-SD service.
This change aligns the test with a recent behavior modification in the OpenThread core (PR 11989), which no longer advertises the `nn` entry if a valid network dataset is not available. This prevents a Border Agent from prematurely advertising a default or invalid Network Name or Extended PAN ID during boot-up before it gets valid network information.
> [dbus-test] remove check for 'nn' (network name) in meshcop service
